// Code generated by capnpc-go. DO NOT EDIT.

package differentiation

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
)

type Hessian capnp.Client

// Hessian_TypeID is the unique identifier for the type Hessian.
const Hessian_TypeID = 0xa7ba4284e333a8d4

func (c Hessian) Write(ctx context.Context, params func(Hessian_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa7ba4284e333a8d4,
			MethodID:      0,
			InterfaceName: "nomagique/differentiation/hessian.capnp:Hessian",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Hessian_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Hessian) Done(ctx context.Context, params func(Hessian_done_Params) error) (Hessian_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa7ba4284e333a8d4,
			MethodID:      1,
			InterfaceName: "nomagique/differentiation/hessian.capnp:Hessian",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Hessian_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Hessian_done_Results_Future{Future: ans.Future()}, release

}

func (c Hessian) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Hessian) String() string {
	return "Hessian(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Hessian) AddRef() Hessian {
	return Hessian(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Hessian) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Hessian) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Hessian) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Hessian) DecodeFromPtr(p capnp.Ptr) Hessian {
	return Hessian(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Hessian) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Hessian) IsSame(other Hessian) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Hessian) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Hessian) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Hessian_Server is a Hessian with a local implementation.
type Hessian_Server interface {
	Write(context.Context, Hessian_write) error

	Done(context.Context, Hessian_done) error
}

// Hessian_NewServer creates a new Server from an implementation of Hessian_Server.
func Hessian_NewServer(s Hessian_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Hessian_Methods(nil, s), s, c)
}

// Hessian_ServerToClient creates a new Client from an implementation of Hessian_Server.
// The caller is responsible for calling Release on the returned Client.
func Hessian_ServerToClient(s Hessian_Server) Hessian {
	return Hessian(capnp.NewClient(Hessian_NewServer(s)))
}

// Hessian_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Hessian_Methods(methods []server.Method, s Hessian_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa7ba4284e333a8d4,
			MethodID:      0,
			InterfaceName: "nomagique/differentiation/hessian.capnp:Hessian",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Hessian_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa7ba4284e333a8d4,
			MethodID:      1,
			InterfaceName: "nomagique/differentiation/hessian.capnp:Hessian",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Hessian_done{call})
		},
	})

	return methods
}

// Hessian_write holds the state for a server call to Hessian.write.
// See server.Call for documentation.
type Hessian_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Hessian_write) Args() Hessian_write_Params {
	return Hessian_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Hessian_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Hessian_done holds the state for a server call to Hessian.done.
// See server.Call for documentation.
type Hessian_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Hessian_done) Args() Hessian_done_Params {
	return Hessian_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Hessian_done) AllocResults() (Hessian_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Hessian_done_Results(r), err
}

// Hessian_List is a list of Hessian.
type Hessian_List = capnp.CapList[Hessian]

// NewHessian_List creates a new list of Hessian.
func NewHessian_List(s *capnp.Segment, sz int32) (Hessian_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Hessian](l), err
}

type Hessian_write_Params capnp.Struct

// Hessian_write_Params_TypeID is the unique identifier for the type Hessian_write_Params.
const Hessian_write_Params_TypeID = 0xf37c7eef258dd6c1

func NewHessian_write_Params(s *capnp.Segment) (Hessian_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return Hessian_write_Params(st), err
}

func NewRootHessian_write_Params(s *capnp.Segment) (Hessian_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return Hessian_write_Params(st), err
}

func ReadRootHessian_write_Params(msg *capnp.Message) (Hessian_write_Params, error) {
	root, err := msg.Root()
	return Hessian_write_Params(root.Struct()), err
}

func (s Hessian_write_Params) String() string {
	str, _ := text.Marshal(0xf37c7eef258dd6c1, capnp.Struct(s))
	return str
}

func (s Hessian_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Hessian_write_Params) DecodeFromPtr(p capnp.Ptr) Hessian_write_Params {
	return Hessian_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Hessian_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Hessian_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Hessian_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Hessian_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Hessian_write_Params) Coeffs() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.Float64List(p.List()), err
}

func (s Hessian_write_Params) HasCoeffs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Hessian_write_Params) SetCoeffs(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewCoeffs sets the coeffs field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Hessian_write_Params) NewCoeffs(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Hessian_write_Params) X() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.Float64List(p.List()), err
}

func (s Hessian_write_Params) HasX() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Hessian_write_Params) SetX(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewX sets the x field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Hessian_write_Params) NewX(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Hessian_write_Params) Dim() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s Hessian_write_Params) SetDim(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

// Hessian_write_Params_List is a list of Hessian_write_Params.
type Hessian_write_Params_List = capnp.StructList[Hessian_write_Params]

// NewHessian_write_Params creates a new list of Hessian_write_Params.
func NewHessian_write_Params_List(s *capnp.Segment, sz int32) (Hessian_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[Hessian_write_Params](l), err
}

// Hessian_write_Params_Future is a wrapper for a Hessian_write_Params promised by a client call.
type Hessian_write_Params_Future struct{ *capnp.Future }

func (f Hessian_write_Params_Future) Struct() (Hessian_write_Params, error) {
	p, err := f.Future.Ptr()
	return Hessian_write_Params(p.Struct()), err
}

type Hessian_done_Params capnp.Struct

// Hessian_done_Params_TypeID is the unique identifier for the type Hessian_done_Params.
const Hessian_done_Params_TypeID = 0x91f5350d54eedbd5

func NewHessian_done_Params(s *capnp.Segment) (Hessian_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Hessian_done_Params(st), err
}

func NewRootHessian_done_Params(s *capnp.Segment) (Hessian_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Hessian_done_Params(st), err
}

func ReadRootHessian_done_Params(msg *capnp.Message) (Hessian_done_Params, error) {
	root, err := msg.Root()
	return Hessian_done_Params(root.Struct()), err
}

func (s Hessian_done_Params) String() string {
	str, _ := text.Marshal(0x91f5350d54eedbd5, capnp.Struct(s))
	return str
}

func (s Hessian_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Hessian_done_Params) DecodeFromPtr(p capnp.Ptr) Hessian_done_Params {
	return Hessian_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Hessian_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Hessian_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Hessian_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Hessian_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Hessian_done_Params_List is a list of Hessian_done_Params.
type Hessian_done_Params_List = capnp.StructList[Hessian_done_Params]

// NewHessian_done_Params creates a new list of Hessian_done_Params.
func NewHessian_done_Params_List(s *capnp.Segment, sz int32) (Hessian_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Hessian_done_Params](l), err
}

// Hessian_done_Params_Future is a wrapper for a Hessian_done_Params promised by a client call.
type Hessian_done_Params_Future struct{ *capnp.Future }

func (f Hessian_done_Params_Future) Struct() (Hessian_done_Params, error) {
	p, err := f.Future.Ptr()
	return Hessian_done_Params(p.Struct()), err
}

type Hessian_done_Results capnp.Struct

// Hessian_done_Results_TypeID is the unique identifier for the type Hessian_done_Results.
const Hessian_done_Results_TypeID = 0x8f8021f874c5751a

func NewHessian_done_Results(s *capnp.Segment) (Hessian_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Hessian_done_Results(st), err
}

func NewRootHessian_done_Results(s *capnp.Segment) (Hessian_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Hessian_done_Results(st), err
}

func ReadRootHessian_done_Results(msg *capnp.Message) (Hessian_done_Results, error) {
	root, err := msg.Root()
	return Hessian_done_Results(root.Struct()), err
}

func (s Hessian_done_Results) String() string {
	str, _ := text.Marshal(0x8f8021f874c5751a, capnp.Struct(s))
	return str
}

func (s Hessian_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Hessian_done_Results) DecodeFromPtr(p capnp.Ptr) Hessian_done_Results {
	return Hessian_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Hessian_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Hessian_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Hessian_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Hessian_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Hessian_done_Results) Hessian() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.Float64List(p.List()), err
}

func (s Hessian_done_Results) HasHessian() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Hessian_done_Results) SetHessian(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHessian sets the hessian field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Hessian_done_Results) NewHessian(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Hessian_done_Results_List is a list of Hessian_done_Results.
type Hessian_done_Results_List = capnp.StructList[Hessian_done_Results]

// NewHessian_done_Results creates a new list of Hessian_done_Results.
func NewHessian_done_Results_List(s *capnp.Segment, sz int32) (Hessian_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Hessian_done_Results](l), err
}

// Hessian_done_Results_Future is a wrapper for a Hessian_done_Results promised by a client call.
type Hessian_done_Results_Future struct{ *capnp.Future }

func (f Hessian_done_Results_Future) Struct() (Hessian_done_Results, error) {
	p, err := f.Future.Ptr()
	return Hessian_done_Results(p.Struct()), err
}
