// Code generated by capnpc-go. DO NOT EDIT.

package cognition

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
)

type Associate capnp.Client

// Associate_TypeID is the unique identifier for the type Associate.
const Associate_TypeID = 0xef4caf89bb206859

func (c Associate) Write(ctx context.Context, params func(Associate_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xef4caf89bb206859,
			MethodID:      0,
			InterfaceName: "nomagique/cognition/associate.capnp:Associate",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Associate_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Associate) Done(ctx context.Context, params func(Associate_done_Params) error) (Associate_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xef4caf89bb206859,
			MethodID:      1,
			InterfaceName: "nomagique/cognition/associate.capnp:Associate",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Associate_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Associate_done_Results_Future{Future: ans.Future()}, release

}

func (c Associate) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Associate) String() string {
	return "Associate(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Associate) AddRef() Associate {
	return Associate(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Associate) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Associate) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Associate) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Associate) DecodeFromPtr(p capnp.Ptr) Associate {
	return Associate(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Associate) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Associate) IsSame(other Associate) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Associate) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Associate) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Associate_Server is a Associate with a local implementation.
type Associate_Server interface {
	Write(context.Context, Associate_write) error

	Done(context.Context, Associate_done) error
}

// Associate_NewServer creates a new Server from an implementation of Associate_Server.
func Associate_NewServer(s Associate_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Associate_Methods(nil, s), s, c)
}

// Associate_ServerToClient creates a new Client from an implementation of Associate_Server.
// The caller is responsible for calling Release on the returned Client.
func Associate_ServerToClient(s Associate_Server) Associate {
	return Associate(capnp.NewClient(Associate_NewServer(s)))
}

// Associate_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Associate_Methods(methods []server.Method, s Associate_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xef4caf89bb206859,
			MethodID:      0,
			InterfaceName: "nomagique/cognition/associate.capnp:Associate",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Associate_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xef4caf89bb206859,
			MethodID:      1,
			InterfaceName: "nomagique/cognition/associate.capnp:Associate",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Associate_done{call})
		},
	})

	return methods
}

// Associate_write holds the state for a server call to Associate.write.
// See server.Call for documentation.
type Associate_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Associate_write) Args() Associate_write_Params {
	return Associate_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Associate_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Associate_done holds the state for a server call to Associate.done.
// See server.Call for documentation.
type Associate_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Associate_done) Args() Associate_done_Params {
	return Associate_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Associate_done) AllocResults() (Associate_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Associate_done_Results(r), err
}

// Associate_List is a list of Associate.
type Associate_List = capnp.CapList[Associate]

// NewAssociate_List creates a new list of Associate.
func NewAssociate_List(s *capnp.Segment, sz int32) (Associate_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Associate](l), err
}

type Associate_write_Params capnp.Struct

// Associate_write_Params_TypeID is the unique identifier for the type Associate_write_Params.
const Associate_write_Params_TypeID = 0xe6df400e371fb606

func NewAssociate_write_Params(s *capnp.Segment) (Associate_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Associate_write_Params(st), err
}

func NewRootAssociate_write_Params(s *capnp.Segment) (Associate_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Associate_write_Params(st), err
}

func ReadRootAssociate_write_Params(msg *capnp.Message) (Associate_write_Params, error) {
	root, err := msg.Root()
	return Associate_write_Params(root.Struct()), err
}

func (s Associate_write_Params) String() string {
	str, _ := text.Marshal(0xe6df400e371fb606, capnp.Struct(s))
	return str
}

func (s Associate_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Associate_write_Params) DecodeFromPtr(p capnp.Ptr) Associate_write_Params {
	return Associate_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Associate_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Associate_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Associate_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Associate_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Associate_write_Params) Current() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Associate_write_Params) HasCurrent() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Associate_write_Params) SetCurrent(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Associate_write_Params_List is a list of Associate_write_Params.
type Associate_write_Params_List = capnp.StructList[Associate_write_Params]

// NewAssociate_write_Params creates a new list of Associate_write_Params.
func NewAssociate_write_Params_List(s *capnp.Segment, sz int32) (Associate_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Associate_write_Params](l), err
}

// Associate_write_Params_Future is a wrapper for a Associate_write_Params promised by a client call.
type Associate_write_Params_Future struct{ *capnp.Future }

func (f Associate_write_Params_Future) Struct() (Associate_write_Params, error) {
	p, err := f.Future.Ptr()
	return Associate_write_Params(p.Struct()), err
}

type Associate_done_Params capnp.Struct

// Associate_done_Params_TypeID is the unique identifier for the type Associate_done_Params.
const Associate_done_Params_TypeID = 0x929cb19b38f49630

func NewAssociate_done_Params(s *capnp.Segment) (Associate_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Associate_done_Params(st), err
}

func NewRootAssociate_done_Params(s *capnp.Segment) (Associate_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Associate_done_Params(st), err
}

func ReadRootAssociate_done_Params(msg *capnp.Message) (Associate_done_Params, error) {
	root, err := msg.Root()
	return Associate_done_Params(root.Struct()), err
}

func (s Associate_done_Params) String() string {
	str, _ := text.Marshal(0x929cb19b38f49630, capnp.Struct(s))
	return str
}

func (s Associate_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Associate_done_Params) DecodeFromPtr(p capnp.Ptr) Associate_done_Params {
	return Associate_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Associate_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Associate_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Associate_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Associate_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Associate_done_Params_List is a list of Associate_done_Params.
type Associate_done_Params_List = capnp.StructList[Associate_done_Params]

// NewAssociate_done_Params creates a new list of Associate_done_Params.
func NewAssociate_done_Params_List(s *capnp.Segment, sz int32) (Associate_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Associate_done_Params](l), err
}

// Associate_done_Params_Future is a wrapper for a Associate_done_Params promised by a client call.
type Associate_done_Params_Future struct{ *capnp.Future }

func (f Associate_done_Params_Future) Struct() (Associate_done_Params, error) {
	p, err := f.Future.Ptr()
	return Associate_done_Params(p.Struct()), err
}

type Associate_done_Results capnp.Struct

// Associate_done_Results_TypeID is the unique identifier for the type Associate_done_Results.
const Associate_done_Results_TypeID = 0x98f4f8cc3bb58c9e

func NewAssociate_done_Results(s *capnp.Segment) (Associate_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Associate_done_Results(st), err
}

func NewRootAssociate_done_Results(s *capnp.Segment) (Associate_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Associate_done_Results(st), err
}

func ReadRootAssociate_done_Results(msg *capnp.Message) (Associate_done_Results, error) {
	root, err := msg.Root()
	return Associate_done_Results(root.Struct()), err
}

func (s Associate_done_Results) String() string {
	str, _ := text.Marshal(0x98f4f8cc3bb58c9e, capnp.Struct(s))
	return str
}

func (s Associate_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Associate_done_Results) DecodeFromPtr(p capnp.Ptr) Associate_done_Results {
	return Associate_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Associate_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Associate_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Associate_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Associate_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Associate_done_Results) Precursor() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Associate_done_Results) HasPrecursor() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Associate_done_Results) SetPrecursor(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Associate_done_Results) Current() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Associate_done_Results) HasCurrent() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Associate_done_Results) SetCurrent(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// Associate_done_Results_List is a list of Associate_done_Results.
type Associate_done_Results_List = capnp.StructList[Associate_done_Results]

// NewAssociate_done_Results creates a new list of Associate_done_Results.
func NewAssociate_done_Results_List(s *capnp.Segment, sz int32) (Associate_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Associate_done_Results](l), err
}

// Associate_done_Results_Future is a wrapper for a Associate_done_Results promised by a client call.
type Associate_done_Results_Future struct{ *capnp.Future }

func (f Associate_done_Results_Future) Struct() (Associate_done_Results, error) {
	p, err := f.Future.Ptr()
	return Associate_done_Results(p.Struct()), err
}

const schema_f7955c5d36bd7258 = "x\xda\xc4Ymt\x14\xd5\xf9\xbf\xcf\xcc\x86\x85\xec\x86" +
	"e2\x1b\x16\xf9\xff\xe9J\x1a4I\x09\x92`%@" +
	"!!\xd5\x8a\x14z2\xc1\xf2\xd2jq\xd8\x0c\xc9\x92" +
	"d_ff\x9b\x04\xc1\x10O\xed\x02%\x1c\xa3\x84\x17" +
	"%@\xa5p@\x83\x98S\xa4\xa2H\xd1S8\xa7\xd4" +
	"\xca\xab\xf4\xd0S\x0e\xd4Z\xde,\x86V\xa0j\x81\xe9" +
	"\xb9w\xf6\xce\xce\x92\xd9d\x13?\xf4\xdb\xdc\xbb\xcf\xbd" +
	"\xcf\xcb\xefw\x9f\xe7>w\xc7\xda\x06\x96\xda\x0a3\xec" +
	"C\x11S\x01i\x03\xb4\xf0\x8a\xd5?\xb8\xb4%}\x19" +
	"\xe2\xc6\x00B6;B\xe3.\xa7\x9f\x00d\xfb\xed\xaf" +
	"\xd5\xc5/\x1eHk\xe1\xbc\xac\xd6\xc8}o\xda\xaf\xce" +
	"|\xeb\x0d\x84`\xdc\xd9\xf4l\xe0\xaf\xa6\xdb\x11\xe2/" +
	"\xa7G\xf9\x09\x0e;B]k\x03\xae\xfb\xa5\xd2\x16." +
	"\x87\xd5r\xcf\xfd4\xbd$}\xea[Xv\xa4C\x06" +
	"\xfe\xdbX\x82/tD\xf9f\xfc\xa5U\x8f[Pu" +
	"\xf8G-\xab\x11W@5\xfa\x1dG\x00\xd9\xb4\x0fo" +
	")\xcb\xf9W\xbelE\\\x1e\xabu}\x94{b\xe2" +
	"\xe2\xf0y\xbc\xcf\x93\x8e\xb7\x81\x8f\x90}\xc2\x8e(\xff" +
	"\x9e\xc3\x83\x90\xd6\xbadl\xab\xbcf\xc2\x0b\x88\xcb\xa5" +
	"\xfbt:^\xc1\xfb\x8c]{\xbd\xf8\xe5\xce\x8d/\x98" +
	"|\xfa\xa5\x03\xfb\xa45\x87\x7fs\xe5\xe6\xd5\xedm\x88" +
	"+\xa6\xbf\xb49\xb2\x19d\xd3\xf6\x1f\xfd\xe65\x9b\xbd" +
	"n\x9d\xe9\x97\x16\xfd\x97\x0b\x1f\xff_\xe6\x8d\xd2U\xeb" +
	"\x88U\xd7\xf6\xbc\xf4yh\xf3'k\xb0U\xcf9\xde" +
	"\x07\xbe\x9dX\xb5\xc1\x11\xe5/\xe3\xafs\xb7\xe7\xb5^" +
	"Y\xb4\x7f\x1dWHw9\xee\xb8\x825oZ\xf5\xe6" +
	"\xa4\x0f\xbe\xb8\xbe^\xb7)\x8d\xc1?\x1dr\xfc\x19\x10" +
	"\xf0g\x1c\xf5\x08\xb4\xc2\xd6\xd9\x93v\x1dW6\xc6\x04" +
	"\x00\x0bLp\x12\x81\x99\xce\x12\x04\xda\x1f\x86e\xec~" +
	"v\xa3\xb6I\xf7W\x17\xa8s\xbe\x8a\x05\x96\x12\x81\xad" +
	"y\xa3_\xde3)s3\xe2\xc6S\xe5\xed\xce\xe1\xd8" +
	"\x85k\x9b\x1bN\x16\xdf\xf3\xc7\xcd\x08\x03t\xe8\xf4\xd1" +
	"\xd3\xebm\x97nb\x17\xda\x9c2\xf0;\x9d\xd8\x85m" +
	"\xce(\x7f\x03\x7fi[B\x17\x864}xg+\x12" +
	"r\x81\x8dmtVWt\xd5\xb9\x1b\x81v\xe0\xd4\x07" +
	"'\xf6^;\xfe\xaa\xd9\xd4\x15\x19\xc4\xd4\xf6\x0clI" +
	"\x8b\xdc6\xa48\xfc\xfc.$\x14\x03C%\xde\xcb\xc8" +
	"g\xb0\xb7\x19x\x8b\xe9M\x153~\xf7\xcc\xb1]H" +
	"\xc81t\x84\x07\xaf\xc4[4\x0f\xc6\x02y\x83\xee?" +
	"\x94\xd3\x11}\x1dq#Y\xad\xfcdx\xe1\x05_{" +
	"36y\x84\xab\x0c\xf8\x02\x1769\xcf\x15\xe5\x1b\xf1" +
	"\x97\x96\xb3\xb8\xec\xdc\xde\x95\xe1N\xac\xd0\x08\xaf\xe8\"" +
	"\x0a\x1b]x?O\xe9\xf0\xe6\xaea\x8f\xbd\x83%l" +
	"T\"k\x08\x96\x18W0d\x0e \xd0\xf6d\x1f\x1d" +
	"\x94\xfd\xe8_\x0e\x9b!j\xe6\x88[m\x1c\x86\xe8\xcc" +
	"\xc8\xf5\x15\x7f_;\xf6\x88\xce\\\xdd+.\xf3\x04\x16" +
	"\x18\x95\x89\xfd~ny{\xc7\xc3\xffx\xf0\x18\"\xf0" +
	"\xeb\x02\x8fd\xfe\x0b\x0b\xcc#\x02\xbb\x0b\x1em\xb89" +
	"e\xdbI$\x8c'v\xb2Xbif6\xb6\xb3-" +
	"\xf3\"\x02\xed;mSf?}\xf8\xedS\x04\xaa\xe5" +
	"\xcf\xbc\xbb%RZ\xb5\x0e\xfb\xbd\x94_\x04|+\x8f" +
	"\xfdn\xe1\xa3\xfcY\xfc\xa5\xb1_\xbc\x18iz\xea\xd8" +
	"i\xc4\xe5\x18\x0a\x0f\xf1$\x8c\x1f\xf1X\xe1\xe7\xa1Q" +
	"9;\xce\x7f\xf67$\x8c\x01J\x8a\x1b<\xf1i\x90" +
	"\x1b\x0b\x1c\xdd[wq\xe6\xc2\x87>1\x9d\x95<7" +
	"9+\x03\xf6z\xc7\x0f.=w\xc1\x8c\xf2\x087Y" +
	"ZH\x96\x16:F\xb7\xdf3q\xd9\xc5\x04g\x047" +
	"q\xc6\xef\xc6\xce\xb4\xfdg\xf5\xc8\xff\xbf\xd7}\x09q" +
	"\xf7\xb1Z\xf1\xd6\x93\xe7\xe7|\xa3s=vff\xd6" +
	"J\xe0\xa5,\xec\x8c\x98\x15\xe5;\xf1\x976\xaf\xfa\xde" +
	"wV\xec\x9e\xd1E\\\x9f+\xbf\xfb\xd0\x93O\xb4\xfd" +
	"\x1bKo\xc8\x92\x81\xdfE\xa4wfE\xf9/\x89\xf4" +
	"k?\xfe\xbd\xb7\xa1c\x9f.=mruf\xcdU" +
	"m9\x96\xfe+\x96\xbeA\xa4\xff\x99\x15\xe5\xa7\x0e\xc5" +
	"\xd2\x9d\xf9;\xfftk\xff\xbe\xaeX\x1cto\xf2\x86" +
	"\x12o&\x0f\xc5\xe0V\xa8\xdbg/\xde\xfb\xe9W1" +
	"p\x09\xfa\x1b\x86\x12pw\x11\x81\x83\xee\xa7s\xe7|" +
	"v\xeb+=C\xe8;dx\x08\xc5Fyp<\x9e" +
	"\xaf_}\xfb\xf8\xaa\xce[\x09\xe8{t\xf4\x89\xc0\x94" +
	"\xf5]w\x0a\xaf\x1f\xb8\x85\xb8|V+\xfa\xf8'e" +
	"\xf9\xfb\x7f\xde\x82Mn\xf4\xbc\x0f|\xab\x87`\xeb\x89" +
	"\xf2g\xf1\x976g\xedk\x9f\x8a\x9b\xa6\xdf\xd6\xb1%" +
	"\xc8\x1c\xf2<\x8b\x9192u\xfb\xa9\xd0\xce\xaa;&" +
	"\xcc:=\x04\xb3\xfbF\xbc>/\xabC\xd0\xb0\x9b\xc6" +
	"\xc1\xdb\xe6!n\xee\xf3\xecFg\xb5@\xb0N\xac\xf2" +
	"\x87#\x03\xa4\x07|\xc1\xaa\x80_\xf5\x07\x03\x0f\xd4\x06" +
	"\x835b\xb5$V\x8e\xf1\x89\xa1@h\xe2\x0cc\\" +
	"\x19\x0cH9\xe5\xa2,\xd6\x81b\xace\xcdkC\xa2" +
	"\xaf&\xb6\xac\xdc.\xfaj\xca\x01\x84\x81l\x1aB\xc6" +
	"\x19\x87@\xe7\xc1\xfaq/\xcd\xdf\xc0\x15\x16!\x86\x1b" +
	"e\x070\x9c\x03\xca`\xee\x9e|\xc4p\x19vo\xbd" +
	"\xecW\xa5Rpa\xcd\xa5P\x0e`\xa8\xb5\x99\xd5*" +
	"\x119$\xfb\x15\xb16\xa6{VD\x0ey\xc9D\xdc" +
	"\x00\x9a\xa7\xac\x0c\xa01\x04zBR0 !f\x0b" +
	"D\xc5\x1f\x98_#5\xc6\x0c(\xc3\xe3\xefK\x8d\xa6" +
	"\x90)\x08\x19k\xd3\xcck\xd5`\x8d\x14\x98\xafH\xe1" +
	"\x88\x14\xf0I\xb1\x0d\x1e\xc7\x93\xb3\xa4\x12}2\xee\x05" +
	"=fV^\xd0\x94\x0f4\xb1$\xf1B\xb0\x01h\x07" +
	"'5\x1c\xf9\xc5\xdc\x15\xabQ2\xb3\xea%\x7fU\xb5" +
	"\x1a3g\x8e>\xa0\xde\xd8\xc5:\xc5:\x10\xa2\xa2\x04" +
	"}~Q\xa5~L5\xc6\x96\xe4\xb1\x9b\xd7\xfajE" +
	"E\xf1/\xf4\xfbD<\x8cm\xf0\xdd\xc4IK\x0b\xec" +
	"\x89\x14\x94\x15i\xfe\xdd\x80\x94\xe3\xd9n\xa8$\xf7#" +
	"\x05[P\x1c\x15Z\xe2\xacP\xa1\xb7\x0c\xa0E\xa7\xaf" +
	"\xdcR\xa4\x80\x12\x94\x1bM\xce\xcc\xd2gL\x9e\xb8\xe4" +
	"\xfe\"R!)\x91ZVU\x84\x81\xac\x0d!\x1b " +
	"\xc4\xe5U $\xe4\xb2 <\xc8\x00\x07\xe0\xc69\x92" +
	"+,CH\x18\xcd\x82P\xcc\x80\x16\x92%_DV" +
	"\x82\x08d\xc8@\x0cd h\xf2EdY\x0a\xa8t" +
	"\xdc\xd7\xdcB\x82A\xf8\xc1\xd6)\x82\xcd0&c\"" +
	"B\xc2@\x16\x047\x03%!YZ\xe8o\xe8\xa6\xa2" +
	"W\xde\xd2\xcdI\x98\x92m.K\xbe\xa0\\\xd9ms" +
	"{\xaag56g\xf0\x9c5!\x92\x90\xadDU\x95" +
	"E\x9f\x1a\x94)\"\xaa*{\xc9D\x9cQ\xf4\xfaa" +
	"\xc5(Z\xa5\x81&\xf8\x14\x18\x95\xda\xd1\xae\x90\x14W" +
	"\xa4VU\x04\xa7\x11\xa2G\x8a\x10\x12JY\x10f\x98" +
	"\xc8\xf0X>B\xc2\xc3,\x08\xe5\x0cp\x0c\xe3\xc6\xe5" +
	"\x85\x9b\x89i3\x83\x05a.\x03^_0\x12P!" +
	"\x0d1\x90\x86\xc0U'*\x0a\x1dh\xc4\xc8Y\xaa\x84" +
	" d\xccY\x13\xdf\"\xab\xeb\xe3\xa4dY\x84\x90\xe0" +
	"dA\x18\xc6\x80\xe6\x0b\x06T\xa9A-C\xaeFU" +
	"Rz\xc65\x95\xd4\x93H\"\xeb\x08Y\x07\x08b\x01" +
	"\xc2Gh\x1a\x0b\xc2\xe38@xsj\x94+$\x07" +
	"\x17\x80\x031\xe0@\xd0\xa4DB\xa1\xa0\xacv\x0bN" +
	"Z\xb2J\x8b?\xe3!\xc1\x95\xe6\x7f\x06\xa0\xad\x17\x9e" +
	"\x99\x92&ma\xac(N\xdb9\xa0\xedG\x0a\x14\xef" +
	"_\x15H\x99\xf2\x8b\xe2\xe0A,`\xc2ps\xc0\xcc" +
	"\x80&!\x1f\x1b\xac\x01@\x0c\xc0\xd7\xe1a\xa2\xd9\xc3" +
	"\x0c\xb37\xe0d\xb6\x86\x05a\x8b\xc9\xec\xf6\xe9\x08\x09" +
	"\x1bY\x10v\xc4\xcd\xde\x86\xc1\xdf\xc2\x82\xd0\xc1\x00\xc7" +
	"\x82\x1b\xf7\\\xdcN,\xb8\x83\x05a\x0f\x03\x9c\x8dq" +
	"\xe3\xbe\x88\xeb\xc4\x8c\xed`Ax\x8b\x01.\xed\xa0\x1b" +
	"\xd2\x10\xe2\xde\xc4z\xde`A\xd8\xcf@I\xbd?\x10" +
	"\x90\x8c\"\xa0\xc9\x11<\xfca\x08!d\xc9m\x12\x17" +
	"YTT,\x90\x84\xef%!QQ\xa4\xcan\x81\x1a" +
	"\xd0[\x0e\xd5\xc7\x89\xb9\xc1T\xd5\xb0/9,\x08\xa5" +
	"\xa6\xf0L\xc6\x93\xc5:\xaaM$\xf8\x92\x02\x83\x11\x94" +
	"\xb3@\xec\x1f\x8c\xa0Ig\xb11=H\x9f\xee\xcf=" +
	"\x90\xd4Z\x15\x122Vv\xbc\x02\xd9\x83\x91^\xcag" +
	"\x8fW\x81\x98\xe3^\xf1\xee\"\xd7\xdf\xa4\x98j\xb1\xc3" +
	"n\xd91\x17\x87\x18:E\xcc\xa6\xa7X\x10\x96\x98\x82" +
	"\xdd\x88y\xa7\xb2 ,\x8bsq)>k\x0d,\x08" +
	"?\xc3\\dt.6\xe3\xa0,aAX\xce\x80F" +
	"\xf5c\xc6\xc4 p\xea\x10\xb8B\xa2ZM\x06N\x04" +
	"\xdeJ)\xa4VS\x0eY\x86\xd2\xd6\x1bR.\x0cU" +
	"<A\xd1&\xd0*A\xd1w+\xa0\xcf\x00}\xad\xc1" +
	"w\xe7o\x13Ap\xfe\xee7C\x92\xd6\xcc\xc4\xdb^" +
	"\x0f\xfb\xd3\xa3\xda\xc7sgy\xbfO\xf1&\x9a\xb4\x9e" +
	"\x97\xc5mKz\xc1\xec+g\x0de\xf8\xf6o\xe6," +
	"\xa6\xe2\x13,\x08\xd5&\xceJE1\"\xd7\x9a\x0a\xa5" +
	"\x1fg\xc0\xca\x18\x91Y\x9d\xb3f\"{\x15_0$" +
	"\x19\xcc$6\xd1Q\x09\x19)wQ\xd9+K\x8a\xa4" +
	"vKyi\xa9\x1e~d\xaa\xab\xf4\xdd\xc9\x82\xb6\xf4" +
	"A\xd2\xf4:\xd1\xc7N\xdb\x0aC/\x99\x88\x1b@\xdf" +
	"\x8a\xac\xce\x0d}\x8d\x05\xfa\x04\xdaW\x03\xac:\x08/" +
	"\x9905\xc9\xb1\xd7S+\x03\xe8\x137\xd0G\xa0\xbe" +
	"\xb6c\xbd<\x8fX\xf5S\xd9\xb1\xca36~A," +
	"\xc8\x8f\xf7XvE\x0a\x1b\xd5\xb26XU\xde\xf3\x11" +
	"LZcLW@H\xd0_\x14\xd7o\x10\xbb`Q" +
	"\xbc\x9fK\xe9\xee\xd2\xff{V\xd2\xee\xcb\x9cyj\xa4" +
	"\xc6\xafQ\xfbb\xa1\xf7\x92\xf4\xd9\xef\xe4\x99\x823\xa6" +
	"sF\x9f\x00\xadXF\xff@\x00\xfa\x16\x9d\x02\xcb\x9c" +
	"\xbd\x96\x87\xd8\xed\x9e.\xe8C\xde\xef9/\xf7\x9c\xd3" +
	"\x0dF\xf7\xa7\xe5)J\xa9\xe5I\xec6\xfe\x1b\x00\x00" +
	"\xff\xffF\x8d\xa7Y"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_f7955c5d36bd7258,
		Nodes: []uint64{
			0x800aa0e84e8e8971,
			0x8d0005be937a74b3,
			0x8d406500270f6e96,
			0x8e8d5ac667623368,
			0x91f9a2138873fcce,
			0x9239947291307c91,
			0x929cb19b38f49630,
			0x95a6edf6eab77181,
			0x976d0704f023cfbc,
			0x978c40f5121be2e6,
			0x97bc006aea9159fd,
			0x98f4f8cc3bb58c9e,
			0x9c73d1ad3b569131,
			0x9eff9c82af0d18cb,
			0x9f123bb49b2c29a3,
			0x9fcd1938d3789ff0,
			0xa3fece7f10e670a0,
			0xaad1f0b6d2ccd4be,
			0xad9071381095728d,
			0xadd07ec44c527f4a,
			0xae87ac24c5270929,
			0xb1718ab6df427a24,
			0xbb4918ef811a4017,
			0xc6dc472209cf22b4,
			0xca3096e5529821d9,
			0xd034ec44ac9d8885,
			0xd3a53ef678472daf,
			0xd4bac67b563e953c,
			0xd6d0607f7593f803,
			0xe3eee0a8242570f3,
			0xe436664de76db6cf,
			0xe6df400e371fb606,
			0xe7803a199d2c0b31,
			0xe814201c218efb95,
			0xef4caf89bb206859,
			0xefb9ac781fc95bab,
			0xefb9bcfcd7a92ab1,
			0xfaebb67a56a67452,
			0xfafcee57287b14c0,
			0xfcb18cd1fd8e7790,
			0xfcbef431feef983e,
			0xfd4a9e61ebab9657,
			0xfe67a970d4a641ca,
			0xff51ac1559ae1d26,
		},
		Compressed: true,
	})
}
