// Code generated by capnpc-go. DO NOT EDIT.

package cognition

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	context "context"
)

type Memory capnp.Client

// Memory_TypeID is the unique identifier for the type Memory.
const Memory_TypeID = 0xe6eab94e2089c1ab

func (c Memory) Reinforce(ctx context.Context, params func(Memory_reinforce_Params) error) (Memory_reinforce_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe6eab94e2089c1ab,
			MethodID:      0,
			InterfaceName: "nomagique/cognition/memory.capnp:Memory",
			MethodName:    "reinforce",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Memory_reinforce_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Memory_reinforce_Results_Future{Future: ans.Future()}, release

}

func (c Memory) Basin(ctx context.Context, params func(Memory_basin_Params) error) (Memory_basin_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe6eab94e2089c1ab,
			MethodID:      1,
			InterfaceName: "nomagique/cognition/memory.capnp:Memory",
			MethodName:    "basin",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Memory_basin_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Memory_basin_Results_Future{Future: ans.Future()}, release

}

func (c Memory) Steps(ctx context.Context, params func(Memory_steps_Params) error) (Memory_steps_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe6eab94e2089c1ab,
			MethodID:      2,
			InterfaceName: "nomagique/cognition/memory.capnp:Memory",
			MethodName:    "steps",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Memory_steps_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Memory_steps_Results_Future{Future: ans.Future()}, release

}

func (c Memory) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Memory) String() string {
	return "Memory(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Memory) AddRef() Memory {
	return Memory(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Memory) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Memory) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Memory) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Memory) DecodeFromPtr(p capnp.Ptr) Memory {
	return Memory(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Memory) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Memory) IsSame(other Memory) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Memory) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Memory) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Memory_Server is a Memory with a local implementation.
type Memory_Server interface {
	Reinforce(context.Context, Memory_reinforce) error

	Basin(context.Context, Memory_basin) error

	Steps(context.Context, Memory_steps) error
}

// Memory_NewServer creates a new Server from an implementation of Memory_Server.
func Memory_NewServer(s Memory_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Memory_Methods(nil, s), s, c)
}

// Memory_ServerToClient creates a new Client from an implementation of Memory_Server.
// The caller is responsible for calling Release on the returned Client.
func Memory_ServerToClient(s Memory_Server) Memory {
	return Memory(capnp.NewClient(Memory_NewServer(s)))
}

// Memory_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Memory_Methods(methods []server.Method, s Memory_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe6eab94e2089c1ab,
			MethodID:      0,
			InterfaceName: "nomagique/cognition/memory.capnp:Memory",
			MethodName:    "reinforce",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Reinforce(ctx, Memory_reinforce{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe6eab94e2089c1ab,
			MethodID:      1,
			InterfaceName: "nomagique/cognition/memory.capnp:Memory",
			MethodName:    "basin",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Basin(ctx, Memory_basin{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe6eab94e2089c1ab,
			MethodID:      2,
			InterfaceName: "nomagique/cognition/memory.capnp:Memory",
			MethodName:    "steps",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Steps(ctx, Memory_steps{call})
		},
	})

	return methods
}

// Memory_reinforce holds the state for a server call to Memory.reinforce.
// See server.Call for documentation.
type Memory_reinforce struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Memory_reinforce) Args() Memory_reinforce_Params {
	return Memory_reinforce_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Memory_reinforce) AllocResults() (Memory_reinforce_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Memory_reinforce_Results(r), err
}

// Memory_basin holds the state for a server call to Memory.basin.
// See server.Call for documentation.
type Memory_basin struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Memory_basin) Args() Memory_basin_Params {
	return Memory_basin_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Memory_basin) AllocResults() (Memory_basin_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Memory_basin_Results(r), err
}

// Memory_steps holds the state for a server call to Memory.steps.
// See server.Call for documentation.
type Memory_steps struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Memory_steps) Args() Memory_steps_Params {
	return Memory_steps_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Memory_steps) AllocResults() (Memory_steps_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Memory_steps_Results(r), err
}

// Memory_List is a list of Memory.
type Memory_List = capnp.CapList[Memory]

// NewMemory_List creates a new list of Memory.
func NewMemory_List(s *capnp.Segment, sz int32) (Memory_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Memory](l), err
}

type Memory_reinforce_Params capnp.Struct

// Memory_reinforce_Params_TypeID is the unique identifier for the type Memory_reinforce_Params.
const Memory_reinforce_Params_TypeID = 0x867da4a328ebdaed

func NewMemory_reinforce_Params(s *capnp.Segment) (Memory_reinforce_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Memory_reinforce_Params(st), err
}

func NewRootMemory_reinforce_Params(s *capnp.Segment) (Memory_reinforce_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Memory_reinforce_Params(st), err
}

func ReadRootMemory_reinforce_Params(msg *capnp.Message) (Memory_reinforce_Params, error) {
	root, err := msg.Root()
	return Memory_reinforce_Params(root.Struct()), err
}

func (s Memory_reinforce_Params) String() string {
	str, _ := text.Marshal(0x867da4a328ebdaed, capnp.Struct(s))
	return str
}

func (s Memory_reinforce_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Memory_reinforce_Params) DecodeFromPtr(p capnp.Ptr) Memory_reinforce_Params {
	return Memory_reinforce_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Memory_reinforce_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Memory_reinforce_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Memory_reinforce_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Memory_reinforce_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Memory_reinforce_Params) Key() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Memory_reinforce_Params) HasKey() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Memory_reinforce_Params) SetKey(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Memory_reinforce_Params_List is a list of Memory_reinforce_Params.
type Memory_reinforce_Params_List = capnp.StructList[Memory_reinforce_Params]

// NewMemory_reinforce_Params creates a new list of Memory_reinforce_Params.
func NewMemory_reinforce_Params_List(s *capnp.Segment, sz int32) (Memory_reinforce_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Memory_reinforce_Params](l), err
}

// Memory_reinforce_Params_Future is a wrapper for a Memory_reinforce_Params promised by a client call.
type Memory_reinforce_Params_Future struct{ *capnp.Future }

func (f Memory_reinforce_Params_Future) Struct() (Memory_reinforce_Params, error) {
	p, err := f.Future.Ptr()
	return Memory_reinforce_Params(p.Struct()), err
}

type Memory_reinforce_Results capnp.Struct

// Memory_reinforce_Results_TypeID is the unique identifier for the type Memory_reinforce_Results.
const Memory_reinforce_Results_TypeID = 0x81073536070a8456

func NewMemory_reinforce_Results(s *capnp.Segment) (Memory_reinforce_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Memory_reinforce_Results(st), err
}

func NewRootMemory_reinforce_Results(s *capnp.Segment) (Memory_reinforce_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Memory_reinforce_Results(st), err
}

func ReadRootMemory_reinforce_Results(msg *capnp.Message) (Memory_reinforce_Results, error) {
	root, err := msg.Root()
	return Memory_reinforce_Results(root.Struct()), err
}

func (s Memory_reinforce_Results) String() string {
	str, _ := text.Marshal(0x81073536070a8456, capnp.Struct(s))
	return str
}

func (s Memory_reinforce_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Memory_reinforce_Results) DecodeFromPtr(p capnp.Ptr) Memory_reinforce_Results {
	return Memory_reinforce_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Memory_reinforce_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Memory_reinforce_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Memory_reinforce_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Memory_reinforce_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Memory_reinforce_Results) Weight() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Memory_reinforce_Results) SetWeight(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Memory_reinforce_Results) LastSeen() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s Memory_reinforce_Results) SetLastSeen(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

// Memory_reinforce_Results_List is a list of Memory_reinforce_Results.
type Memory_reinforce_Results_List = capnp.StructList[Memory_reinforce_Results]

// NewMemory_reinforce_Results creates a new list of Memory_reinforce_Results.
func NewMemory_reinforce_Results_List(s *capnp.Segment, sz int32) (Memory_reinforce_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Memory_reinforce_Results](l), err
}

// Memory_reinforce_Results_Future is a wrapper for a Memory_reinforce_Results promised by a client call.
type Memory_reinforce_Results_Future struct{ *capnp.Future }

func (f Memory_reinforce_Results_Future) Struct() (Memory_reinforce_Results, error) {
	p, err := f.Future.Ptr()
	return Memory_reinforce_Results(p.Struct()), err
}

type Memory_basin_Params capnp.Struct

// Memory_basin_Params_TypeID is the unique identifier for the type Memory_basin_Params.
const Memory_basin_Params_TypeID = 0x9fe7de9ac33a176a

func NewMemory_basin_Params(s *capnp.Segment) (Memory_basin_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Memory_basin_Params(st), err
}

func NewRootMemory_basin_Params(s *capnp.Segment) (Memory_basin_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Memory_basin_Params(st), err
}

func ReadRootMemory_basin_Params(msg *capnp.Message) (Memory_basin_Params, error) {
	root, err := msg.Root()
	return Memory_basin_Params(root.Struct()), err
}

func (s Memory_basin_Params) String() string {
	str, _ := text.Marshal(0x9fe7de9ac33a176a, capnp.Struct(s))
	return str
}

func (s Memory_basin_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Memory_basin_Params) DecodeFromPtr(p capnp.Ptr) Memory_basin_Params {
	return Memory_basin_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Memory_basin_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Memory_basin_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Memory_basin_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Memory_basin_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Memory_basin_Params) Prefix() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Memory_basin_Params) HasPrefix() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Memory_basin_Params) SetPrefix(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Memory_basin_Params_List is a list of Memory_basin_Params.
type Memory_basin_Params_List = capnp.StructList[Memory_basin_Params]

// NewMemory_basin_Params creates a new list of Memory_basin_Params.
func NewMemory_basin_Params_List(s *capnp.Segment, sz int32) (Memory_basin_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Memory_basin_Params](l), err
}

// Memory_basin_Params_Future is a wrapper for a Memory_basin_Params promised by a client call.
type Memory_basin_Params_Future struct{ *capnp.Future }

func (f Memory_basin_Params_Future) Struct() (Memory_basin_Params, error) {
	p, err := f.Future.Ptr()
	return Memory_basin_Params(p.Struct()), err
}

type Memory_basin_Results capnp.Struct

// Memory_basin_Results_TypeID is the unique identifier for the type Memory_basin_Results.
const Memory_basin_Results_TypeID = 0xcd84a2add9c748cb

func NewMemory_basin_Results(s *capnp.Segment) (Memory_basin_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Memory_basin_Results(st), err
}

func NewRootMemory_basin_Results(s *capnp.Segment) (Memory_basin_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Memory_basin_Results(st), err
}

func ReadRootMemory_basin_Results(msg *capnp.Message) (Memory_basin_Results, error) {
	root, err := msg.Root()
	return Memory_basin_Results(root.Struct()), err
}

func (s Memory_basin_Results) String() string {
	str, _ := text.Marshal(0xcd84a2add9c748cb, capnp.Struct(s))
	return str
}

func (s Memory_basin_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Memory_basin_Results) DecodeFromPtr(p capnp.Ptr) Memory_basin_Results {
	return Memory_basin_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Memory_basin_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Memory_basin_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Memory_basin_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Memory_basin_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Memory_basin_Results) Classes() (capnp.DataList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.DataList(p.List()), err
}

func (s Memory_basin_Results) HasClasses() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Memory_basin_Results) SetClasses(v capnp.DataList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewClasses sets the classes field to a newly
// allocated capnp.DataList, preferring placement in s's segment.
func (s Memory_basin_Results) NewClasses(n int32) (capnp.DataList, error) {
	l, err := capnp.NewDataList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.DataList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Memory_basin_Results) Weights() (capnp.UInt64List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.UInt64List(p.List()), err
}

func (s Memory_basin_Results) HasWeights() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Memory_basin_Results) SetWeights(v capnp.UInt64List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewWeights sets the weights field to a newly
// allocated capnp.UInt64List, preferring placement in s's segment.
func (s Memory_basin_Results) NewWeights(n int32) (capnp.UInt64List, error) {
	l, err := capnp.NewUInt64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.UInt64List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// Memory_basin_Results_List is a list of Memory_basin_Results.
type Memory_basin_Results_List = capnp.StructList[Memory_basin_Results]

// NewMemory_basin_Results creates a new list of Memory_basin_Results.
func NewMemory_basin_Results_List(s *capnp.Segment, sz int32) (Memory_basin_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Memory_basin_Results](l), err
}

// Memory_basin_Results_Future is a wrapper for a Memory_basin_Results promised by a client call.
type Memory_basin_Results_Future struct{ *capnp.Future }

func (f Memory_basin_Results_Future) Struct() (Memory_basin_Results, error) {
	p, err := f.Future.Ptr()
	return Memory_basin_Results(p.Struct()), err
}

type Memory_steps_Params capnp.Struct

// Memory_steps_Params_TypeID is the unique identifier for the type Memory_steps_Params.
const Memory_steps_Params_TypeID = 0xde8a8437969166de

func NewMemory_steps_Params(s *capnp.Segment) (Memory_steps_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Memory_steps_Params(st), err
}

func NewRootMemory_steps_Params(s *capnp.Segment) (Memory_steps_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Memory_steps_Params(st), err
}

func ReadRootMemory_steps_Params(msg *capnp.Message) (Memory_steps_Params, error) {
	root, err := msg.Root()
	return Memory_steps_Params(root.Struct()), err
}

func (s Memory_steps_Params) String() string {
	str, _ := text.Marshal(0xde8a8437969166de, capnp.Struct(s))
	return str
}

func (s Memory_steps_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Memory_steps_Params) DecodeFromPtr(p capnp.Ptr) Memory_steps_Params {
	return Memory_steps_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Memory_steps_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Memory_steps_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Memory_steps_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Memory_steps_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Memory_steps_Params_List is a list of Memory_steps_Params.
type Memory_steps_Params_List = capnp.StructList[Memory_steps_Params]

// NewMemory_steps_Params creates a new list of Memory_steps_Params.
func NewMemory_steps_Params_List(s *capnp.Segment, sz int32) (Memory_steps_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Memory_steps_Params](l), err
}

// Memory_steps_Params_Future is a wrapper for a Memory_steps_Params promised by a client call.
type Memory_steps_Params_Future struct{ *capnp.Future }

func (f Memory_steps_Params_Future) Struct() (Memory_steps_Params, error) {
	p, err := f.Future.Ptr()
	return Memory_steps_Params(p.Struct()), err
}

type Memory_steps_Results capnp.Struct

// Memory_steps_Results_TypeID is the unique identifier for the type Memory_steps_Results.
const Memory_steps_Results_TypeID = 0xa5fb84a32c7b6134

func NewMemory_steps_Results(s *capnp.Segment) (Memory_steps_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Memory_steps_Results(st), err
}

func NewRootMemory_steps_Results(s *capnp.Segment) (Memory_steps_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Memory_steps_Results(st), err
}

func ReadRootMemory_steps_Results(msg *capnp.Message) (Memory_steps_Results, error) {
	root, err := msg.Root()
	return Memory_steps_Results(root.Struct()), err
}

func (s Memory_steps_Results) String() string {
	str, _ := text.Marshal(0xa5fb84a32c7b6134, capnp.Struct(s))
	return str
}

func (s Memory_steps_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Memory_steps_Results) DecodeFromPtr(p capnp.Ptr) Memory_steps_Results {
	return Memory_steps_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Memory_steps_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Memory_steps_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Memory_steps_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Memory_steps_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Memory_steps_Results) Out() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Memory_steps_Results) SetOut(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// Memory_steps_Results_List is a list of Memory_steps_Results.
type Memory_steps_Results_List = capnp.StructList[Memory_steps_Results]

// NewMemory_steps_Results creates a new list of Memory_steps_Results.
func NewMemory_steps_Results_List(s *capnp.Segment, sz int32) (Memory_steps_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Memory_steps_Results](l), err
}

// Memory_steps_Results_Future is a wrapper for a Memory_steps_Results promised by a client call.
type Memory_steps_Results_Future struct{ *capnp.Future }

func (f Memory_steps_Results_Future) Struct() (Memory_steps_Results, error) {
	p, err := f.Future.Ptr()
	return Memory_steps_Results(p.Struct()), err
}
