// Code generated by capnpc-go. DO NOT EDIT.

package calculus

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type Polarize capnp.Client

// Polarize_TypeID is the unique identifier for the type Polarize.
const Polarize_TypeID = 0xb5dd82e58682af24

func (c Polarize) Write(ctx context.Context, params func(Polarize_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xb5dd82e58682af24,
			MethodID:      0,
			InterfaceName: "nomagique/calculus/polarize.capnp:Polarize",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Polarize_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Polarize) Done(ctx context.Context, params func(Polarize_done_Params) error) (Polarize_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xb5dd82e58682af24,
			MethodID:      1,
			InterfaceName: "nomagique/calculus/polarize.capnp:Polarize",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Polarize_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Polarize_done_Results_Future{Future: ans.Future()}, release

}

func (c Polarize) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Polarize) String() string {
	return "Polarize(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Polarize) AddRef() Polarize {
	return Polarize(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Polarize) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Polarize) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Polarize) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Polarize) DecodeFromPtr(p capnp.Ptr) Polarize {
	return Polarize(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Polarize) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Polarize) IsSame(other Polarize) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Polarize) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Polarize) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Polarize_Server is a Polarize with a local implementation.
type Polarize_Server interface {
	Write(context.Context, Polarize_write) error

	Done(context.Context, Polarize_done) error
}

// Polarize_NewServer creates a new Server from an implementation of Polarize_Server.
func Polarize_NewServer(s Polarize_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Polarize_Methods(nil, s), s, c)
}

// Polarize_ServerToClient creates a new Client from an implementation of Polarize_Server.
// The caller is responsible for calling Release on the returned Client.
func Polarize_ServerToClient(s Polarize_Server) Polarize {
	return Polarize(capnp.NewClient(Polarize_NewServer(s)))
}

// Polarize_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Polarize_Methods(methods []server.Method, s Polarize_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb5dd82e58682af24,
			MethodID:      0,
			InterfaceName: "nomagique/calculus/polarize.capnp:Polarize",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Polarize_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xb5dd82e58682af24,
			MethodID:      1,
			InterfaceName: "nomagique/calculus/polarize.capnp:Polarize",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Polarize_done{call})
		},
	})

	return methods
}

// Polarize_write holds the state for a server call to Polarize.write.
// See server.Call for documentation.
type Polarize_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Polarize_write) Args() Polarize_write_Params {
	return Polarize_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Polarize_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Polarize_done holds the state for a server call to Polarize.done.
// See server.Call for documentation.
type Polarize_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Polarize_done) Args() Polarize_done_Params {
	return Polarize_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Polarize_done) AllocResults() (Polarize_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Polarize_done_Results(r), err
}

// Polarize_List is a list of Polarize.
type Polarize_List = capnp.CapList[Polarize]

// NewPolarize_List creates a new list of Polarize.
func NewPolarize_List(s *capnp.Segment, sz int32) (Polarize_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Polarize](l), err
}

type Polarize_write_Params capnp.Struct

// Polarize_write_Params_TypeID is the unique identifier for the type Polarize_write_Params.
const Polarize_write_Params_TypeID = 0xb7f2b1f4a897436d

func NewPolarize_write_Params(s *capnp.Segment) (Polarize_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Polarize_write_Params(st), err
}

func NewRootPolarize_write_Params(s *capnp.Segment) (Polarize_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Polarize_write_Params(st), err
}

func ReadRootPolarize_write_Params(msg *capnp.Message) (Polarize_write_Params, error) {
	root, err := msg.Root()
	return Polarize_write_Params(root.Struct()), err
}

func (s Polarize_write_Params) String() string {
	str, _ := text.Marshal(0xb7f2b1f4a897436d, capnp.Struct(s))
	return str
}

func (s Polarize_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Polarize_write_Params) DecodeFromPtr(p capnp.Ptr) Polarize_write_Params {
	return Polarize_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Polarize_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Polarize_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Polarize_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Polarize_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Polarize_write_Params) A() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Polarize_write_Params) SetA(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Polarize_write_Params) B() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Polarize_write_Params) SetB(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// Polarize_write_Params_List is a list of Polarize_write_Params.
type Polarize_write_Params_List = capnp.StructList[Polarize_write_Params]

// NewPolarize_write_Params creates a new list of Polarize_write_Params.
func NewPolarize_write_Params_List(s *capnp.Segment, sz int32) (Polarize_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Polarize_write_Params](l), err
}

// Polarize_write_Params_Future is a wrapper for a Polarize_write_Params promised by a client call.
type Polarize_write_Params_Future struct{ *capnp.Future }

func (f Polarize_write_Params_Future) Struct() (Polarize_write_Params, error) {
	p, err := f.Future.Ptr()
	return Polarize_write_Params(p.Struct()), err
}

type Polarize_done_Params capnp.Struct

// Polarize_done_Params_TypeID is the unique identifier for the type Polarize_done_Params.
const Polarize_done_Params_TypeID = 0xe31bbc7dee8e7216

func NewPolarize_done_Params(s *capnp.Segment) (Polarize_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Polarize_done_Params(st), err
}

func NewRootPolarize_done_Params(s *capnp.Segment) (Polarize_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Polarize_done_Params(st), err
}

func ReadRootPolarize_done_Params(msg *capnp.Message) (Polarize_done_Params, error) {
	root, err := msg.Root()
	return Polarize_done_Params(root.Struct()), err
}

func (s Polarize_done_Params) String() string {
	str, _ := text.Marshal(0xe31bbc7dee8e7216, capnp.Struct(s))
	return str
}

func (s Polarize_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Polarize_done_Params) DecodeFromPtr(p capnp.Ptr) Polarize_done_Params {
	return Polarize_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Polarize_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Polarize_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Polarize_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Polarize_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Polarize_done_Params_List is a list of Polarize_done_Params.
type Polarize_done_Params_List = capnp.StructList[Polarize_done_Params]

// NewPolarize_done_Params creates a new list of Polarize_done_Params.
func NewPolarize_done_Params_List(s *capnp.Segment, sz int32) (Polarize_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Polarize_done_Params](l), err
}

// Polarize_done_Params_Future is a wrapper for a Polarize_done_Params promised by a client call.
type Polarize_done_Params_Future struct{ *capnp.Future }

func (f Polarize_done_Params_Future) Struct() (Polarize_done_Params, error) {
	p, err := f.Future.Ptr()
	return Polarize_done_Params(p.Struct()), err
}

type Polarize_done_Results capnp.Struct

// Polarize_done_Results_TypeID is the unique identifier for the type Polarize_done_Results.
const Polarize_done_Results_TypeID = 0xede5e414ca09d669

func NewPolarize_done_Results(s *capnp.Segment) (Polarize_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Polarize_done_Results(st), err
}

func NewRootPolarize_done_Results(s *capnp.Segment) (Polarize_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Polarize_done_Results(st), err
}

func ReadRootPolarize_done_Results(msg *capnp.Message) (Polarize_done_Results, error) {
	root, err := msg.Root()
	return Polarize_done_Results(root.Struct()), err
}

func (s Polarize_done_Results) String() string {
	str, _ := text.Marshal(0xede5e414ca09d669, capnp.Struct(s))
	return str
}

func (s Polarize_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Polarize_done_Results) DecodeFromPtr(p capnp.Ptr) Polarize_done_Results {
	return Polarize_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Polarize_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Polarize_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Polarize_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Polarize_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Polarize_done_Results) Out() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Polarize_done_Results) SetOut(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Polarize_done_Results_List is a list of Polarize_done_Results.
type Polarize_done_Results_List = capnp.StructList[Polarize_done_Results]

// NewPolarize_done_Results creates a new list of Polarize_done_Results.
func NewPolarize_done_Results_List(s *capnp.Segment, sz int32) (Polarize_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Polarize_done_Results](l), err
}

// Polarize_done_Results_Future is a wrapper for a Polarize_done_Results promised by a client call.
type Polarize_done_Results_Future struct{ *capnp.Future }

func (f Polarize_done_Results_Future) Struct() (Polarize_done_Results, error) {
	p, err := f.Future.Ptr()
	return Polarize_done_Results(p.Struct()), err
}

const schema_a0ad9f64dd8c7603 = "x\xda\xbcZ{|SE\x16\x9e\xc9M[\xc0\xd6r" +
	"3i\xd3&\xa9\xb5H\x17(/[t\x05\x84-\xe5" +
	"\xd1\x95\x97\xcbE@\xdb\x15\xeb%M\xdbh\x93\xb4I" +
	"\x83\xd0\x15\x7fK)\x1by\xc8\xf2\x90G\xc5j\x8b[" +
	"J\x91jy\xd4\x07\xd2U\xb1,\xd0\xc5\x07*\xc8c" +
	"\xbb\xcaS\xbb(X\x95\xba\x80\xe5\xeeo&\x99dR" +
	"nZ\xd2\xe0\xfe7\xb9s\xe6\x9c3\xdf|s\xe6\xcc" +
	"\x99\xdc\x9d\xddk\x8c29\"+\x01(\x1e*\x85!" +
	"\xa1\xd2\x85\x0b3\xf6\xb6\x1e\x19\xbf\x10\xf0q\x9ct\x7f" +
	"[C\xff\xd6\x06\xb1\x11\x008lm\xef^\x10U\xf5" +
	"\x0e\x03\x00U\xf6v\xa2V\xdc\x92^\xd9]\xa6j\xf8" +
	"&\xce\x09\x84\x04\x08\x01P\x86\x010\xecxo\x1b\x04" +
	"\x10\x9d\xeb\x9d\x0a\xa0\x943'c\xec\x83\x1fW,\x05" +
	"\xfc]\xb4?\x84/\x86@)5\x15\xdb\xb692\xed" +
	"\xcb\xd8\xa1\xad\xae\xa1\xedd\xe8\xfdm\xfb\x1b\x7f;\xe6" +
	"\xc5e@\x18\xea\x11\x88\xe3Oc\x81d\x1e\x0b\xac\xfc" +
	"\xb2H\x93\xd2\xaby\x05\xe0\x07\xd2~\x81\xdf\x8du\xaf" +
	"\xfen]h\xdc]\xf7\xad\x04\xfcp\xda\x93\xc6\xf7Q" +
	"\x00\xa5\xf4r\xf3\xa9\x15\xaf\x86\x98W1\xfe\x8cp\xf9" +
	"3\xfd\x9f\xbb\xa7\xaf\xdb\xb8~\x0d\x10\x06@\x85\xbb+" +
	"\x91\xdf\x81\xcd\xdd\xcb?\x05\xa0\xb4eX\xdb\xc0\xcd\xcf" +
	"\xdb\xd7\x02\xe1.\x8f?\xab\xf8\x12,PN\xfci>" +
	"{{\xcf\x96\xads\xd6\x01\xbe\x1f\xedo\xe0_\xc0\xba" +
	"\xeb\xbe^\xba|~\xdd\xe8\x0d\x80\xbf\x93\x93.i>" +
	"\xdd\x10\xb6\xb2f/\x06\xb5\x96\x1f\x09Q\x03\x8fA}" +
	"\x9bw\xa2\x9e*\x0cjA\xcd\xf3\xa3r\xf9se\x80" +
	"\x1f\xe0\x01\x86\xdf\x8a\xf5(\xc3\xaf~{r\xd0\xa8\x17" +
	"\x00\xdf\x87\x93\x0ed\x1c\xba\xfdE\xeds+\xb1\x9eS" +
	"|&D\x97\x89\x9eV\xde\x89\xd2\x88\x9e]\x9b\xcc{" +
	"\xfb\xbf\x17^\xc9\xccu\x80\x8a\xcc\xb5\x7fbU\xf9\xd2" +
	"\xb7\xab+\x01\x9f@{\xa2TO\x90\x9eE\x07\xfe\xb4" +
	"\xbbX\xbf\x09\xa3@\xbb\xa0\x8a\xa0\xc0\xab\xf0$7\xa5" +
	"\x97?yz\xde\x93\x7f\x03|<'m\xe1\xc6\xbe\xcf" +
	"U\x0cz\x15\xbb\x90\xacJ\x82.\xc3h\xb4\xca\x89\x9e" +
	"#.\x84\xb7\x1cz\xf7\xa0N\xd8\x0c\x84~\x1eu\x0e" +
	"\xd5&\xacn1Q\xa7K^\xb8\xbc\xb1\xea\xd8\x16 " +
	"\x0c\xf4\x08T\xa9\xf6b\x81z\"\xd0\xf2\xc9\xc8\x93\xa2" +
	"c~\x0d+p\xc4%p\x8e\x08LL~\xa8j\x91" +
	"aW\x0d\xe0\x138\xa9n@\xfa3\xf7\x0dn:\x86" +
	"\x1d\x0aA\x93 \x8aE\xd8\xa1(\xe4DF\xdc\x92\xea" +
	"goV>\xfa\x9f'\xb6\x11z\x1f]Sw\xf4\xce" +
	"\xeb[\xde\xc2\xd2SQ/\x88f\x13\xe9\x0c\xe4D5" +
	"D\xda\xf1\xee\xf7\xb5\x17\xdfxi\x1b\xe0\x07pRH" +
	"\xd9\xb5\xdf\xbc9\xeb\xad\xddXz\x15\xda\x0b]2\xa8" +
	"\x0a9\xd1e\"}\xb8\xfa\xc9~R^\xc9\x0e\x96 " +
	"\xcd\x88\x10\xa4\x05aW\x0b\xe2?\xd8\xf7\xed\xa5E\xf5" +
	"\x80O\xa4\xfd=\xd5K1\xec}_/\xf9\xcb\xb9\x92" +
	"\xe6z\xb2\xb0\xdc\xdc\xe5\xcd\xd9/\xd7V`CWP" +
	"&D\x11jl\xa8\xa7\xda\x892pK\xbag\xc4\xe8" +
	"\x0d\xbf\x1b\xf9\xf8\x1b\x0cA\xd2\xd4\x84 \xe6q\xeb\xb7" +
	"\xfc\xb4\xfd\x8771Z\x94\xc4\xc9j\x82V\x9a\x1a\x93" +
	"\xf8\x93\xd2\xcf\xd6]o\x8c\xdc\x03\x84\xe1\x1e\x81ru" +
	"\x92\x02\xe3M\x04.\x1d\xbe\xb0q\xa39m\x0f;\x09" +
	">\x8aL\".\x0aOB\xf3\xe3\xe4\xc2V\xa1|\x0f" +
	"\xbboGG\x91};\x91\x08\x94.\xdaw\xec\x89\xca" +
	"\x96w\xd9}k\x8a\"\xfbv\x01\x11\xd8p\xbfR\xdf" +
	"X\xff\xce^v\xa7\x95G\x11\x8e\xd5Fa\x1fZ\x14" +
	"\x1b\x8fN\xbe\x92\xd5H\x96\xf4\x0f\x99I\xc2\x86\xa4Q" +
	"\xb5\x18\x8d\x9e\xd1\x93 \x8a\x8b\xc6h\xc4F;\x91\x09" +
	"\xb7\xa4\xc9\x0dh\xc1*X\xb2\x1f\xf0wp\xd2\x82\x97" +
	"N\xec\xcbx\xa0\xe4<\x96\x16\xa2\xb5\x10\x89Dzv" +
	"\xb4\x13\xd5\x12\xe9\x04\xb4L?\xf4\x99\xb7\x0e\x00~ " +
	"'\x1dV<Rp\xf5\x95\xc2\x8b$\xbeE\x9f\x86h" +
	";\x91\xae\x8dv\xa2v\"\xfdj\xf5\x85\xf4\xfa\xb5\xef" +
	"\x1cd\xd18\x17M\xd0h\x8d\xc6s\x89i3\xa4\x0b" +
	"\xf5\x83\x9aX\x82\xf3\x1aB\xf0\x04\x0d\x16\xb0o\xad\x10" +
	"\x9a\x1e.9\xc4\xc2\x95\xa6!pM%\x02\x9fj\xf3" +
	"\xb6|\x91\x91\xf4!C\x0a\xb3\x86\x90b\x8av\xf6\xf8" +
	"\x9a\xab?\x7f\x06\x84D\xcf\xd0\xd9\x9a\xd5x\xa8\x99\x0c" +
	"Mh\xbaf<\xb5\xbf\xfd32\xf3\x0d''\xb7\xef" +
	"|vI\x0b\x9e\xcbs\x1a-D\xe5\x1a<\x972\x8d" +
	"\x13\xb5\xe0\x96Ty|5\xb7cp\xf1\xe7\xec\\\x0e" +
	"k\xc8\\\x9a\x89\xba\xac\xf05y\x1f=\xfa\xc7#@" +
	"\x18\x059\xb7@\xbbf\x12\xe6Fl\xcc\xeb\x00J\x8b" +
	"\xef\x99Y\xb3\xec\xe9\xabG\x99\x00\xb7=\x86\x04\xb8W" +
	"\xce\xf7_\xdf\xf8\xfc\x91c\x80\x1fE{*c\xc6\xe2" +
	"\x80{\xe0\x8a\xea\xf1\x8f+\x92\x8f3A\xa8,\x86\x04" +
	"\xa1o\xf3\xaf\xfe\xe3\xb1\xf0\xcc\x13$\x924\x94\x0a\xcf" +
	"~>dV)\xf6~qL\x12Dkc\xb0\xf7\xab" +
	"b\x9c\xe8\x14nI\x8f\x16\xfe\xbd*e\x9c\xf9\x04\x06" +
	"\x83:w0\x86\x80q\x9c8'\xae\x1e\xfaMYu" +
	"\xe9\x97\x04\x8cC\x1b\x9f\xbe~\xf1\xf0\xe7\x9f`u\x85" +
	"\xb1Z\x88\x16\xc6bu\x0bb\x9d\xe8C\xdc\x92\xd2'" +
	"-\xffy\xe0\xa4Y_\x01\xbe/'i.\x9fT\x1c" +
	"\xfb\xa5\x89P\xac>\xb6\x18\xa2\x83Dz_\xac\x13E" +
	"i\xb1\xf4\xb5q\\\xdf\xff\xa6\x1aO\xb1+\xd1\x1eK" +
	"\x8cGhS\x01\xbc\xb4\xe4|fau\xddi\x06\xd9" +
	"\xc1Z\x82\xec\x08\xdc-\xa5\x14E\x96/~ \xe6\x0c" +
	"\xcb\x92\x0c-a\x89\x89\x08D\xdbV\\\\\xb0Gw" +
	"\x869\xca\x96h\xc9Q6\xe8\xb5\xdc\x1f\x1b\x1f[q" +
	"\x9e\x1d:\xdf5t\x09\x19zb\xc8\xe6\x97?zx" +
	"\xdby\xd6\xb7\x1a-\xf1\xedm\"\x10\xdeP\xc1Ef" +
	"m\xfe\x1a/\xab\xe7\x8c\xd6\x92e\xbdL\x04\x0e\x0f\xbf" +
	"\xef\x8b\xc13\x93Z\x08r\xa5g\xcf\xf0\xef\xcd\x9d\xfc" +
	"\x15\xc6\"J\xa7\x85(Q\x87\xb1H\xd09Q!n" +
	"I\xc7\xce|\xb5s\xd7\x9a\x83\x17\x98\xb3#CG\xce" +
	"\x0e\xd3\xd1\x9eM\xea\xb3\xe7\xbecC\xf5\x04\x1d\x09>" +
	"3u\xd8\xd0\x94\xd5\x09\x07r\x93w^d]u\xe8" +
	"\x88\xab\x8b\x89\xc0\xf4\xec;*\x1e\xd9\xdf\xd6\xca\x0aT" +
	"\xb9\x04\xea\x89@\xe8\x07/e\xadW\x94\xfe\xc0r\xf8" +
	"\x88\x8e }\x8a\x08\xecI\x8dI\xff}N\xee\x8f\xcc" +
	"n\x82z\xb2\x9b\x12\xd6\xbc\x96g\xe8\xb7\xe32\xa1\xdb" +
	"\xc4\xd7v^N\xa9.\xac\xc4\xb3l\xd5%A\x04\xf5" +
	"x\x96\xed:'\x9a\x8a[R\xc4\xa7\x13z\x15\xec\x9a" +
	"\xdc\xc6\x1a\xbaWO\x0c\xa5\xe9\xb1\xa1\xb4\x19\x7f^x" +
	"F\xfb\xd7+8\x90R\x01QO\x02\xe9|\"p\xb6" +
	"\xf5R\xdc\x09\xe3\xb3\xbf\xb0'i\x99\x9eD\xb9\x1a\"" +
	"\xf0\xdd\xf6\x11[g\x0e\x9f\xd5N\x92\x8219\xffV" +
	"\xfe\xab\xe2\xa7:\xec\xd0A\xfdH\x88\x8e\x13\x87\x8e\xe8" +
	"\x9d(1\x0e;T\xf5\xfe\xf7\xfa\x08\xf5\xba\xeb\x80\x1f" +
	"J\xb5E\xc4\x9d\x80@\x02\x1a\xc9b5\x8b\xb9\xa6B" +
	"\x07g\x1cj\x10\xf3\x0d\x8e|\x87}h\xbe5w\x88" +
	"A,\xb0\x14\x8c\x9cb\xcd\x05`\x1a\x84B\x0f.\x04" +
	"\x00O\xfc\x86\x96\xed\xef=5\xec\x85\xac2>9\x05" +
	"(\xf8\xc40\x08=k\x0bi^\xc7\xc7&\x01\x05\x1f" +
	"\x11\x16\xff\x94\xcdTd\x1c\x03#\xb3\xad\x16\xe3\x188" +
	"\x0dB\x8fQ\xa5?\xa3C\xb0l\xdf\xe9\xc6x\xbb#" +
	"\xbf\xc8.(9%\x00J\x08\x00\x1f\xd1\x07\x00\xa1\x07" +
	"\x07\x05\xb5\x02\x86Y\x1dE\xf06\xa0\x80\xb7\x01y\x95" +
	"E\xa2%\xcf\xads\x06n\x12\xa5\xa9\xd3D\x9bh\xb6" +
	"\xcb\x0e0\xce+p\xcbO\x98W0\x84\xf8\xddwZ" +
	"<\x91g}H\xf1\xfa\x10?W\xccw\x18o\xf0\"" +
	"\x94Qj3\x1aL\x056\xabA\xccw\xeb\x9e\xee\xfd" +
	"\xe06!\xda\xc2\x026\x11\xc2\x98\x10\xe7\xd8\xad\xf9\x8e" +
	"\"\xa3\xdb@\x1a\xfd);\xe10\x1f\xdf\xf2\xc5\"\xd3" +
	"\\c\x96!O\xb4\xe4\x1a=\x0e\xba\xbe\x8es}$" +
	"Z\xdc>\xca\xc2f7\xe5Z\xdcC\x1f\xc2MY\xb3" +
	"\xac\xbff\x93\xc5dv\x98\xddc\xa6\xba\x7f\xf9\xe2\xdd" +
	"\xc3\x03\xc6\x00\x15\x00B_\x0e\x0aw+ \x0f\xa1\x1a" +
	"o\x09~0\xfe\xd8\x9f\x83\xc2=\x0a\x08E\x8a\x0e\x9c" +
	"\xd3)N\xf6B[\x11u\x147\xdd,#$\x03\x81" +
	"\xb0\xccW\xa9C\xb4\x19=j\xc9\x0f\x0a\x99\xc81\x08" +
	"\xb0[\xccb\xcc\x15=\xeb\x95\xfa \xf9\xe5\xddg4" +
	"\xf5\x95\xdbg\xf4 \x85\xf4`\xb8\x89}\xd65\xf6n" +
	"\x87#\xfdn\x0dY\x8aq\xac\xd34\x1d\x97s\x9a^" +
	"\xb7 M\xc9\x03\x0c\x0e\xb2\x0bw\xf3;Yvv>" +
	"\xa0\x88\xf3XP\xdc\xbf\xba\x1d\x84\xd8\x95\x9ecuX" +
	"\xb2\xdd\x8a\xc7F\xe2\x1f^\xc8hb\"\x07\x19=\x8d" +
	" =\xf9\x02\\g\x1f\x86\xb9\x08\x16L\xb8\x09\xbd\x89" +
	"p\xe3Q/\x9a}\xb7\xd3\xadQ\xdf\xed\xdd\xaa\xec\x8a" +
	"\xfe\xec\x19G\xef\xf2rkBo\xd7\x90\x1e\xd07\xb1" +
	"&\x9c?V\xb2FiAC\xce(\xbdpCz\x1d" +
	"\xb8\x09\xa3\xa1\x01\xc6x\xc6\x15z\xcb\x93s\x85\xd6F" +
	" \xcd`\x02\xe4\xa4\xd1\x96c\xa0\x00\xe0f\x10\x84a" +
	"\xd5\xe6\xe4[\xad6\xb7\xdet\xd2\xf6\xc4_\xb3\x1d\x00" +
	"Y\x1e\x14X\xf3E\x9b\xa9\x98\xc21\x8d\xfc\xe4\x8a\x99" +
	"xF\xef\xc3r@\xd0\x9c\x1b\xd2\xbc5\xd0 \xec?" +
	"\xdet\x0cS\xa1]9]\xdcq\xe3\xdd\xaa\x933\xe0" +
	"D\x81\xba\x11\xd9\xf1\x00O\x91s#\xc9\xeb\x86\xef\x1a" +
	"G\x16\xd8\x8cs;]\xf0\x8e\x89]\x10<\xf2\x9f\x82" +
	"\xfe\x1f\xd2?OD\x0b\x0b\xf0\x80\xe9\x9aK\xbfN2" +
	"\xa5\xec\xca.\x1b\xd4h\xadFn\x03\xd12\x14\xa4E" +
	"\xc3\x00#\xa9O\xca\xc9\xe5Z\xbcVi\xd9E\xce*" +
	"\xad\xe0BzE\x0b0\x94\xda\x8d\x06\xab%;+\xdb" +
	"\x94\x93c\xb4\x19-\x06O\xd6G\xbe\x8fw}\x0e\xb3" +
	"\x18\x98(B\x0b#r\xee\xd0\xca\x07\xa4\xd7\xec\x00\xa3" +
	"H\xc7\xbc\xfb\x16\x85S\xb9\x846\x88\xcc\xa1\x8b\xb4\xac" +
	";\xf9\x95\xcf\xdd\x87\x09\x06iE\x9ek\xde\x0d\xc1\xbf" +
	"\xf31\x0ct0\xc0\xf9q\xfe\x02\x13g\xc9\xf3\xf2\x80" +
	"\xd6F\xe5x@\x1f:\xe0\x92\xf3\x99\x85\xa0\xba\xeet" +
	"\xa0<\xe8\x90\x1d\x07\xc1\x83\x1e\x81\xb2\x1d\x7f\xf6\xb1\x07" +
	"\x84p\x8f\xc1\x09\xd8\xe0\x18\x0e\x0aS\x98`3\x11\x7f" +
	"\x1c\xcfAa\x9a\x02\xf2\x0a\x85\x1a*\x00\xe0\xa7\xe2\x8f" +
	"\x0fpP\x98\xd1\xd1\xb5x|\x1a$\xfb\xfcJ\xe9\x94" +
	"\x10r\x89\xaf\xec},\xa2;se\xc9E\x15u\x92" +
	"\xe1\xc8^T8\x7f\xb9K$\xfe\xc1\xa4\xa2\xee\x92\x96" +
	"l*\xea~\x0f\x80\xb4\x86\x17 g|\xae%\xa4\xed" +
	"\xbb\x05\xbaZ\xc4>r\x8b\xd8\xc7\xdf\"\x86\x99M\x16" +
	"o[\x9c\xd7\xe9&\xf2\xa13g+\xf2\x02B\xcb\xd0" +
	"r\x80\xd0\x17+H\xdf\xda\x02\xbcb\xca\x9e\xd3\xa9\xae" +
	"/^\x0f\xe8\xc3\xa2\x9c\x07\xb4\xcc\x06\xe9+F\x80K" +
	"\xe2'\x92\xb9n<\xb0\xdb\x01R\xb6\x0a\x16l\xd1\xc3" +
	"\xef&\x0b6\x9b\xf1\x97\xe2vYS\xf2[\x86\x09\xd6" +
	"#?\xb7\x8b\xee,K\x8fnG\x1c\xba^\xa0\xbbe" +
	"\x08\x9f\xc0\xc4\xe5\x18\xbc\x94\xa6O\x8fr\x94\xa6/0" +
	"\x90\x16\xcf\x83/\xeav\xe7~sK({c\xc4\xbb" +
	"%\xdb\xebFz\x04\x91K\x84tu\x94\xfcJ \xdc" +
	"\x90-q\xfe\xe2R$\xfe\xe1%\x0f}g\x94#\x0f" +
	"}\x9d\x84\xf4\x09,\xc8\xf4\xb6\xdb\x00t\xaf\xe2=\xdd" +
	"h\x8f\x0c&1\xed\xa4\xd0\x1alM\xd1'\xd6\xa5\xba" +
	"\x82\x9dwM\xe8\xbb\xb2\xdc\x9a\xd0\xff\x99@\xfa6\x18" +
	"p1\xa9\x8b\xdb\xac;\xc9\xfa_\x00\x00\x00\xff\xff\xae" +
	"Y\xad\x8c"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a0ad9f64dd8c7603,
		Nodes: []uint64{
			0x8144d5f1c254ebeb,
			0x871de8bd1299baa3,
			0x8aa0cf4e42596266,
			0x8b735a75ac727aca,
			0x8b9c4036c4c7f63b,
			0x8edd0a321774df90,
			0x9037231d0696ed92,
			0x916d05ab8ee1dd9f,
			0x93979b9652bacb52,
			0x957394a62bf633a8,
			0x9662aae9090ee4dd,
			0x983db0798c8ae7b0,
			0x99e511673c94a970,
			0x9a3c2cdbecfa0c04,
			0xa10cc028c26da2b4,
			0xa1a7b98a9da52528,
			0xa21c7aba7bc88328,
			0xa46b78e26b9d46a2,
			0xa6511bc9bfcce90c,
			0xa8d8a5c48c81311b,
			0xa9797561db3ad0e9,
			0xa9b46383a5533149,
			0xac6aea5c04a65db5,
			0xac9eb6eeadf0bf75,
			0xb28268ff276ba7d1,
			0xb583efecc5c31f70,
			0xb5dd82e58682af24,
			0xb6603a3e983d3934,
			0xb7f2b1f4a897436d,
			0xbc0fc4fe96d384d0,
			0xbc416d9b9bebd1ef,
			0xbc9d51f1714bf317,
			0xbfe9a16ad8c58384,
			0xc2bbb5c41c043b98,
			0xc45ff94bd69b02e9,
			0xc78201917d13bd4b,
			0xc8b87e2f1c8b1321,
			0xc9bb95b546eba7ab,
			0xca2cb5514663f618,
			0xcc8257ca51a0aa73,
			0xcd2a59d7a8681ad2,
			0xd3f7faa9445d1a4c,
			0xd3fdc7e165fbca21,
			0xd47a2db20392d9a1,
			0xd55b5cce68930c5f,
			0xd6fa7c8ba9553485,
			0xd8d594c49728e6a3,
			0xd931a0cf6012f9c8,
			0xda5a0c5ec6fa6cec,
			0xda6d4332a5be715c,
			0xdf84a799e82f9261,
			0xe0564a2bf78c4a46,
			0xe1653ff8240343fb,
			0xe2b0a700715ae689,
			0xe31848859d0f7432,
			0xe31bbc7dee8e7216,
			0xe68e5ec4f367ae2c,
			0xe6ac57ce9fa62eda,
			0xe7a65f0f03a0bd0c,
			0xe92a552dd73738d1,
			0xebc993b4b3e0e3d8,
			0xede5e414ca09d669,
			0xeeb33167c821924c,
			0xf1f6c758a01e6452,
			0xf28402975f9ec306,
			0xf367664746183fbc,
			0xf5b2276368ae9321,
			0xf64bb4700a45d20d,
			0xf98f1ae381805441,
			0xfc8865da1deff1e4,
			0xfd563855aa39b1ed,
			0xfe96140d1cf0c1a5,
		},
		Compressed: true,
	})
}
