// Code generated by capnpc-go. DO NOT EDIT.

package calculus

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type Tanh capnp.Client

// Tanh_TypeID is the unique identifier for the type Tanh.
const Tanh_TypeID = 0xd3fdc7e165fbca21

func (c Tanh) Write(ctx context.Context, params func(Tanh_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd3fdc7e165fbca21,
			MethodID:      0,
			InterfaceName: "nomagique/calculus/tanh.capnp:Tanh",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Tanh_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Tanh) Done(ctx context.Context, params func(Tanh_done_Params) error) (Tanh_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd3fdc7e165fbca21,
			MethodID:      1,
			InterfaceName: "nomagique/calculus/tanh.capnp:Tanh",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Tanh_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Tanh_done_Results_Future{Future: ans.Future()}, release

}

func (c Tanh) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Tanh) String() string {
	return "Tanh(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Tanh) AddRef() Tanh {
	return Tanh(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Tanh) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Tanh) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Tanh) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Tanh) DecodeFromPtr(p capnp.Ptr) Tanh {
	return Tanh(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Tanh) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Tanh) IsSame(other Tanh) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Tanh) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Tanh) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Tanh_Server is a Tanh with a local implementation.
type Tanh_Server interface {
	Write(context.Context, Tanh_write) error

	Done(context.Context, Tanh_done) error
}

// Tanh_NewServer creates a new Server from an implementation of Tanh_Server.
func Tanh_NewServer(s Tanh_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Tanh_Methods(nil, s), s, c)
}

// Tanh_ServerToClient creates a new Client from an implementation of Tanh_Server.
// The caller is responsible for calling Release on the returned Client.
func Tanh_ServerToClient(s Tanh_Server) Tanh {
	return Tanh(capnp.NewClient(Tanh_NewServer(s)))
}

// Tanh_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Tanh_Methods(methods []server.Method, s Tanh_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd3fdc7e165fbca21,
			MethodID:      0,
			InterfaceName: "nomagique/calculus/tanh.capnp:Tanh",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Tanh_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd3fdc7e165fbca21,
			MethodID:      1,
			InterfaceName: "nomagique/calculus/tanh.capnp:Tanh",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Tanh_done{call})
		},
	})

	return methods
}

// Tanh_write holds the state for a server call to Tanh.write.
// See server.Call for documentation.
type Tanh_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Tanh_write) Args() Tanh_write_Params {
	return Tanh_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Tanh_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Tanh_done holds the state for a server call to Tanh.done.
// See server.Call for documentation.
type Tanh_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Tanh_done) Args() Tanh_done_Params {
	return Tanh_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Tanh_done) AllocResults() (Tanh_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Tanh_done_Results(r), err
}

// Tanh_List is a list of Tanh.
type Tanh_List = capnp.CapList[Tanh]

// NewTanh_List creates a new list of Tanh.
func NewTanh_List(s *capnp.Segment, sz int32) (Tanh_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Tanh](l), err
}

type Tanh_write_Params capnp.Struct

// Tanh_write_Params_TypeID is the unique identifier for the type Tanh_write_Params.
const Tanh_write_Params_TypeID = 0xbc416d9b9bebd1ef

func NewTanh_write_Params(s *capnp.Segment) (Tanh_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Tanh_write_Params(st), err
}

func NewRootTanh_write_Params(s *capnp.Segment) (Tanh_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Tanh_write_Params(st), err
}

func ReadRootTanh_write_Params(msg *capnp.Message) (Tanh_write_Params, error) {
	root, err := msg.Root()
	return Tanh_write_Params(root.Struct()), err
}

func (s Tanh_write_Params) String() string {
	str, _ := text.Marshal(0xbc416d9b9bebd1ef, capnp.Struct(s))
	return str
}

func (s Tanh_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Tanh_write_Params) DecodeFromPtr(p capnp.Ptr) Tanh_write_Params {
	return Tanh_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Tanh_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Tanh_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Tanh_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Tanh_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Tanh_write_Params) Value() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Tanh_write_Params) SetValue(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Tanh_write_Params_List is a list of Tanh_write_Params.
type Tanh_write_Params_List = capnp.StructList[Tanh_write_Params]

// NewTanh_write_Params creates a new list of Tanh_write_Params.
func NewTanh_write_Params_List(s *capnp.Segment, sz int32) (Tanh_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Tanh_write_Params](l), err
}

// Tanh_write_Params_Future is a wrapper for a Tanh_write_Params promised by a client call.
type Tanh_write_Params_Future struct{ *capnp.Future }

func (f Tanh_write_Params_Future) Struct() (Tanh_write_Params, error) {
	p, err := f.Future.Ptr()
	return Tanh_write_Params(p.Struct()), err
}

type Tanh_done_Params capnp.Struct

// Tanh_done_Params_TypeID is the unique identifier for the type Tanh_done_Params.
const Tanh_done_Params_TypeID = 0x8aa0cf4e42596266

func NewTanh_done_Params(s *capnp.Segment) (Tanh_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Tanh_done_Params(st), err
}

func NewRootTanh_done_Params(s *capnp.Segment) (Tanh_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Tanh_done_Params(st), err
}

func ReadRootTanh_done_Params(msg *capnp.Message) (Tanh_done_Params, error) {
	root, err := msg.Root()
	return Tanh_done_Params(root.Struct()), err
}

func (s Tanh_done_Params) String() string {
	str, _ := text.Marshal(0x8aa0cf4e42596266, capnp.Struct(s))
	return str
}

func (s Tanh_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Tanh_done_Params) DecodeFromPtr(p capnp.Ptr) Tanh_done_Params {
	return Tanh_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Tanh_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Tanh_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Tanh_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Tanh_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Tanh_done_Params_List is a list of Tanh_done_Params.
type Tanh_done_Params_List = capnp.StructList[Tanh_done_Params]

// NewTanh_done_Params creates a new list of Tanh_done_Params.
func NewTanh_done_Params_List(s *capnp.Segment, sz int32) (Tanh_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Tanh_done_Params](l), err
}

// Tanh_done_Params_Future is a wrapper for a Tanh_done_Params promised by a client call.
type Tanh_done_Params_Future struct{ *capnp.Future }

func (f Tanh_done_Params_Future) Struct() (Tanh_done_Params, error) {
	p, err := f.Future.Ptr()
	return Tanh_done_Params(p.Struct()), err
}

type Tanh_done_Results capnp.Struct

// Tanh_done_Results_TypeID is the unique identifier for the type Tanh_done_Results.
const Tanh_done_Results_TypeID = 0xe2b0a700715ae689

func NewTanh_done_Results(s *capnp.Segment) (Tanh_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Tanh_done_Results(st), err
}

func NewRootTanh_done_Results(s *capnp.Segment) (Tanh_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Tanh_done_Results(st), err
}

func ReadRootTanh_done_Results(msg *capnp.Message) (Tanh_done_Results, error) {
	root, err := msg.Root()
	return Tanh_done_Results(root.Struct()), err
}

func (s Tanh_done_Results) String() string {
	str, _ := text.Marshal(0xe2b0a700715ae689, capnp.Struct(s))
	return str
}

func (s Tanh_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Tanh_done_Results) DecodeFromPtr(p capnp.Ptr) Tanh_done_Results {
	return Tanh_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Tanh_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Tanh_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Tanh_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Tanh_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Tanh_done_Results) Out() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Tanh_done_Results) SetOut(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Tanh_done_Results_List is a list of Tanh_done_Results.
type Tanh_done_Results_List = capnp.StructList[Tanh_done_Results]

// NewTanh_done_Results creates a new list of Tanh_done_Results.
func NewTanh_done_Results_List(s *capnp.Segment, sz int32) (Tanh_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Tanh_done_Results](l), err
}

// Tanh_done_Results_Future is a wrapper for a Tanh_done_Results promised by a client call.
type Tanh_done_Results_Future struct{ *capnp.Future }

func (f Tanh_done_Results_Future) Struct() (Tanh_done_Results, error) {
	p, err := f.Future.Ptr()
	return Tanh_done_Results(p.Struct()), err
}
