// Code generated by capnpc-go. DO NOT EDIT.

package statistic

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type ChiSquare capnp.Client

// ChiSquare_TypeID is the unique identifier for the type ChiSquare.
const ChiSquare_TypeID = 0xe68495071991ef6b

func (c ChiSquare) Write(ctx context.Context, params func(ChiSquare_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe68495071991ef6b,
			MethodID:      0,
			InterfaceName: "nomagique/statistic/chi_square.capnp:ChiSquare",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ChiSquare_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c ChiSquare) Done(ctx context.Context, params func(ChiSquare_done_Params) error) (ChiSquare_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe68495071991ef6b,
			MethodID:      1,
			InterfaceName: "nomagique/statistic/chi_square.capnp:ChiSquare",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ChiSquare_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ChiSquare_done_Results_Future{Future: ans.Future()}, release

}

func (c ChiSquare) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c ChiSquare) String() string {
	return "ChiSquare(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c ChiSquare) AddRef() ChiSquare {
	return ChiSquare(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c ChiSquare) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c ChiSquare) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c ChiSquare) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (ChiSquare) DecodeFromPtr(p capnp.Ptr) ChiSquare {
	return ChiSquare(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c ChiSquare) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c ChiSquare) IsSame(other ChiSquare) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c ChiSquare) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c ChiSquare) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A ChiSquare_Server is a ChiSquare with a local implementation.
type ChiSquare_Server interface {
	Write(context.Context, ChiSquare_write) error

	Done(context.Context, ChiSquare_done) error
}

// ChiSquare_NewServer creates a new Server from an implementation of ChiSquare_Server.
func ChiSquare_NewServer(s ChiSquare_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ChiSquare_Methods(nil, s), s, c)
}

// ChiSquare_ServerToClient creates a new Client from an implementation of ChiSquare_Server.
// The caller is responsible for calling Release on the returned Client.
func ChiSquare_ServerToClient(s ChiSquare_Server) ChiSquare {
	return ChiSquare(capnp.NewClient(ChiSquare_NewServer(s)))
}

// ChiSquare_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ChiSquare_Methods(methods []server.Method, s ChiSquare_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe68495071991ef6b,
			MethodID:      0,
			InterfaceName: "nomagique/statistic/chi_square.capnp:ChiSquare",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, ChiSquare_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe68495071991ef6b,
			MethodID:      1,
			InterfaceName: "nomagique/statistic/chi_square.capnp:ChiSquare",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, ChiSquare_done{call})
		},
	})

	return methods
}

// ChiSquare_write holds the state for a server call to ChiSquare.write.
// See server.Call for documentation.
type ChiSquare_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ChiSquare_write) Args() ChiSquare_write_Params {
	return ChiSquare_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ChiSquare_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// ChiSquare_done holds the state for a server call to ChiSquare.done.
// See server.Call for documentation.
type ChiSquare_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ChiSquare_done) Args() ChiSquare_done_Params {
	return ChiSquare_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ChiSquare_done) AllocResults() (ChiSquare_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ChiSquare_done_Results(r), err
}

// ChiSquare_List is a list of ChiSquare.
type ChiSquare_List = capnp.CapList[ChiSquare]

// NewChiSquare_List creates a new list of ChiSquare.
func NewChiSquare_List(s *capnp.Segment, sz int32) (ChiSquare_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[ChiSquare](l), err
}

type ChiSquare_write_Params capnp.Struct

// ChiSquare_write_Params_TypeID is the unique identifier for the type ChiSquare_write_Params.
const ChiSquare_write_Params_TypeID = 0xe63840db93bee868

func NewChiSquare_write_Params(s *capnp.Segment) (ChiSquare_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ChiSquare_write_Params(st), err
}

func NewRootChiSquare_write_Params(s *capnp.Segment) (ChiSquare_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return ChiSquare_write_Params(st), err
}

func ReadRootChiSquare_write_Params(msg *capnp.Message) (ChiSquare_write_Params, error) {
	root, err := msg.Root()
	return ChiSquare_write_Params(root.Struct()), err
}

func (s ChiSquare_write_Params) String() string {
	str, _ := text.Marshal(0xe63840db93bee868, capnp.Struct(s))
	return str
}

func (s ChiSquare_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ChiSquare_write_Params) DecodeFromPtr(p capnp.Ptr) ChiSquare_write_Params {
	return ChiSquare_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ChiSquare_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ChiSquare_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ChiSquare_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ChiSquare_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ChiSquare_write_Params) Observed() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.Float64List(p.List()), err
}

func (s ChiSquare_write_Params) HasObserved() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ChiSquare_write_Params) SetObserved(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewObserved sets the observed field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s ChiSquare_write_Params) NewObserved(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ChiSquare_write_Params) Expected() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.Float64List(p.List()), err
}

func (s ChiSquare_write_Params) HasExpected() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ChiSquare_write_Params) SetExpected(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewExpected sets the expected field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s ChiSquare_write_Params) NewExpected(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// ChiSquare_write_Params_List is a list of ChiSquare_write_Params.
type ChiSquare_write_Params_List = capnp.StructList[ChiSquare_write_Params]

// NewChiSquare_write_Params creates a new list of ChiSquare_write_Params.
func NewChiSquare_write_Params_List(s *capnp.Segment, sz int32) (ChiSquare_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[ChiSquare_write_Params](l), err
}

// ChiSquare_write_Params_Future is a wrapper for a ChiSquare_write_Params promised by a client call.
type ChiSquare_write_Params_Future struct{ *capnp.Future }

func (f ChiSquare_write_Params_Future) Struct() (ChiSquare_write_Params, error) {
	p, err := f.Future.Ptr()
	return ChiSquare_write_Params(p.Struct()), err
}

type ChiSquare_done_Params capnp.Struct

// ChiSquare_done_Params_TypeID is the unique identifier for the type ChiSquare_done_Params.
const ChiSquare_done_Params_TypeID = 0x85e34ed553e84711

func NewChiSquare_done_Params(s *capnp.Segment) (ChiSquare_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ChiSquare_done_Params(st), err
}

func NewRootChiSquare_done_Params(s *capnp.Segment) (ChiSquare_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ChiSquare_done_Params(st), err
}

func ReadRootChiSquare_done_Params(msg *capnp.Message) (ChiSquare_done_Params, error) {
	root, err := msg.Root()
	return ChiSquare_done_Params(root.Struct()), err
}

func (s ChiSquare_done_Params) String() string {
	str, _ := text.Marshal(0x85e34ed553e84711, capnp.Struct(s))
	return str
}

func (s ChiSquare_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ChiSquare_done_Params) DecodeFromPtr(p capnp.Ptr) ChiSquare_done_Params {
	return ChiSquare_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ChiSquare_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ChiSquare_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ChiSquare_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ChiSquare_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ChiSquare_done_Params_List is a list of ChiSquare_done_Params.
type ChiSquare_done_Params_List = capnp.StructList[ChiSquare_done_Params]

// NewChiSquare_done_Params creates a new list of ChiSquare_done_Params.
func NewChiSquare_done_Params_List(s *capnp.Segment, sz int32) (ChiSquare_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ChiSquare_done_Params](l), err
}

// ChiSquare_done_Params_Future is a wrapper for a ChiSquare_done_Params promised by a client call.
type ChiSquare_done_Params_Future struct{ *capnp.Future }

func (f ChiSquare_done_Params_Future) Struct() (ChiSquare_done_Params, error) {
	p, err := f.Future.Ptr()
	return ChiSquare_done_Params(p.Struct()), err
}

type ChiSquare_done_Results capnp.Struct

// ChiSquare_done_Results_TypeID is the unique identifier for the type ChiSquare_done_Results.
const ChiSquare_done_Results_TypeID = 0xaf6b138979434a5a

func NewChiSquare_done_Results(s *capnp.Segment) (ChiSquare_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ChiSquare_done_Results(st), err
}

func NewRootChiSquare_done_Results(s *capnp.Segment) (ChiSquare_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return ChiSquare_done_Results(st), err
}

func ReadRootChiSquare_done_Results(msg *capnp.Message) (ChiSquare_done_Results, error) {
	root, err := msg.Root()
	return ChiSquare_done_Results(root.Struct()), err
}

func (s ChiSquare_done_Results) String() string {
	str, _ := text.Marshal(0xaf6b138979434a5a, capnp.Struct(s))
	return str
}

func (s ChiSquare_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ChiSquare_done_Results) DecodeFromPtr(p capnp.Ptr) ChiSquare_done_Results {
	return ChiSquare_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ChiSquare_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ChiSquare_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ChiSquare_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ChiSquare_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ChiSquare_done_Results) ChiSquare() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s ChiSquare_done_Results) SetChiSquare(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// ChiSquare_done_Results_List is a list of ChiSquare_done_Results.
type ChiSquare_done_Results_List = capnp.StructList[ChiSquare_done_Results]

// NewChiSquare_done_Results creates a new list of ChiSquare_done_Results.
func NewChiSquare_done_Results_List(s *capnp.Segment, sz int32) (ChiSquare_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[ChiSquare_done_Results](l), err
}

// ChiSquare_done_Results_Future is a wrapper for a ChiSquare_done_Results promised by a client call.
type ChiSquare_done_Results_Future struct{ *capnp.Future }

func (f ChiSquare_done_Results_Future) Struct() (ChiSquare_done_Results, error) {
	p, err := f.Future.Ptr()
	return ChiSquare_done_Results(p.Struct()), err
}
