// Code generated by capnpc-go. DO NOT EDIT.

package statistic

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type Correlation capnp.Client

// Correlation_TypeID is the unique identifier for the type Correlation.
const Correlation_TypeID = 0xbbe3a3228a8b8346

func (c Correlation) Write(ctx context.Context, params func(Correlation_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xbbe3a3228a8b8346,
			MethodID:      0,
			InterfaceName: "nomagique/statistic/correlation.capnp:Correlation",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Correlation_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Correlation) Done(ctx context.Context, params func(Correlation_done_Params) error) (Correlation_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xbbe3a3228a8b8346,
			MethodID:      1,
			InterfaceName: "nomagique/statistic/correlation.capnp:Correlation",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Correlation_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Correlation_done_Results_Future{Future: ans.Future()}, release

}

func (c Correlation) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Correlation) String() string {
	return "Correlation(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Correlation) AddRef() Correlation {
	return Correlation(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Correlation) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Correlation) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Correlation) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Correlation) DecodeFromPtr(p capnp.Ptr) Correlation {
	return Correlation(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Correlation) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Correlation) IsSame(other Correlation) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Correlation) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Correlation) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Correlation_Server is a Correlation with a local implementation.
type Correlation_Server interface {
	Write(context.Context, Correlation_write) error

	Done(context.Context, Correlation_done) error
}

// Correlation_NewServer creates a new Server from an implementation of Correlation_Server.
func Correlation_NewServer(s Correlation_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Correlation_Methods(nil, s), s, c)
}

// Correlation_ServerToClient creates a new Client from an implementation of Correlation_Server.
// The caller is responsible for calling Release on the returned Client.
func Correlation_ServerToClient(s Correlation_Server) Correlation {
	return Correlation(capnp.NewClient(Correlation_NewServer(s)))
}

// Correlation_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Correlation_Methods(methods []server.Method, s Correlation_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xbbe3a3228a8b8346,
			MethodID:      0,
			InterfaceName: "nomagique/statistic/correlation.capnp:Correlation",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Correlation_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xbbe3a3228a8b8346,
			MethodID:      1,
			InterfaceName: "nomagique/statistic/correlation.capnp:Correlation",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Correlation_done{call})
		},
	})

	return methods
}

// Correlation_write holds the state for a server call to Correlation.write.
// See server.Call for documentation.
type Correlation_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Correlation_write) Args() Correlation_write_Params {
	return Correlation_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Correlation_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Correlation_done holds the state for a server call to Correlation.done.
// See server.Call for documentation.
type Correlation_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Correlation_done) Args() Correlation_done_Params {
	return Correlation_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Correlation_done) AllocResults() (Correlation_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Correlation_done_Results(r), err
}

// Correlation_List is a list of Correlation.
type Correlation_List = capnp.CapList[Correlation]

// NewCorrelation_List creates a new list of Correlation.
func NewCorrelation_List(s *capnp.Segment, sz int32) (Correlation_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Correlation](l), err
}

type Correlation_write_Params capnp.Struct

// Correlation_write_Params_TypeID is the unique identifier for the type Correlation_write_Params.
const Correlation_write_Params_TypeID = 0xdcabb409ec2c6c62

func NewCorrelation_write_Params(s *capnp.Segment) (Correlation_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Correlation_write_Params(st), err
}

func NewRootCorrelation_write_Params(s *capnp.Segment) (Correlation_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return Correlation_write_Params(st), err
}

func ReadRootCorrelation_write_Params(msg *capnp.Message) (Correlation_write_Params, error) {
	root, err := msg.Root()
	return Correlation_write_Params(root.Struct()), err
}

func (s Correlation_write_Params) String() string {
	str, _ := text.Marshal(0xdcabb409ec2c6c62, capnp.Struct(s))
	return str
}

func (s Correlation_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Correlation_write_Params) DecodeFromPtr(p capnp.Ptr) Correlation_write_Params {
	return Correlation_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Correlation_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Correlation_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Correlation_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Correlation_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Correlation_write_Params) X() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Correlation_write_Params) SetX(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Correlation_write_Params) Y() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Correlation_write_Params) SetY(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// Correlation_write_Params_List is a list of Correlation_write_Params.
type Correlation_write_Params_List = capnp.StructList[Correlation_write_Params]

// NewCorrelation_write_Params creates a new list of Correlation_write_Params.
func NewCorrelation_write_Params_List(s *capnp.Segment, sz int32) (Correlation_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[Correlation_write_Params](l), err
}

// Correlation_write_Params_Future is a wrapper for a Correlation_write_Params promised by a client call.
type Correlation_write_Params_Future struct{ *capnp.Future }

func (f Correlation_write_Params_Future) Struct() (Correlation_write_Params, error) {
	p, err := f.Future.Ptr()
	return Correlation_write_Params(p.Struct()), err
}

type Correlation_done_Params capnp.Struct

// Correlation_done_Params_TypeID is the unique identifier for the type Correlation_done_Params.
const Correlation_done_Params_TypeID = 0x843fa093071a0c6d

func NewCorrelation_done_Params(s *capnp.Segment) (Correlation_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Correlation_done_Params(st), err
}

func NewRootCorrelation_done_Params(s *capnp.Segment) (Correlation_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Correlation_done_Params(st), err
}

func ReadRootCorrelation_done_Params(msg *capnp.Message) (Correlation_done_Params, error) {
	root, err := msg.Root()
	return Correlation_done_Params(root.Struct()), err
}

func (s Correlation_done_Params) String() string {
	str, _ := text.Marshal(0x843fa093071a0c6d, capnp.Struct(s))
	return str
}

func (s Correlation_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Correlation_done_Params) DecodeFromPtr(p capnp.Ptr) Correlation_done_Params {
	return Correlation_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Correlation_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Correlation_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Correlation_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Correlation_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Correlation_done_Params_List is a list of Correlation_done_Params.
type Correlation_done_Params_List = capnp.StructList[Correlation_done_Params]

// NewCorrelation_done_Params creates a new list of Correlation_done_Params.
func NewCorrelation_done_Params_List(s *capnp.Segment, sz int32) (Correlation_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Correlation_done_Params](l), err
}

// Correlation_done_Params_Future is a wrapper for a Correlation_done_Params promised by a client call.
type Correlation_done_Params_Future struct{ *capnp.Future }

func (f Correlation_done_Params_Future) Struct() (Correlation_done_Params, error) {
	p, err := f.Future.Ptr()
	return Correlation_done_Params(p.Struct()), err
}

type Correlation_done_Results capnp.Struct

// Correlation_done_Results_TypeID is the unique identifier for the type Correlation_done_Results.
const Correlation_done_Results_TypeID = 0xaecc8e6ce0fe16ab

func NewCorrelation_done_Results(s *capnp.Segment) (Correlation_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Correlation_done_Results(st), err
}

func NewRootCorrelation_done_Results(s *capnp.Segment) (Correlation_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Correlation_done_Results(st), err
}

func ReadRootCorrelation_done_Results(msg *capnp.Message) (Correlation_done_Results, error) {
	root, err := msg.Root()
	return Correlation_done_Results(root.Struct()), err
}

func (s Correlation_done_Results) String() string {
	str, _ := text.Marshal(0xaecc8e6ce0fe16ab, capnp.Struct(s))
	return str
}

func (s Correlation_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Correlation_done_Results) DecodeFromPtr(p capnp.Ptr) Correlation_done_Results {
	return Correlation_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Correlation_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Correlation_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Correlation_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Correlation_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Correlation_done_Results) Correlation() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Correlation_done_Results) SetCorrelation(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Correlation_done_Results_List is a list of Correlation_done_Results.
type Correlation_done_Results_List = capnp.StructList[Correlation_done_Results]

// NewCorrelation_done_Results creates a new list of Correlation_done_Results.
func NewCorrelation_done_Results_List(s *capnp.Segment, sz int32) (Correlation_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Correlation_done_Results](l), err
}

// Correlation_done_Results_Future is a wrapper for a Correlation_done_Results promised by a client call.
type Correlation_done_Results_Future struct{ *capnp.Future }

func (f Correlation_done_Results_Future) Struct() (Correlation_done_Results, error) {
	p, err := f.Future.Ptr()
	return Correlation_done_Results(p.Struct()), err
}
