// Code generated by capnpc-go. DO NOT EDIT.

package graph

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type PageRank capnp.Client

// PageRank_TypeID is the unique identifier for the type PageRank.
const PageRank_TypeID = 0xaef3d09f5623693e

func (c PageRank) Write(ctx context.Context, params func(PageRank_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xaef3d09f5623693e,
			MethodID:      0,
			InterfaceName: "nomagique/graph/page_rank.capnp:PageRank",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(PageRank_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c PageRank) Done(ctx context.Context, params func(PageRank_done_Params) error) (PageRank_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xaef3d09f5623693e,
			MethodID:      1,
			InterfaceName: "nomagique/graph/page_rank.capnp:PageRank",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(PageRank_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return PageRank_done_Results_Future{Future: ans.Future()}, release

}

func (c PageRank) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c PageRank) String() string {
	return "PageRank(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c PageRank) AddRef() PageRank {
	return PageRank(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c PageRank) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c PageRank) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c PageRank) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (PageRank) DecodeFromPtr(p capnp.Ptr) PageRank {
	return PageRank(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c PageRank) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c PageRank) IsSame(other PageRank) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c PageRank) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c PageRank) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A PageRank_Server is a PageRank with a local implementation.
type PageRank_Server interface {
	Write(context.Context, PageRank_write) error

	Done(context.Context, PageRank_done) error
}

// PageRank_NewServer creates a new Server from an implementation of PageRank_Server.
func PageRank_NewServer(s PageRank_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(PageRank_Methods(nil, s), s, c)
}

// PageRank_ServerToClient creates a new Client from an implementation of PageRank_Server.
// The caller is responsible for calling Release on the returned Client.
func PageRank_ServerToClient(s PageRank_Server) PageRank {
	return PageRank(capnp.NewClient(PageRank_NewServer(s)))
}

// PageRank_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func PageRank_Methods(methods []server.Method, s PageRank_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xaef3d09f5623693e,
			MethodID:      0,
			InterfaceName: "nomagique/graph/page_rank.capnp:PageRank",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, PageRank_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xaef3d09f5623693e,
			MethodID:      1,
			InterfaceName: "nomagique/graph/page_rank.capnp:PageRank",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, PageRank_done{call})
		},
	})

	return methods
}

// PageRank_write holds the state for a server call to PageRank.write.
// See server.Call for documentation.
type PageRank_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c PageRank_write) Args() PageRank_write_Params {
	return PageRank_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c PageRank_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// PageRank_done holds the state for a server call to PageRank.done.
// See server.Call for documentation.
type PageRank_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c PageRank_done) Args() PageRank_done_Params {
	return PageRank_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c PageRank_done) AllocResults() (PageRank_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PageRank_done_Results(r), err
}

// PageRank_List is a list of PageRank.
type PageRank_List = capnp.CapList[PageRank]

// NewPageRank_List creates a new list of PageRank.
func NewPageRank_List(s *capnp.Segment, sz int32) (PageRank_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[PageRank](l), err
}

type PageRank_write_Params capnp.Struct

// PageRank_write_Params_TypeID is the unique identifier for the type PageRank_write_Params.
const PageRank_write_Params_TypeID = 0xd1084a837982e605

func NewPageRank_write_Params(s *capnp.Segment) (PageRank_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return PageRank_write_Params(st), err
}

func NewRootPageRank_write_Params(s *capnp.Segment) (PageRank_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2})
	return PageRank_write_Params(st), err
}

func ReadRootPageRank_write_Params(msg *capnp.Message) (PageRank_write_Params, error) {
	root, err := msg.Root()
	return PageRank_write_Params(root.Struct()), err
}

func (s PageRank_write_Params) String() string {
	str, _ := text.Marshal(0xd1084a837982e605, capnp.Struct(s))
	return str
}

func (s PageRank_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PageRank_write_Params) DecodeFromPtr(p capnp.Ptr) PageRank_write_Params {
	return PageRank_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PageRank_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PageRank_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PageRank_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PageRank_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PageRank_write_Params) FromNodes() (capnp.Int64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.Int64List(p.List()), err
}

func (s PageRank_write_Params) HasFromNodes() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PageRank_write_Params) SetFromNodes(v capnp.Int64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewFromNodes sets the fromNodes field to a newly
// allocated capnp.Int64List, preferring placement in s's segment.
func (s PageRank_write_Params) NewFromNodes(n int32) (capnp.Int64List, error) {
	l, err := capnp.NewInt64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Int64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s PageRank_write_Params) ToNodes() (capnp.Int64List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.Int64List(p.List()), err
}

func (s PageRank_write_Params) HasToNodes() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PageRank_write_Params) SetToNodes(v capnp.Int64List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewToNodes sets the toNodes field to a newly
// allocated capnp.Int64List, preferring placement in s's segment.
func (s PageRank_write_Params) NewToNodes(n int32) (capnp.Int64List, error) {
	l, err := capnp.NewInt64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Int64List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s PageRank_write_Params) Damping() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s PageRank_write_Params) SetDamping(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s PageRank_write_Params) Tol() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s PageRank_write_Params) SetTol(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// PageRank_write_Params_List is a list of PageRank_write_Params.
type PageRank_write_Params_List = capnp.StructList[PageRank_write_Params]

// NewPageRank_write_Params creates a new list of PageRank_write_Params.
func NewPageRank_write_Params_List(s *capnp.Segment, sz int32) (PageRank_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 2}, sz)
	return capnp.StructList[PageRank_write_Params](l), err
}

// PageRank_write_Params_Future is a wrapper for a PageRank_write_Params promised by a client call.
type PageRank_write_Params_Future struct{ *capnp.Future }

func (f PageRank_write_Params_Future) Struct() (PageRank_write_Params, error) {
	p, err := f.Future.Ptr()
	return PageRank_write_Params(p.Struct()), err
}

type PageRank_done_Params capnp.Struct

// PageRank_done_Params_TypeID is the unique identifier for the type PageRank_done_Params.
const PageRank_done_Params_TypeID = 0x84b5392322a18866

func NewPageRank_done_Params(s *capnp.Segment) (PageRank_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return PageRank_done_Params(st), err
}

func NewRootPageRank_done_Params(s *capnp.Segment) (PageRank_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return PageRank_done_Params(st), err
}

func ReadRootPageRank_done_Params(msg *capnp.Message) (PageRank_done_Params, error) {
	root, err := msg.Root()
	return PageRank_done_Params(root.Struct()), err
}

func (s PageRank_done_Params) String() string {
	str, _ := text.Marshal(0x84b5392322a18866, capnp.Struct(s))
	return str
}

func (s PageRank_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PageRank_done_Params) DecodeFromPtr(p capnp.Ptr) PageRank_done_Params {
	return PageRank_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PageRank_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PageRank_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PageRank_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PageRank_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// PageRank_done_Params_List is a list of PageRank_done_Params.
type PageRank_done_Params_List = capnp.StructList[PageRank_done_Params]

// NewPageRank_done_Params creates a new list of PageRank_done_Params.
func NewPageRank_done_Params_List(s *capnp.Segment, sz int32) (PageRank_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[PageRank_done_Params](l), err
}

// PageRank_done_Params_Future is a wrapper for a PageRank_done_Params promised by a client call.
type PageRank_done_Params_Future struct{ *capnp.Future }

func (f PageRank_done_Params_Future) Struct() (PageRank_done_Params, error) {
	p, err := f.Future.Ptr()
	return PageRank_done_Params(p.Struct()), err
}

type PageRank_done_Results capnp.Struct

// PageRank_done_Results_TypeID is the unique identifier for the type PageRank_done_Results.
const PageRank_done_Results_TypeID = 0xd3ceb3cee8dd39db

func NewPageRank_done_Results(s *capnp.Segment) (PageRank_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PageRank_done_Results(st), err
}

func NewRootPageRank_done_Results(s *capnp.Segment) (PageRank_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PageRank_done_Results(st), err
}

func ReadRootPageRank_done_Results(msg *capnp.Message) (PageRank_done_Results, error) {
	root, err := msg.Root()
	return PageRank_done_Results(root.Struct()), err
}

func (s PageRank_done_Results) String() string {
	str, _ := text.Marshal(0xd3ceb3cee8dd39db, capnp.Struct(s))
	return str
}

func (s PageRank_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PageRank_done_Results) DecodeFromPtr(p capnp.Ptr) PageRank_done_Results {
	return PageRank_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PageRank_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PageRank_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PageRank_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PageRank_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PageRank_done_Results) Nodes() (capnp.Int64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.Int64List(p.List()), err
}

func (s PageRank_done_Results) HasNodes() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PageRank_done_Results) SetNodes(v capnp.Int64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewNodes sets the nodes field to a newly
// allocated capnp.Int64List, preferring placement in s's segment.
func (s PageRank_done_Results) NewNodes(n int32) (capnp.Int64List, error) {
	l, err := capnp.NewInt64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Int64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s PageRank_done_Results) Ranks() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.Float64List(p.List()), err
}

func (s PageRank_done_Results) HasRanks() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PageRank_done_Results) SetRanks(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewRanks sets the ranks field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s PageRank_done_Results) NewRanks(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// PageRank_done_Results_List is a list of PageRank_done_Results.
type PageRank_done_Results_List = capnp.StructList[PageRank_done_Results]

// NewPageRank_done_Results creates a new list of PageRank_done_Results.
func NewPageRank_done_Results_List(s *capnp.Segment, sz int32) (PageRank_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[PageRank_done_Results](l), err
}

// PageRank_done_Results_Future is a wrapper for a PageRank_done_Results promised by a client call.
type PageRank_done_Results_Future struct{ *capnp.Future }

func (f PageRank_done_Results_Future) Struct() (PageRank_done_Results, error) {
	p, err := f.Future.Ptr()
	return PageRank_done_Results(p.Struct()), err
}
