// Code generated by capnpc-go. DO NOT EDIT.

package linalg

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
)

type Transpose capnp.Client

// Transpose_TypeID is the unique identifier for the type Transpose.
const Transpose_TypeID = 0x89e7032b379f2705

func (c Transpose) Write(ctx context.Context, params func(Transpose_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x89e7032b379f2705,
			MethodID:      0,
			InterfaceName: "nomagique/linalg/transpose.capnp:Transpose",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Transpose_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Transpose) Done(ctx context.Context, params func(Transpose_done_Params) error) (Transpose_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x89e7032b379f2705,
			MethodID:      1,
			InterfaceName: "nomagique/linalg/transpose.capnp:Transpose",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Transpose_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Transpose_done_Results_Future{Future: ans.Future()}, release

}

func (c Transpose) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Transpose) String() string {
	return "Transpose(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Transpose) AddRef() Transpose {
	return Transpose(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Transpose) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Transpose) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Transpose) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Transpose) DecodeFromPtr(p capnp.Ptr) Transpose {
	return Transpose(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Transpose) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Transpose) IsSame(other Transpose) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Transpose) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Transpose) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Transpose_Server is a Transpose with a local implementation.
type Transpose_Server interface {
	Write(context.Context, Transpose_write) error

	Done(context.Context, Transpose_done) error
}

// Transpose_NewServer creates a new Server from an implementation of Transpose_Server.
func Transpose_NewServer(s Transpose_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Transpose_Methods(nil, s), s, c)
}

// Transpose_ServerToClient creates a new Client from an implementation of Transpose_Server.
// The caller is responsible for calling Release on the returned Client.
func Transpose_ServerToClient(s Transpose_Server) Transpose {
	return Transpose(capnp.NewClient(Transpose_NewServer(s)))
}

// Transpose_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Transpose_Methods(methods []server.Method, s Transpose_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x89e7032b379f2705,
			MethodID:      0,
			InterfaceName: "nomagique/linalg/transpose.capnp:Transpose",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Transpose_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x89e7032b379f2705,
			MethodID:      1,
			InterfaceName: "nomagique/linalg/transpose.capnp:Transpose",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Transpose_done{call})
		},
	})

	return methods
}

// Transpose_write holds the state for a server call to Transpose.write.
// See server.Call for documentation.
type Transpose_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Transpose_write) Args() Transpose_write_Params {
	return Transpose_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Transpose_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Transpose_done holds the state for a server call to Transpose.done.
// See server.Call for documentation.
type Transpose_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Transpose_done) Args() Transpose_done_Params {
	return Transpose_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Transpose_done) AllocResults() (Transpose_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Transpose_done_Results(r), err
}

// Transpose_List is a list of Transpose.
type Transpose_List = capnp.CapList[Transpose]

// NewTranspose_List creates a new list of Transpose.
func NewTranspose_List(s *capnp.Segment, sz int32) (Transpose_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Transpose](l), err
}

type Transpose_write_Params capnp.Struct

// Transpose_write_Params_TypeID is the unique identifier for the type Transpose_write_Params.
const Transpose_write_Params_TypeID = 0xf75d8b3b0da537a2

func NewTranspose_write_Params(s *capnp.Segment) (Transpose_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Transpose_write_Params(st), err
}

func NewRootTranspose_write_Params(s *capnp.Segment) (Transpose_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Transpose_write_Params(st), err
}

func ReadRootTranspose_write_Params(msg *capnp.Message) (Transpose_write_Params, error) {
	root, err := msg.Root()
	return Transpose_write_Params(root.Struct()), err
}

func (s Transpose_write_Params) String() string {
	str, _ := text.Marshal(0xf75d8b3b0da537a2, capnp.Struct(s))
	return str
}

func (s Transpose_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Transpose_write_Params) DecodeFromPtr(p capnp.Ptr) Transpose_write_Params {
	return Transpose_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Transpose_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Transpose_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Transpose_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Transpose_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Transpose_write_Params) A() (Matrix, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Matrix(p.Struct()), err
}

func (s Transpose_write_Params) HasA() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Transpose_write_Params) SetA(v Matrix) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewA sets the a field to a newly
// allocated Matrix struct, preferring placement in s's segment.
func (s Transpose_write_Params) NewA() (Matrix, error) {
	ss, err := NewMatrix(capnp.Struct(s).Segment())
	if err != nil {
		return Matrix{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Transpose_write_Params_List is a list of Transpose_write_Params.
type Transpose_write_Params_List = capnp.StructList[Transpose_write_Params]

// NewTranspose_write_Params creates a new list of Transpose_write_Params.
func NewTranspose_write_Params_List(s *capnp.Segment, sz int32) (Transpose_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Transpose_write_Params](l), err
}

// Transpose_write_Params_Future is a wrapper for a Transpose_write_Params promised by a client call.
type Transpose_write_Params_Future struct{ *capnp.Future }

func (f Transpose_write_Params_Future) Struct() (Transpose_write_Params, error) {
	p, err := f.Future.Ptr()
	return Transpose_write_Params(p.Struct()), err
}
func (p Transpose_write_Params_Future) A() Matrix_Future {
	return Matrix_Future{Future: p.Future.Field(0, nil)}
}

type Transpose_done_Params capnp.Struct

// Transpose_done_Params_TypeID is the unique identifier for the type Transpose_done_Params.
const Transpose_done_Params_TypeID = 0xfacef9de5669cea5

func NewTranspose_done_Params(s *capnp.Segment) (Transpose_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Transpose_done_Params(st), err
}

func NewRootTranspose_done_Params(s *capnp.Segment) (Transpose_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Transpose_done_Params(st), err
}

func ReadRootTranspose_done_Params(msg *capnp.Message) (Transpose_done_Params, error) {
	root, err := msg.Root()
	return Transpose_done_Params(root.Struct()), err
}

func (s Transpose_done_Params) String() string {
	str, _ := text.Marshal(0xfacef9de5669cea5, capnp.Struct(s))
	return str
}

func (s Transpose_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Transpose_done_Params) DecodeFromPtr(p capnp.Ptr) Transpose_done_Params {
	return Transpose_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Transpose_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Transpose_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Transpose_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Transpose_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Transpose_done_Params_List is a list of Transpose_done_Params.
type Transpose_done_Params_List = capnp.StructList[Transpose_done_Params]

// NewTranspose_done_Params creates a new list of Transpose_done_Params.
func NewTranspose_done_Params_List(s *capnp.Segment, sz int32) (Transpose_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Transpose_done_Params](l), err
}

// Transpose_done_Params_Future is a wrapper for a Transpose_done_Params promised by a client call.
type Transpose_done_Params_Future struct{ *capnp.Future }

func (f Transpose_done_Params_Future) Struct() (Transpose_done_Params, error) {
	p, err := f.Future.Ptr()
	return Transpose_done_Params(p.Struct()), err
}

type Transpose_done_Results capnp.Struct

// Transpose_done_Results_TypeID is the unique identifier for the type Transpose_done_Results.
const Transpose_done_Results_TypeID = 0xdcd7dc0cbef9a390

func NewTranspose_done_Results(s *capnp.Segment) (Transpose_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Transpose_done_Results(st), err
}

func NewRootTranspose_done_Results(s *capnp.Segment) (Transpose_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Transpose_done_Results(st), err
}

func ReadRootTranspose_done_Results(msg *capnp.Message) (Transpose_done_Results, error) {
	root, err := msg.Root()
	return Transpose_done_Results(root.Struct()), err
}

func (s Transpose_done_Results) String() string {
	str, _ := text.Marshal(0xdcd7dc0cbef9a390, capnp.Struct(s))
	return str
}

func (s Transpose_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Transpose_done_Results) DecodeFromPtr(p capnp.Ptr) Transpose_done_Results {
	return Transpose_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Transpose_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Transpose_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Transpose_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Transpose_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Transpose_done_Results) C() (Matrix, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Matrix(p.Struct()), err
}

func (s Transpose_done_Results) HasC() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Transpose_done_Results) SetC(v Matrix) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewC sets the c field to a newly
// allocated Matrix struct, preferring placement in s's segment.
func (s Transpose_done_Results) NewC() (Matrix, error) {
	ss, err := NewMatrix(capnp.Struct(s).Segment())
	if err != nil {
		return Matrix{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Transpose_done_Results_List is a list of Transpose_done_Results.
type Transpose_done_Results_List = capnp.StructList[Transpose_done_Results]

// NewTranspose_done_Results creates a new list of Transpose_done_Results.
func NewTranspose_done_Results_List(s *capnp.Segment, sz int32) (Transpose_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Transpose_done_Results](l), err
}

// Transpose_done_Results_Future is a wrapper for a Transpose_done_Results promised by a client call.
type Transpose_done_Results_Future struct{ *capnp.Future }

func (f Transpose_done_Results_Future) Struct() (Transpose_done_Results, error) {
	p, err := f.Future.Ptr()
	return Transpose_done_Results(p.Struct()), err
}
func (p Transpose_done_Results_Future) C() Matrix_Future {
	return Matrix_Future{Future: p.Future.Field(0, nil)}
}
