package types

/*
Catalog is the authoritative opportunity taxonomy. Order matters only for
deterministic ties; scoring consults every archetype, not just the first match.
*/
var Catalog = []OpportunityArchetype{
	{
		Type: OpportunitySuddenPump,
		Precursors: []CategoryType{
			VerticalIgnition,
			RiskOnSurge,
		},
		Supports: []ObservationCondition{
			{
				Source:          SourcePumpDump,
				Metric:          string(MetricRVOL),
				Name:            "rvol surge",
				State:           "rvol above its own recent median while lift stays positive",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
			{
				Source:          SourceHawkes,
				Metric:          string(MetricSpectralRadius),
				Name:            "near-critical cascade",
				State:           "spectral radius approaching one with positive branching",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
			{
				Source:          SourceDepthFlow,
				Metric:          string(MetricThinScore),
				Name:            "hollow ask book",
				State:           "thin ask depth below the symbol's own touch-depth median",
				Supports:        true,
				MaturityFloor:   0.3,
				SeparationFloor: 0.3,
			},
			{
				Source:          SourceCVD,
				Metric:          string(MetricDrive),
				Name:            "aggressive buy drive",
				State:           "buy aggressor flow dominant and still accelerating",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
		},
		Opposes: []ObservationCondition{
			{
				Source:          SourceToxicity,
				Metric:          string(MetricBluffScore),
				Name:            "spoofed wall",
				State:           "cancelled retreating quantity marks the wall as fake",
				Contradicts:     true,
				MaturityFloor:   0.3,
				SeparationFloor: 0.3,
			},
			{
				Source:          SourceExhaustion,
				Metric:          string(MetricExhaustion),
				Side:            SideSell,
				Name:            "late seller exhaustion",
				State:           "the move is already decelerating into rejection",
				Contradicts:     true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.3,
			},
		},
		RolloutDynamics: "pump",
	},
	{
		Type:       OpportunityCoiledCompression,
		Precursors: []CategoryType{CoiledCompression},
		Supports: []ObservationCondition{
			{
				Source:          SourcePumpDump,
				Metric:          string(MetricCompression),
				Name:            "spread compression",
				State:           "spread tightening below its own baseline",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
			{
				Source:          SourceManifold,
				Metric:          "pressure_gradient",
				Name:            "coiled pressure",
				State:           "pressure gradient accumulating without divergence release",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
			{
				Source:          SourceManifold,
				Metric:          "coherence",
				Name:            "oscillator phase sync",
				State:           "phase coherence rising toward synchronized release",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
		},
		Opposes: []ObservationCondition{
			{
				Source:          SourceDepthFlow,
				Metric:          string(MetricNeutralScore),
				Name:            "dense neutrality",
				State:           "deep two-sided book absorbs without releasing",
				Contradicts:     true,
				MaturityFloor:   0.3,
				SeparationFloor: 0.3,
			},
		},
		RolloutDynamics: "coiled",
	},
	{
		Type:       OpportunityDailyRiser,
		Precursors: []CategoryType{OrganicTrend},
		Supports: []ObservationCondition{
			{
				Source:          SourceResonance,
				Metric:          "generalized_velocity",
				Name:            "latent velocity",
				State:           "positive generalized velocity with low residual",
				Supports:        true,
				MaturityFloor:   0.5,
				SeparationFloor: 0.4,
			},
			{
				Source:          SourceSentiment,
				Metric:          string(MetricBreadth),
				Name:            "positive breadth",
				State:           "cohort breadth supporting the leader",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
			{
				Source:          SourceManifold,
				Metric:          "divergence",
				Name:            "laminar flow",
				State:           "low divergence across the fluid field",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.3,
			},
		},
		Opposes: []ObservationCondition{
			{
				Source:          SourceExhaustion,
				Metric:          string(MetricFragile),
				Name:            "fragile expansion",
				State:           "the trend is built on fragile marginal volume",
				Contradicts:     true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.3,
			},
		},
		RolloutDynamics: "riser",
	},
	{
		Type:       OpportunityInefficientLag,
		Precursors: []CategoryType{InefficientLag},
		Supports: []ObservationCondition{
			{
				Source:          SourceLeadLag,
				Metric:          string(MetricInefficient),
				Name:            "lag correlation",
				State:           "leader path predicts this symbol's next move",
				Supports:        true,
				MaturityFloor:   0.5,
				SeparationFloor: 0.5,
			},
			{
				Source:          SourceCorrelation,
				Metric:          string(MetricAlphaScore),
				Name:            "decoupled alpha",
				State:           "own path carries signal beyond cohort beta",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
		},
		Opposes: []ObservationCondition{
			{
				Source:          SourceLeadLag,
				Metric:          string(MetricStall),
				Name:            "anchor stall",
				State:           "the presumed leader has stopped moving",
				Contradicts:     true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.3,
			},
		},
		RolloutDynamics: "lag",
	},
	{
		Type:       OpportunityAbsorptionReversal,
		Precursors: []CategoryType{HiddenAbsorption},
		Supports: []ObservationCondition{
			{
				Source:          SourceCVD,
				Metric:          string(MetricAbsorption),
				Name:            "massive absorption",
				State:           "passive absorption outlasting the aggressive flow",
				Supports:        true,
				MaturityFloor:   0.4,
				SeparationFloor: 0.4,
			},
			{
				Source:          SourceToxicity,
				Metric:          string(MetricBluffScore),
				Name:            "bluff wall",
				State:           "cancellation marks the pressure as fake",
				Supports:        true,
				MaturityFloor:   0.3,
				SeparationFloor: 0.3,
			},
		},
		Opposes: []ObservationCondition{
			{
				Source:          SourceHawkes,
				Metric:          string(MetricSpectralRadius),
				Name:            "still-critical cascade",
				State:           "the arrival process is still self-exciting upward",
				Contradicts:     true,
				MaturityFloor:   0.3,
				SeparationFloor: 0.3,
			},
		},
		RolloutDynamics: "absorption",
	},
}
