// Code generated by capnpc-go. DO NOT EDIT.

package transport

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
)

type Broadcast capnp.Client

// Broadcast_TypeID is the unique identifier for the type Broadcast.
const Broadcast_TypeID = 0xf5f83d5bc12037d9

func (c Broadcast) Write(ctx context.Context, params func(Broadcast_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xf5f83d5bc12037d9,
			MethodID:      0,
			InterfaceName: "transport/broadcast.capnp:Broadcast",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Broadcast_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Broadcast) Done(ctx context.Context, params func(Broadcast_done_Params) error) (Broadcast_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xf5f83d5bc12037d9,
			MethodID:      1,
			InterfaceName: "transport/broadcast.capnp:Broadcast",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Broadcast_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Broadcast_done_Results_Future{Future: ans.Future()}, release

}

func (c Broadcast) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Broadcast) String() string {
	return "Broadcast(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Broadcast) AddRef() Broadcast {
	return Broadcast(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Broadcast) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Broadcast) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Broadcast) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Broadcast) DecodeFromPtr(p capnp.Ptr) Broadcast {
	return Broadcast(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Broadcast) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Broadcast) IsSame(other Broadcast) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Broadcast) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Broadcast) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Broadcast_Server is a Broadcast with a local implementation.
type Broadcast_Server interface {
	Write(context.Context, Broadcast_write) error

	Done(context.Context, Broadcast_done) error
}

// Broadcast_NewServer creates a new Server from an implementation of Broadcast_Server.
func Broadcast_NewServer(s Broadcast_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Broadcast_Methods(nil, s), s, c)
}

// Broadcast_ServerToClient creates a new Client from an implementation of Broadcast_Server.
// The caller is responsible for calling Release on the returned Client.
func Broadcast_ServerToClient(s Broadcast_Server) Broadcast {
	return Broadcast(capnp.NewClient(Broadcast_NewServer(s)))
}

// Broadcast_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Broadcast_Methods(methods []server.Method, s Broadcast_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf5f83d5bc12037d9,
			MethodID:      0,
			InterfaceName: "transport/broadcast.capnp:Broadcast",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Broadcast_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xf5f83d5bc12037d9,
			MethodID:      1,
			InterfaceName: "transport/broadcast.capnp:Broadcast",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Broadcast_done{call})
		},
	})

	return methods
}

// Broadcast_write holds the state for a server call to Broadcast.write.
// See server.Call for documentation.
type Broadcast_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Broadcast_write) Args() Broadcast_write_Params {
	return Broadcast_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Broadcast_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Broadcast_done holds the state for a server call to Broadcast.done.
// See server.Call for documentation.
type Broadcast_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Broadcast_done) Args() Broadcast_done_Params {
	return Broadcast_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Broadcast_done) AllocResults() (Broadcast_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Broadcast_done_Results(r), err
}

// Broadcast_List is a list of Broadcast.
type Broadcast_List = capnp.CapList[Broadcast]

// NewBroadcast_List creates a new list of Broadcast.
func NewBroadcast_List(s *capnp.Segment, sz int32) (Broadcast_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Broadcast](l), err
}

type Broadcast_write_Params capnp.Struct

// Broadcast_write_Params_TypeID is the unique identifier for the type Broadcast_write_Params.
const Broadcast_write_Params_TypeID = 0xdf155a6ab55bbcc2

func NewBroadcast_write_Params(s *capnp.Segment) (Broadcast_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Broadcast_write_Params(st), err
}

func NewRootBroadcast_write_Params(s *capnp.Segment) (Broadcast_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Broadcast_write_Params(st), err
}

func ReadRootBroadcast_write_Params(msg *capnp.Message) (Broadcast_write_Params, error) {
	root, err := msg.Root()
	return Broadcast_write_Params(root.Struct()), err
}

func (s Broadcast_write_Params) String() string {
	str, _ := text.Marshal(0xdf155a6ab55bbcc2, capnp.Struct(s))
	return str
}

func (s Broadcast_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Broadcast_write_Params) DecodeFromPtr(p capnp.Ptr) Broadcast_write_Params {
	return Broadcast_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Broadcast_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Broadcast_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Broadcast_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Broadcast_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Broadcast_write_Params) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Broadcast_write_Params) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Broadcast_write_Params) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Broadcast_write_Params_List is a list of Broadcast_write_Params.
type Broadcast_write_Params_List = capnp.StructList[Broadcast_write_Params]

// NewBroadcast_write_Params creates a new list of Broadcast_write_Params.
func NewBroadcast_write_Params_List(s *capnp.Segment, sz int32) (Broadcast_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Broadcast_write_Params](l), err
}

// Broadcast_write_Params_Future is a wrapper for a Broadcast_write_Params promised by a client call.
type Broadcast_write_Params_Future struct{ *capnp.Future }

func (f Broadcast_write_Params_Future) Struct() (Broadcast_write_Params, error) {
	p, err := f.Future.Ptr()
	return Broadcast_write_Params(p.Struct()), err
}

type Broadcast_done_Params capnp.Struct

// Broadcast_done_Params_TypeID is the unique identifier for the type Broadcast_done_Params.
const Broadcast_done_Params_TypeID = 0xa031c5c9cb654b9b

func NewBroadcast_done_Params(s *capnp.Segment) (Broadcast_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Broadcast_done_Params(st), err
}

func NewRootBroadcast_done_Params(s *capnp.Segment) (Broadcast_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Broadcast_done_Params(st), err
}

func ReadRootBroadcast_done_Params(msg *capnp.Message) (Broadcast_done_Params, error) {
	root, err := msg.Root()
	return Broadcast_done_Params(root.Struct()), err
}

func (s Broadcast_done_Params) String() string {
	str, _ := text.Marshal(0xa031c5c9cb654b9b, capnp.Struct(s))
	return str
}

func (s Broadcast_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Broadcast_done_Params) DecodeFromPtr(p capnp.Ptr) Broadcast_done_Params {
	return Broadcast_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Broadcast_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Broadcast_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Broadcast_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Broadcast_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Broadcast_done_Params_List is a list of Broadcast_done_Params.
type Broadcast_done_Params_List = capnp.StructList[Broadcast_done_Params]

// NewBroadcast_done_Params creates a new list of Broadcast_done_Params.
func NewBroadcast_done_Params_List(s *capnp.Segment, sz int32) (Broadcast_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Broadcast_done_Params](l), err
}

// Broadcast_done_Params_Future is a wrapper for a Broadcast_done_Params promised by a client call.
type Broadcast_done_Params_Future struct{ *capnp.Future }

func (f Broadcast_done_Params_Future) Struct() (Broadcast_done_Params, error) {
	p, err := f.Future.Ptr()
	return Broadcast_done_Params(p.Struct()), err
}

type Broadcast_done_Results capnp.Struct

// Broadcast_done_Results_TypeID is the unique identifier for the type Broadcast_done_Results.
const Broadcast_done_Results_TypeID = 0xf38121de37cbe206

func NewBroadcast_done_Results(s *capnp.Segment) (Broadcast_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Broadcast_done_Results(st), err
}

func NewRootBroadcast_done_Results(s *capnp.Segment) (Broadcast_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Broadcast_done_Results(st), err
}

func ReadRootBroadcast_done_Results(msg *capnp.Message) (Broadcast_done_Results, error) {
	root, err := msg.Root()
	return Broadcast_done_Results(root.Struct()), err
}

func (s Broadcast_done_Results) String() string {
	str, _ := text.Marshal(0xf38121de37cbe206, capnp.Struct(s))
	return str
}

func (s Broadcast_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Broadcast_done_Results) DecodeFromPtr(p capnp.Ptr) Broadcast_done_Results {
	return Broadcast_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Broadcast_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Broadcast_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Broadcast_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Broadcast_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Broadcast_done_Results) Out() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Broadcast_done_Results) HasOut() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Broadcast_done_Results) SetOut(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// Broadcast_done_Results_List is a list of Broadcast_done_Results.
type Broadcast_done_Results_List = capnp.StructList[Broadcast_done_Results]

// NewBroadcast_done_Results creates a new list of Broadcast_done_Results.
func NewBroadcast_done_Results_List(s *capnp.Segment, sz int32) (Broadcast_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Broadcast_done_Results](l), err
}

// Broadcast_done_Results_Future is a wrapper for a Broadcast_done_Results promised by a client call.
type Broadcast_done_Results_Future struct{ *capnp.Future }

func (f Broadcast_done_Results_Future) Struct() (Broadcast_done_Results, error) {
	p, err := f.Future.Ptr()
	return Broadcast_done_Results(p.Struct()), err
}

const schema_ab2c34cea45a1972 = "x\xda\xa4X\x7fTS\xd7\x1d\xbf\xdf\xf7\x88\x91\xd6$" +
	"<n\x88\xa2\x9d(\xd5\xf5@EDj\x9d:\x8a8" +
	"\x7f\xaf(\x0f\xeb\xd1\x0a\xda> \x0a\x08\x09K\x1eS" +
	"\xd71A\x87\xa9\x9e\xa3N\xc4YE\x9cVt\xb5\xd6" +
	"Y\xba\xe2\xd1YN\x8b\xad\xae\xa8u\xea\xa6\xad\xae\xfe" +
	"\xa0\xed\xd9\xd4SuX9Sk\xf7v\xee}\xb9\xc9" +
	"K|`\x0c\xff\xe5\xbe|\xee\xf7\xf7\xf7\xf3\xbd\xf7\x0e" +
	"K\xed96\"\xc5\x94\xdc\x0fq3~\x0a\x86\x1eJ" +
	"\xc6\x9e\x07#;\x8eTT\"\xa1? d\x00#B" +
	"\xa9\x15\xa69\x80\x00\xaf4\xa5#P\x0a\xc7\x1d:u" +
	"\xbf\xe6\x87J$\xf4\xe5\x95\x1e\x07\xee\xd4\xccK\xfb\xf5" +
	"v\x84 u\xb7)\x1e\xf0A\x93\x11!\xdcd\xf2`" +
	"\x83\xd9\x88\x90r\xf4\x8b1y\xe7\xd2\x9e_\x86\x84\x18" +
	"\xfe\xd6\xbeu\xcb\x9d7~\xf7_\x04\xf8\x86\xe9\x0c\xbe" +
	"G\xa1\x1d&\x0f\x9e@\xa1_'\xbe<T\xd8}r" +
	"\xa5\xaa9\x82(N2g\x03\x8aP\\\x95\x07\xae\xfc" +
	"m\xcd\xf4\xf5H\xe8\xeb\xb3)\xd6<\x9a\xd84\xd0L" +
	"lz-#\xfd\xd9\xff\xd5l\xabE\xc2\x8f\xd9\xd6\x0c" +
	"s\x0d\xd9:\xf3]\xfe\x89\xb6\x9c\xa76 !\x96W" +
	"\xb2o.j[\xf1\xa9\xbd\x85X\x9bb\x8e\x06\x9cA" +
	"\x14\xe34\xb3\x07\xaf\xa6&\x14\xc6\xefZ1\xfa_'" +
	"6\xaa\x8a\xa8\x9cr\xf3p\"'\xf3\x1f\xcd[7\xf6" +
	"\xcf\xa9\xd3\xfc3W\xfdgYB\xd2\xed\x17\xea\x9e\xd9" +
	"B<T\xaa\x7f?ns\xee\xed\xe8o\x11\x02<\xc1" +
	"|\x06\x8bTA\xa6\xd9\x83\xeb\xa9\x82\xf27\xaf\xcf:" +
	"\x93TW\x8f\x84\x01\xc4\x13\x9e\xc8\xa96\x17\x13O\xd6" +
	"\x99\xf7!P\x94\xcd\x93\x8b\x07\x1f\xcd\xfd\x83\xd6\xd5\x04" +
	"\x0bu5\xc5B\\\xad\xfb\xb9\xfdx\xeb\x91\x94mH" +
	"\x18\xc4\x0c\x11-\xcb\x88!w\xa3J\x16\xa7\x0d^\xd6" +
	"\xa0\x06A\xdd\x9af\xd9L\xb6f\xd2\xad\xabF\xdd\x9c" +
	"\x9d][\xdb\x80\x84~\xbc\xb2}BtS\xc7\xf7\xaf" +
	"V\x92X\x94Z\x86\x03\xae\xb0\x10S\x97X<\xb8\x95" +
	"\xfcRF\xeeZ\xd9\xbe\xfc\xd3=\x0dH\xe8\xcd\x7fo" +
	"\\r{O\xfc\xb0\x1a\x04\xb8\xd1r\x1b7S\xe8A" +
	"\x8b\x07GF\x11\xa8\xb9\xd4\xbd\x7f]\xe25Up\x8d" +
	"s\xc9$\xdb\xb4\xb7w\x13\xc1\xedD0\x10\x0c\xfe\xc1" +
	"\xe2\xc1\x99\x14\xfdZ\xe2_\x0a\xd7~\x17\xb9\x8b\x06\xec" +
	"\xc6\xc5\x13m[\xd7mz\x83\x04lD\xd4\x19\x9cA" +
	"\xc1iQ\x1e\xbc\x9a\x82\xc7\x0d\x1d\xec\x9c\xd3;i\x17" +
	"\x12\xfa\xf0\xca\xd6\xb7?~\xf9\xaf\xbf\xac\xb8@D\x97" +
	"Gq\x80\xab(\xba\"\xca\x83?\xa3\xe8M\xd5\x8b\xfb" +
	"\xfd\xf6\xc1\x9d]\xda\xe85E\xd1\xe85G\x91\x10L" +
	"\x1d\xb2G~/\xae\xf6\x8f\xde\xf8S\xc0\xc5(\x1a\xff" +
	"k\x14puLR\xcb\x81\xbeS\xfe\x84\x84>>@" +
	"\xa4\x90H\x00\x82@\x00\x0b.\xb4\xe5\xb7_\xfe\xf2=" +
	"$\xc4\xfb\x00)\xc2\xaf\x08 \x8d\x02F\xec\xfc\xfab" +
	"\xcf+\xc6\xfdZ\x15s\x05\xaa\xa2\x88\x02lI\x1b\x8f" +
	"g<\x8f\x0fj2\xb8R\xa0\x194\x97\x7f3}\xb6" +
	"q\xe7!\xad\xf9\xe5\x025\xbf\x82n\xadm\xdf\xea\xe9" +
	"\xfdm\xfa\x87Z\xeb\xeaU\xebvR@\x82s|\xf6" +
	"P\xcf\xaa\x16\x15@e\x1f!\x86F(k\x9f\xe0'" +
	"\xfdf\xff\xc4\x8f\xb5\xb2\xf7\xaa\xb2\x9b\xd4\xad\xd5U\xd3" +
	"\xbf\x12\xfa~\xa2\xdaM\xb7\x9e\x15\xf2\xc8\xd6\xac\xa3'" +
	"\xda\x92\xd7\xbc\xf8\x89\xd6\xe5\x16\xd5\xe5\xcf\xe8V\xcf\xf6" +
	"\xe9\xc7K\xfb\xdf<\xa2u\xf9\x86\xea\xf2=\x0a\x18V" +
	"X:k\xfe\x98\x0bG\x918\x088\x84\x0cTzl" +
	"\xf4*@\x90\x9a\x10=\x0b\x10(\xa3\x0e\xb5\x1c\x1bT" +
	"\xf3\xe61$Xy\xe5\xa9{\xca\x03K\xe1\xf8/H" +
	"U\x94\xe3\xc3\xb8\x02\xd3\xda\xc4\x1e\xdcJ~)wo" +
	"=Su\xed\xfc\xcfN\xd2\xaah\xc9YvaG\xd3" +
	"\xc0&R\x15\x8d\x98\x03\xdcL\xd1\x07\xb1\x07GZ\x09" +
	"zit\xd5\xf5sW\xdf9\xa9a\x87vL\xd9\xe1" +
	"\xdc\xbc\x8f.\xcd\xaf\xbfuJ\x13\xae6L\xc3u\xb3" +
	"t\xdf\xfa\x8e\xb8k\xa7\xb5\xe1j\xc54\\\xa71u" +
	"i\xcd\x83?_\xda:\xe9\xef\x1aBh\xc7\x94\x10\xca" +
	"\xd6\xb6\xde\x11#\x87|\xae\xddz^\xdd\xdaF\xb7\xfe" +
	"\xf3?I\xf3\xab\x9e\\}A\x9bE\xb0\xd2,FZ" +
	"\x09\x00wl|\xbf\xb8a\xda\x97\xb4C\xa02\xf3\xd6" +
	"\x95\x0d\xa3\xb6\x90X$X\xcf\xe0\x11\xc4'\x9cb\xf5" +
	"\xe0*\xea\xdd\xb9\xd5\xb3\x1b;\xd2\xae^T\xb3C\x0d" +
	")\xb2\xba\x88!\x87?\xc8i*\x9e\x13sY-4" +
	"U\xcfL+\x09:\xb6S=\x87\xad\xcd\xcdO\xcf\xed" +
	"wE\xcb\xf5\xd5V\xca\xf5\xeb(`Xc\xee\xa5\x1e" +
	"\xb9\xaf\x7f\xa3\xa5\x94F+\xa5\x94\x16\x0a\xf8\xc9\xe5\xe4" +
	"\x15x\xc3\xf6\x00@\x9b\x0ah\xa7\x80\xf5G&\xf7\xb0" +
	"\x0c\xa8\xbb\xae\x0d\x86\x10C\x83\x11\x1bC\x00\xc7r[" +
	"W\xefxu\x7f;)\x0d\x9e!F\xc5P+\xa7\xc4" +
	"\xfc\x1b\x81\xd2\xe3\xab\xe3#/\x0d\xac\xfaN\xeb\xc6@" +
	"\x1b\x05\xa4\xd8\x88\x88\xf3#\x07\xb4\xe4\xa4\xdd\xed\xa0\x13" +
	"\xc9\x15;\xa7\xe1\xe4sC\xf6\x90j\x10m\xf1\x80%" +
	"\x1b\x89\xd7\\\x9b\x07\xef%\xbf\x94~9\xcb\x9f-\x9f" +
	"\xe6\xb8\xabI\xdc\x06\x1bM\\\xfb\xbc\xcc1C\xea\xf6" +
	"\xde\xd5\xe6\xa5\xc2F\xf3RM\x15\xcd\xf8\xdc\xf0A\xfd" +
	"\xa8\xbc{Zow\xda\xa8\xb7M\x14\x9003\xe6\xe9" +
	"W\xe2g\xdc\xa7E\x9c~\xf6`\xd4\x87\x15;\xaaI" +
	"\xe2\xce\xda\x0e\xe3\x8b\xd4\x90\xf36\x0fN\xe8M\x0c\xb9" +
	"\xf5\xc2i\xe5\xd4\xf1\xda\xfb\x9a\x86\x13z\xe7\x01R\x10" +
	"(\xb2Kr\xb8\xcb\x9c\xae\x089\xd9-\xbb\xecR\xe9" +
	"\xd0|\xa9\xccQ6z\x86\xba(p:\xec\x83\xb2\xed" +
	"\xee\xf2\x12^v\x8b\x11|\x04B\x11\x80\x90`\x8aG" +
	"H\xec\xc9\x83h\xe5\xc0\xe8,\x97\xc1\x8480i\xe4" +
	"\xf1rrA\x91\xdbU^&;]^\x91\xe3\xe9\xda" +
	"(;]Y\x00bO\xde\x80\x90/)\xe0h\xfch" +
	"Q\xea\xe6W6\x09)\xc3\x11'\x0c6\x82\x9f\xbe\x80" +
	"5\xb5\x10\x9b\x888\xc1d\x8c[\xe4*\x92\xedc\xc1" +
	"B\xac\x1b\x0bY\xe0W\xcb\xc9\xc9\xc5\xce\"\x87W\xe3" +
	"Tg\x118\xfc\xca\x18i\xeb)c\xc9\x02\xd6T!" +
	"(\xeb*fY\x92K*\x05\xb76\x1e\xf3\x9d\xae\x85" +
	"^\xe4D\xf2\x93\x0a\x1e\x94N\x91\x01\xb1M\xf4\xc7\xd6" +
	"R \xc9\xd2C\xc15\xc8\xc9\xc5n\xa7\xc3\xee\xc8w" +
	"\x16\xd8\x99\xaf3\xa6O\x9b\xa0~\xe8\xcc\x802\xc9%" +
	"\x95\x94\xd8K\xbc;\xb2\xd4%\x94\xf8#\xc4f\x8e^" +
	"\x84X\xfb\x03c\xe9\x10\"\xc4\xcb\xc9\x0b$\x99\x998" +
	"\x89\xfcT\x8d\x8b\xa3N\x07\x1a\x97o\xf7\x19\x96\xdf\x09" +
	"\x8e\x0b\x96\x07v\xbf\xf1l\xa8\xe9\x19\xcf\xce[\xc0\x8e" +
	"=\xa1\xa5\xb7\xcc\xe5\xcc\xb7\xbb\xdd\xcc.\xefJM\\" +
	"\x96d\xa1\x89\xeb\xe5K\xdc\x04\x92\xb8\xb1<\x88/r" +
	" \x00X\x81|\x9c2\x1a!q<\x0fb\x16\x07\x02" +
	"\xc7Y\xc9X\x122\x09r2\x0f\xe2KA)N\xcf" +
	"+rH\xae%\xd0\x0bq\xd0\x0b\x81Er-p\xb3" +
	"\xc5#\xa3\x9a\x9dN\x1a\xf5\xf1\xfa\xf4I99\xcf\xe5" +
	"\x94\x0a\xf2%\xb7\xec\x158\xce\xb7\xf6\x17\x92\x1b\xb1\x0d" +
	"!\x94^\x98|A\xe4\x16\xd8\x83\xe4\x8e\x8f\xa3_\xfc" +
	"Yf\xd4\xa8\x97e6\x7f\x81\x8d\x93\xd0\x18#\xb0\x89" +
	"\xe3\xe8\xca\xaf\x90\xcd.=\x85\xec&\x01\xec2\x13Z" +
	"O\xe8G0\xce\x11\xe8)\x1byz\x8a\xd9=\x04\xd8" +
	"Y<4O\x03\x9bL\xdb<l|\xea)cW\x12" +
	"`g\x95\xd0\xbc,(r\xe7K\xae\x02?\xfb\x93\x15" +
	"\xf2\xabd\x879=\x95ld\x01;\xe4\x86\x18\xd8\x00" +
	"\xeewt\x83b;m~V\xe1\x96\xc7\xed4^N" +
	"\x96\xed,\xfa/\xd9\xedA4\xf2\xb8\xc6\xe9ryI" +
	"\xf7<\xd6\xcdX\xf8\x1eGvv\x06 k}n\x09" +
	"\xe6\xb5\xf0\xddy(\xdc\xddI\xdc|\x89\x95\xd5D\xc9" +
	"\xe13\xdd\x184\xc2\x82\x07|\xd8\xa4\xdcu\xf1\x05k" +
	"\xee\xa2\x1a\xbac\x81~1\x84_\xb4\x86GVC\xb6" +
	"j'Bb\x1f\x9f\xdcMd|\xd6\xf2 n\xd3\xcc" +
	"\xd4z\xf2\xf1\x0d\x1e\xc4\x06\xcdL\xddN>n\xe1A" +
	"|\x8b\x03\x81\xe7\xad\xe4\x90/\xec$\x1f\xb7\xf1 \xbe" +
	"\xc3\x01DX!\x02!a\xf78\x84\xc4\x06\x1e\xc4w" +
	"9\x10\x0c\x11V0 $\xec%\xc0\xb7x\x10\xdf\xe7" +
	" \xdd-K\x0b\xec)\xbe\x99L\x97\xc3\x03\x97\xa9\x81" +
	"\xcb\xe7\xd8ri\x9e\x94\xbf\xb0\xc4\xb9\x00\x0c\x88\x03\x83" +
	"\xfa\xb7\\\xee\x06\x8b2\xb7x[\xe3\x8f&\xd6\xbd\x8e" +
	"\x10\x80\x05\x05\xd0r@yi\x18\x92\xdd\x13\xf4\x18\x92" +
	"]\xc0\x81]\xf2BcH\xdd\xba\xd2\xa8d\xefF\xba" +
	"*\xbd\x17w`\x8f\x1b!\xa84t6\xd7\xed]\x1e" +
	"UuZW\xa7\xe1t\xcf\x8c\xe1\x94{g\xcd\xabs" +
	"N\x0d\x1e1\xdd\xd2\xf90\xad\x84CP\\\xb0\xf5\xb0" +
	"\xd0\x9fP\xf6\xa4\xa9\x97P\xf6\xb4\x00\xec\xcd&\xc4S" +
	"qWl\x13\x1c2CW\x07L\xc6&t\x0a\xa0\xc7" +
	"\x1dWz\x97/\xbfD>\xbcKU\x97\x95\x1a\xce\xc9" +
	"\xf6\x11\x97\xb5\xf0\x0d\xd6i\x80n]);g\xe7\xa0" +
	"4E\xf9\xe4JDn.\x0fb!\x07\x8c\x9c\xedS" +
	"\x11\x12\x0bx\x10\xcb\x089\x83J\xce\xa5\x84s\x0by" +
	"\x10eB\xce\x95*9\xffb8Bb\x09\x0f\xe2\xe2" +
	"`\xab\xf2\xa52)\xbfH^\x82\x10bD\xba\x94\x1a" +
	"\xe1r\xb3u\x9cTPZ$\x03 \x0e \xd0\x8fG" +
	"\xdcg\xfcS\xe6\xf1\x9aU_\xacQr\xcb\x9a\xbb\x82" +
	"\xf7!L\xaf\xd9\xd8{:\xb0g\xa6\xf0\x8e\xb4\x9d\xf1" +
	"R \x97tkLw\xd5\x06\xe1\x97+\x17\xc4\xea\x9a" +
	"\xa1\xc3\xde\xc2u\x9f\x1d\xbc/\xa7\xc0\x9e\xa4C\xe3\xa8" +
	".\x8e\xb2\xdeA\xf2\xff\x00\x00\x00\xff\xff\x10\xc3\x85>"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_ab2c34cea45a1972,
		Nodes: []uint64{
			0x807dc5f537fcab41,
			0x80fd92fad0bb4268,
			0x82363dd6623bd8c6,
			0x89cea9112e592ae3,
			0x934f8ecfe0b88072,
			0x94a092fe2b3f417b,
			0x951c5be10a03b055,
			0x97cce63a86a62268,
			0x9b5b1e979ebdd44d,
			0x9c279b3ef22d2982,
			0x9d9b2dd257eaa275,
			0x9f5cc6256a489aff,
			0xa031c5c9cb654b9b,
			0xa482253d786c10f8,
			0xa494945258ee398a,
			0xa4abc883f189a637,
			0xa4e92a91b6736d0e,
			0xa609f38f68ba2a7b,
			0xa62d175a6f252e42,
			0xa6f4fc841b788599,
			0xa7941fb274ab2c4a,
			0xae491ab8c12d3be8,
			0xb2dcdff163e1da67,
			0xb607e008dde3a535,
			0xb9133641cb972d16,
			0xbba507584fe4750e,
			0xbf3fec17879ef194,
			0xc18a872e52446f29,
			0xc346b67e47030a8f,
			0xc41a11e24f818529,
			0xc44c8e2fe1ccc650,
			0xc5ee1e6dcb4fa187,
			0xc6da3b66576d6830,
			0xcaa29224cac1bb39,
			0xce43d9e98127eff8,
			0xceace8d6ea81127f,
			0xd0ef9d66dec05ed6,
			0xd1e91ff593af6dee,
			0xd3479edeb3fc8e30,
			0xd72c0951f4c98f70,
			0xda8d0b81662df0db,
			0xdc4ea46ab497f513,
			0xdde83df5b1588dd6,
			0xdf155a6ab55bbcc2,
			0xe01b5d23bdbd14c2,
			0xe4885c06de5cb130,
			0xe4a19513862fdf38,
			0xea9b200f0648c593,
			0xf1b660a38dc95cca,
			0xf38121de37cbe206,
			0xf5f83d5bc12037d9,
			0xf86e4e752b835b1b,
			0xf8ad9b2c3b4d5ef1,
			0xf962399dbc05d753,
			0xfa53225f23155529,
			0xfa94cbd0ffd13eef,
		},
		Compressed: true,
	})
}
