// Code generated by capnpc-go. DO NOT EDIT.

package integration

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type Romberg capnp.Client

// Romberg_TypeID is the unique identifier for the type Romberg.
const Romberg_TypeID = 0x90bff12097db6889

func (c Romberg) Write(ctx context.Context, params func(Romberg_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x90bff12097db6889,
			MethodID:      0,
			InterfaceName: "nomagique/integration/romberg.capnp:Romberg",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Romberg_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Romberg) Done(ctx context.Context, params func(Romberg_done_Params) error) (Romberg_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x90bff12097db6889,
			MethodID:      1,
			InterfaceName: "nomagique/integration/romberg.capnp:Romberg",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Romberg_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Romberg_done_Results_Future{Future: ans.Future()}, release

}

func (c Romberg) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Romberg) String() string {
	return "Romberg(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Romberg) AddRef() Romberg {
	return Romberg(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Romberg) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Romberg) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Romberg) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Romberg) DecodeFromPtr(p capnp.Ptr) Romberg {
	return Romberg(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Romberg) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Romberg) IsSame(other Romberg) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Romberg) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Romberg) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Romberg_Server is a Romberg with a local implementation.
type Romberg_Server interface {
	Write(context.Context, Romberg_write) error

	Done(context.Context, Romberg_done) error
}

// Romberg_NewServer creates a new Server from an implementation of Romberg_Server.
func Romberg_NewServer(s Romberg_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Romberg_Methods(nil, s), s, c)
}

// Romberg_ServerToClient creates a new Client from an implementation of Romberg_Server.
// The caller is responsible for calling Release on the returned Client.
func Romberg_ServerToClient(s Romberg_Server) Romberg {
	return Romberg(capnp.NewClient(Romberg_NewServer(s)))
}

// Romberg_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Romberg_Methods(methods []server.Method, s Romberg_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x90bff12097db6889,
			MethodID:      0,
			InterfaceName: "nomagique/integration/romberg.capnp:Romberg",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Romberg_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x90bff12097db6889,
			MethodID:      1,
			InterfaceName: "nomagique/integration/romberg.capnp:Romberg",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Romberg_done{call})
		},
	})

	return methods
}

// Romberg_write holds the state for a server call to Romberg.write.
// See server.Call for documentation.
type Romberg_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Romberg_write) Args() Romberg_write_Params {
	return Romberg_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Romberg_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Romberg_done holds the state for a server call to Romberg.done.
// See server.Call for documentation.
type Romberg_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Romberg_done) Args() Romberg_done_Params {
	return Romberg_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Romberg_done) AllocResults() (Romberg_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Romberg_done_Results(r), err
}

// Romberg_List is a list of Romberg.
type Romberg_List = capnp.CapList[Romberg]

// NewRomberg_List creates a new list of Romberg.
func NewRomberg_List(s *capnp.Segment, sz int32) (Romberg_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Romberg](l), err
}

type Romberg_write_Params capnp.Struct

// Romberg_write_Params_TypeID is the unique identifier for the type Romberg_write_Params.
const Romberg_write_Params_TypeID = 0xa6f454dd6a02a369

func NewRomberg_write_Params(s *capnp.Segment) (Romberg_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Romberg_write_Params(st), err
}

func NewRootRomberg_write_Params(s *capnp.Segment) (Romberg_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Romberg_write_Params(st), err
}

func ReadRootRomberg_write_Params(msg *capnp.Message) (Romberg_write_Params, error) {
	root, err := msg.Root()
	return Romberg_write_Params(root.Struct()), err
}

func (s Romberg_write_Params) String() string {
	str, _ := text.Marshal(0xa6f454dd6a02a369, capnp.Struct(s))
	return str
}

func (s Romberg_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Romberg_write_Params) DecodeFromPtr(p capnp.Ptr) Romberg_write_Params {
	return Romberg_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Romberg_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Romberg_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Romberg_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Romberg_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Romberg_write_Params) Y() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.Float64List(p.List()), err
}

func (s Romberg_write_Params) HasY() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Romberg_write_Params) SetY(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewY sets the y field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Romberg_write_Params) NewY(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Romberg_write_Params) Dx() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Romberg_write_Params) SetDx(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Romberg_write_Params_List is a list of Romberg_write_Params.
type Romberg_write_Params_List = capnp.StructList[Romberg_write_Params]

// NewRomberg_write_Params creates a new list of Romberg_write_Params.
func NewRomberg_write_Params_List(s *capnp.Segment, sz int32) (Romberg_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Romberg_write_Params](l), err
}

// Romberg_write_Params_Future is a wrapper for a Romberg_write_Params promised by a client call.
type Romberg_write_Params_Future struct{ *capnp.Future }

func (f Romberg_write_Params_Future) Struct() (Romberg_write_Params, error) {
	p, err := f.Future.Ptr()
	return Romberg_write_Params(p.Struct()), err
}

type Romberg_done_Params capnp.Struct

// Romberg_done_Params_TypeID is the unique identifier for the type Romberg_done_Params.
const Romberg_done_Params_TypeID = 0xa25be46530365e6d

func NewRomberg_done_Params(s *capnp.Segment) (Romberg_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Romberg_done_Params(st), err
}

func NewRootRomberg_done_Params(s *capnp.Segment) (Romberg_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Romberg_done_Params(st), err
}

func ReadRootRomberg_done_Params(msg *capnp.Message) (Romberg_done_Params, error) {
	root, err := msg.Root()
	return Romberg_done_Params(root.Struct()), err
}

func (s Romberg_done_Params) String() string {
	str, _ := text.Marshal(0xa25be46530365e6d, capnp.Struct(s))
	return str
}

func (s Romberg_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Romberg_done_Params) DecodeFromPtr(p capnp.Ptr) Romberg_done_Params {
	return Romberg_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Romberg_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Romberg_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Romberg_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Romberg_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Romberg_done_Params_List is a list of Romberg_done_Params.
type Romberg_done_Params_List = capnp.StructList[Romberg_done_Params]

// NewRomberg_done_Params creates a new list of Romberg_done_Params.
func NewRomberg_done_Params_List(s *capnp.Segment, sz int32) (Romberg_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Romberg_done_Params](l), err
}

// Romberg_done_Params_Future is a wrapper for a Romberg_done_Params promised by a client call.
type Romberg_done_Params_Future struct{ *capnp.Future }

func (f Romberg_done_Params_Future) Struct() (Romberg_done_Params, error) {
	p, err := f.Future.Ptr()
	return Romberg_done_Params(p.Struct()), err
}

type Romberg_done_Results capnp.Struct

// Romberg_done_Results_TypeID is the unique identifier for the type Romberg_done_Results.
const Romberg_done_Results_TypeID = 0xc1f39b5872fadade

func NewRomberg_done_Results(s *capnp.Segment) (Romberg_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Romberg_done_Results(st), err
}

func NewRootRomberg_done_Results(s *capnp.Segment) (Romberg_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Romberg_done_Results(st), err
}

func ReadRootRomberg_done_Results(msg *capnp.Message) (Romberg_done_Results, error) {
	root, err := msg.Root()
	return Romberg_done_Results(root.Struct()), err
}

func (s Romberg_done_Results) String() string {
	str, _ := text.Marshal(0xc1f39b5872fadade, capnp.Struct(s))
	return str
}

func (s Romberg_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Romberg_done_Results) DecodeFromPtr(p capnp.Ptr) Romberg_done_Results {
	return Romberg_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Romberg_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Romberg_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Romberg_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Romberg_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Romberg_done_Results) Integral() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Romberg_done_Results) SetIntegral(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Romberg_done_Results_List is a list of Romberg_done_Results.
type Romberg_done_Results_List = capnp.StructList[Romberg_done_Results]

// NewRomberg_done_Results creates a new list of Romberg_done_Results.
func NewRomberg_done_Results_List(s *capnp.Segment, sz int32) (Romberg_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Romberg_done_Results](l), err
}

// Romberg_done_Results_Future is a wrapper for a Romberg_done_Results promised by a client call.
type Romberg_done_Results_Future struct{ *capnp.Future }

func (f Romberg_done_Results_Future) Struct() (Romberg_done_Results, error) {
	p, err := f.Future.Ptr()
	return Romberg_done_Results(p.Struct()), err
}
