// Code generated by capnpc-go. DO NOT EDIT.

package tables

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	runtime "github.com/theapemachine/symm/nomagique/runtime"
)

type IcebergTable capnp.Client

// IcebergTable_TypeID is the unique identifier for the type IcebergTable.
const IcebergTable_TypeID = 0xce2ab50338f6a568

func (c IcebergTable) Write(ctx context.Context, params func(IcebergTable_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xce2ab50338f6a568,
			MethodID:      0,
			InterfaceName: "nomagique/store/tables/table.capnp:IcebergTable",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(IcebergTable_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c IcebergTable) Done(ctx context.Context, params func(IcebergTable_done_Params) error) (IcebergTable_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xce2ab50338f6a568,
			MethodID:      1,
			InterfaceName: "nomagique/store/tables/table.capnp:IcebergTable",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(IcebergTable_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return IcebergTable_done_Results_Future{Future: ans.Future()}, release

}

func (c IcebergTable) Flush(ctx context.Context, params func(runtime.Durable_flush_Params) error) (runtime.Durable_flush_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xd317eb5f30a42558,
			MethodID:      0,
			InterfaceName: "nomagique/runtime/status.capnp:Durable",
			MethodName:    "flush",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(runtime.Durable_flush_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return runtime.Durable_flush_Results_Future{Future: ans.Future()}, release

}

func (c IcebergTable) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c IcebergTable) String() string {
	return "IcebergTable(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c IcebergTable) AddRef() IcebergTable {
	return IcebergTable(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c IcebergTable) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c IcebergTable) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c IcebergTable) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (IcebergTable) DecodeFromPtr(p capnp.Ptr) IcebergTable {
	return IcebergTable(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c IcebergTable) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c IcebergTable) IsSame(other IcebergTable) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c IcebergTable) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c IcebergTable) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A IcebergTable_Server is a IcebergTable with a local implementation.
type IcebergTable_Server interface {
	Write(context.Context, IcebergTable_write) error

	Done(context.Context, IcebergTable_done) error

	Flush(context.Context, runtime.Durable_flush) error
}

// IcebergTable_NewServer creates a new Server from an implementation of IcebergTable_Server.
func IcebergTable_NewServer(s IcebergTable_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(IcebergTable_Methods(nil, s), s, c)
}

// IcebergTable_ServerToClient creates a new Client from an implementation of IcebergTable_Server.
// The caller is responsible for calling Release on the returned Client.
func IcebergTable_ServerToClient(s IcebergTable_Server) IcebergTable {
	return IcebergTable(capnp.NewClient(IcebergTable_NewServer(s)))
}

// IcebergTable_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func IcebergTable_Methods(methods []server.Method, s IcebergTable_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xce2ab50338f6a568,
			MethodID:      0,
			InterfaceName: "nomagique/store/tables/table.capnp:IcebergTable",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, IcebergTable_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xce2ab50338f6a568,
			MethodID:      1,
			InterfaceName: "nomagique/store/tables/table.capnp:IcebergTable",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, IcebergTable_done{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xd317eb5f30a42558,
			MethodID:      0,
			InterfaceName: "nomagique/runtime/status.capnp:Durable",
			MethodName:    "flush",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Flush(ctx, runtime.Durable_flush{call})
		},
	})

	return methods
}

// IcebergTable_write holds the state for a server call to IcebergTable.write.
// See server.Call for documentation.
type IcebergTable_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c IcebergTable_write) Args() IcebergTable_write_Params {
	return IcebergTable_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c IcebergTable_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// IcebergTable_done holds the state for a server call to IcebergTable.done.
// See server.Call for documentation.
type IcebergTable_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c IcebergTable_done) Args() IcebergTable_done_Params {
	return IcebergTable_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c IcebergTable_done) AllocResults() (IcebergTable_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return IcebergTable_done_Results(r), err
}

// IcebergTable_List is a list of IcebergTable.
type IcebergTable_List = capnp.CapList[IcebergTable]

// NewIcebergTable_List creates a new list of IcebergTable.
func NewIcebergTable_List(s *capnp.Segment, sz int32) (IcebergTable_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[IcebergTable](l), err
}

type IcebergTable_write_Params capnp.Struct

// IcebergTable_write_Params_TypeID is the unique identifier for the type IcebergTable_write_Params.
const IcebergTable_write_Params_TypeID = 0xcec2209f6cf83c36

func NewIcebergTable_write_Params(s *capnp.Segment) (IcebergTable_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return IcebergTable_write_Params(st), err
}

func NewRootIcebergTable_write_Params(s *capnp.Segment) (IcebergTable_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return IcebergTable_write_Params(st), err
}

func ReadRootIcebergTable_write_Params(msg *capnp.Message) (IcebergTable_write_Params, error) {
	root, err := msg.Root()
	return IcebergTable_write_Params(root.Struct()), err
}

func (s IcebergTable_write_Params) String() string {
	str, _ := text.Marshal(0xcec2209f6cf83c36, capnp.Struct(s))
	return str
}

func (s IcebergTable_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IcebergTable_write_Params) DecodeFromPtr(p capnp.Ptr) IcebergTable_write_Params {
	return IcebergTable_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IcebergTable_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IcebergTable_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IcebergTable_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IcebergTable_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IcebergTable_write_Params) Config() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IcebergTable_write_Params) HasConfig() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IcebergTable_write_Params) ConfigBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IcebergTable_write_Params) SetConfig(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IcebergTable_write_Params) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s IcebergTable_write_Params) HasPayload() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IcebergTable_write_Params) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s IcebergTable_write_Params) Commit() bool {
	return capnp.Struct(s).Bit(0)
}

func (s IcebergTable_write_Params) SetCommit(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// IcebergTable_write_Params_List is a list of IcebergTable_write_Params.
type IcebergTable_write_Params_List = capnp.StructList[IcebergTable_write_Params]

// NewIcebergTable_write_Params creates a new list of IcebergTable_write_Params.
func NewIcebergTable_write_Params_List(s *capnp.Segment, sz int32) (IcebergTable_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[IcebergTable_write_Params](l), err
}

// IcebergTable_write_Params_Future is a wrapper for a IcebergTable_write_Params promised by a client call.
type IcebergTable_write_Params_Future struct{ *capnp.Future }

func (f IcebergTable_write_Params_Future) Struct() (IcebergTable_write_Params, error) {
	p, err := f.Future.Ptr()
	return IcebergTable_write_Params(p.Struct()), err
}

type IcebergTable_done_Params capnp.Struct

// IcebergTable_done_Params_TypeID is the unique identifier for the type IcebergTable_done_Params.
const IcebergTable_done_Params_TypeID = 0xb5726b5a01ec0103

func NewIcebergTable_done_Params(s *capnp.Segment) (IcebergTable_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return IcebergTable_done_Params(st), err
}

func NewRootIcebergTable_done_Params(s *capnp.Segment) (IcebergTable_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return IcebergTable_done_Params(st), err
}

func ReadRootIcebergTable_done_Params(msg *capnp.Message) (IcebergTable_done_Params, error) {
	root, err := msg.Root()
	return IcebergTable_done_Params(root.Struct()), err
}

func (s IcebergTable_done_Params) String() string {
	str, _ := text.Marshal(0xb5726b5a01ec0103, capnp.Struct(s))
	return str
}

func (s IcebergTable_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IcebergTable_done_Params) DecodeFromPtr(p capnp.Ptr) IcebergTable_done_Params {
	return IcebergTable_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IcebergTable_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IcebergTable_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IcebergTable_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IcebergTable_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// IcebergTable_done_Params_List is a list of IcebergTable_done_Params.
type IcebergTable_done_Params_List = capnp.StructList[IcebergTable_done_Params]

// NewIcebergTable_done_Params creates a new list of IcebergTable_done_Params.
func NewIcebergTable_done_Params_List(s *capnp.Segment, sz int32) (IcebergTable_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[IcebergTable_done_Params](l), err
}

// IcebergTable_done_Params_Future is a wrapper for a IcebergTable_done_Params promised by a client call.
type IcebergTable_done_Params_Future struct{ *capnp.Future }

func (f IcebergTable_done_Params_Future) Struct() (IcebergTable_done_Params, error) {
	p, err := f.Future.Ptr()
	return IcebergTable_done_Params(p.Struct()), err
}

type IcebergTable_done_Results capnp.Struct

// IcebergTable_done_Results_TypeID is the unique identifier for the type IcebergTable_done_Results.
const IcebergTable_done_Results_TypeID = 0x8b02f933f4bac737

func NewIcebergTable_done_Results(s *capnp.Segment) (IcebergTable_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return IcebergTable_done_Results(st), err
}

func NewRootIcebergTable_done_Results(s *capnp.Segment) (IcebergTable_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return IcebergTable_done_Results(st), err
}

func ReadRootIcebergTable_done_Results(msg *capnp.Message) (IcebergTable_done_Results, error) {
	root, err := msg.Root()
	return IcebergTable_done_Results(root.Struct()), err
}

func (s IcebergTable_done_Results) String() string {
	str, _ := text.Marshal(0x8b02f933f4bac737, capnp.Struct(s))
	return str
}

func (s IcebergTable_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IcebergTable_done_Results) DecodeFromPtr(p capnp.Ptr) IcebergTable_done_Results {
	return IcebergTable_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IcebergTable_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IcebergTable_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IcebergTable_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IcebergTable_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IcebergTable_done_Results) Out() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s IcebergTable_done_Results) HasOut() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IcebergTable_done_Results) SetOut(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s IcebergTable_done_Results) Pending() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s IcebergTable_done_Results) SetPending(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s IcebergTable_done_Results) Committed() int64 {
	return int64(capnp.Struct(s).Uint64(8))
}

func (s IcebergTable_done_Results) SetCommitted(v int64) {
	capnp.Struct(s).SetUint64(8, uint64(v))
}

func (s IcebergTable_done_Results) Bytes() int64 {
	return int64(capnp.Struct(s).Uint64(16))
}

func (s IcebergTable_done_Results) SetBytes(v int64) {
	capnp.Struct(s).SetUint64(16, uint64(v))
}

// IcebergTable_done_Results_List is a list of IcebergTable_done_Results.
type IcebergTable_done_Results_List = capnp.StructList[IcebergTable_done_Results]

// NewIcebergTable_done_Results creates a new list of IcebergTable_done_Results.
func NewIcebergTable_done_Results_List(s *capnp.Segment, sz int32) (IcebergTable_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[IcebergTable_done_Results](l), err
}

// IcebergTable_done_Results_Future is a wrapper for a IcebergTable_done_Results promised by a client call.
type IcebergTable_done_Results_Future struct{ *capnp.Future }

func (f IcebergTable_done_Results_Future) Struct() (IcebergTable_done_Results, error) {
	p, err := f.Future.Ptr()
	return IcebergTable_done_Results(p.Struct()), err
}

type IcebergScan capnp.Client

// IcebergScan_TypeID is the unique identifier for the type IcebergScan.
const IcebergScan_TypeID = 0xefa0adbd7a396d92

func (c IcebergScan) Write(ctx context.Context, params func(IcebergScan_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xefa0adbd7a396d92,
			MethodID:      0,
			InterfaceName: "nomagique/store/tables/table.capnp:IcebergScan",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(IcebergScan_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c IcebergScan) Done(ctx context.Context, params func(IcebergScan_done_Params) error) (IcebergScan_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xefa0adbd7a396d92,
			MethodID:      1,
			InterfaceName: "nomagique/store/tables/table.capnp:IcebergScan",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(IcebergScan_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return IcebergScan_done_Results_Future{Future: ans.Future()}, release

}

func (c IcebergScan) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c IcebergScan) String() string {
	return "IcebergScan(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c IcebergScan) AddRef() IcebergScan {
	return IcebergScan(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c IcebergScan) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c IcebergScan) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c IcebergScan) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (IcebergScan) DecodeFromPtr(p capnp.Ptr) IcebergScan {
	return IcebergScan(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c IcebergScan) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c IcebergScan) IsSame(other IcebergScan) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c IcebergScan) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c IcebergScan) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A IcebergScan_Server is a IcebergScan with a local implementation.
type IcebergScan_Server interface {
	Write(context.Context, IcebergScan_write) error

	Done(context.Context, IcebergScan_done) error
}

// IcebergScan_NewServer creates a new Server from an implementation of IcebergScan_Server.
func IcebergScan_NewServer(s IcebergScan_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(IcebergScan_Methods(nil, s), s, c)
}

// IcebergScan_ServerToClient creates a new Client from an implementation of IcebergScan_Server.
// The caller is responsible for calling Release on the returned Client.
func IcebergScan_ServerToClient(s IcebergScan_Server) IcebergScan {
	return IcebergScan(capnp.NewClient(IcebergScan_NewServer(s)))
}

// IcebergScan_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func IcebergScan_Methods(methods []server.Method, s IcebergScan_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xefa0adbd7a396d92,
			MethodID:      0,
			InterfaceName: "nomagique/store/tables/table.capnp:IcebergScan",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, IcebergScan_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xefa0adbd7a396d92,
			MethodID:      1,
			InterfaceName: "nomagique/store/tables/table.capnp:IcebergScan",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, IcebergScan_done{call})
		},
	})

	return methods
}

// IcebergScan_write holds the state for a server call to IcebergScan.write.
// See server.Call for documentation.
type IcebergScan_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c IcebergScan_write) Args() IcebergScan_write_Params {
	return IcebergScan_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c IcebergScan_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// IcebergScan_done holds the state for a server call to IcebergScan.done.
// See server.Call for documentation.
type IcebergScan_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c IcebergScan_done) Args() IcebergScan_done_Params {
	return IcebergScan_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c IcebergScan_done) AllocResults() (IcebergScan_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return IcebergScan_done_Results(r), err
}

// IcebergScan_List is a list of IcebergScan.
type IcebergScan_List = capnp.CapList[IcebergScan]

// NewIcebergScan_List creates a new list of IcebergScan.
func NewIcebergScan_List(s *capnp.Segment, sz int32) (IcebergScan_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[IcebergScan](l), err
}

type IcebergScan_write_Params capnp.Struct

// IcebergScan_write_Params_TypeID is the unique identifier for the type IcebergScan_write_Params.
const IcebergScan_write_Params_TypeID = 0xe0d4d972989bb7b6

func NewIcebergScan_write_Params(s *capnp.Segment) (IcebergScan_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return IcebergScan_write_Params(st), err
}

func NewRootIcebergScan_write_Params(s *capnp.Segment) (IcebergScan_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return IcebergScan_write_Params(st), err
}

func ReadRootIcebergScan_write_Params(msg *capnp.Message) (IcebergScan_write_Params, error) {
	root, err := msg.Root()
	return IcebergScan_write_Params(root.Struct()), err
}

func (s IcebergScan_write_Params) String() string {
	str, _ := text.Marshal(0xe0d4d972989bb7b6, capnp.Struct(s))
	return str
}

func (s IcebergScan_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IcebergScan_write_Params) DecodeFromPtr(p capnp.Ptr) IcebergScan_write_Params {
	return IcebergScan_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IcebergScan_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IcebergScan_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IcebergScan_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IcebergScan_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IcebergScan_write_Params) Config() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IcebergScan_write_Params) HasConfig() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IcebergScan_write_Params) ConfigBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IcebergScan_write_Params) SetConfig(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IcebergScan_write_Params) Query() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s IcebergScan_write_Params) HasQuery() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IcebergScan_write_Params) SetQuery(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// IcebergScan_write_Params_List is a list of IcebergScan_write_Params.
type IcebergScan_write_Params_List = capnp.StructList[IcebergScan_write_Params]

// NewIcebergScan_write_Params creates a new list of IcebergScan_write_Params.
func NewIcebergScan_write_Params_List(s *capnp.Segment, sz int32) (IcebergScan_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[IcebergScan_write_Params](l), err
}

// IcebergScan_write_Params_Future is a wrapper for a IcebergScan_write_Params promised by a client call.
type IcebergScan_write_Params_Future struct{ *capnp.Future }

func (f IcebergScan_write_Params_Future) Struct() (IcebergScan_write_Params, error) {
	p, err := f.Future.Ptr()
	return IcebergScan_write_Params(p.Struct()), err
}

type IcebergScan_done_Params capnp.Struct

// IcebergScan_done_Params_TypeID is the unique identifier for the type IcebergScan_done_Params.
const IcebergScan_done_Params_TypeID = 0x83aa2d97a293e68f

func NewIcebergScan_done_Params(s *capnp.Segment) (IcebergScan_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return IcebergScan_done_Params(st), err
}

func NewRootIcebergScan_done_Params(s *capnp.Segment) (IcebergScan_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return IcebergScan_done_Params(st), err
}

func ReadRootIcebergScan_done_Params(msg *capnp.Message) (IcebergScan_done_Params, error) {
	root, err := msg.Root()
	return IcebergScan_done_Params(root.Struct()), err
}

func (s IcebergScan_done_Params) String() string {
	str, _ := text.Marshal(0x83aa2d97a293e68f, capnp.Struct(s))
	return str
}

func (s IcebergScan_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IcebergScan_done_Params) DecodeFromPtr(p capnp.Ptr) IcebergScan_done_Params {
	return IcebergScan_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IcebergScan_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IcebergScan_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IcebergScan_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IcebergScan_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// IcebergScan_done_Params_List is a list of IcebergScan_done_Params.
type IcebergScan_done_Params_List = capnp.StructList[IcebergScan_done_Params]

// NewIcebergScan_done_Params creates a new list of IcebergScan_done_Params.
func NewIcebergScan_done_Params_List(s *capnp.Segment, sz int32) (IcebergScan_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[IcebergScan_done_Params](l), err
}

// IcebergScan_done_Params_Future is a wrapper for a IcebergScan_done_Params promised by a client call.
type IcebergScan_done_Params_Future struct{ *capnp.Future }

func (f IcebergScan_done_Params_Future) Struct() (IcebergScan_done_Params, error) {
	p, err := f.Future.Ptr()
	return IcebergScan_done_Params(p.Struct()), err
}

type IcebergScan_done_Results capnp.Struct

// IcebergScan_done_Results_TypeID is the unique identifier for the type IcebergScan_done_Results.
const IcebergScan_done_Results_TypeID = 0x9974b38894482732

func NewIcebergScan_done_Results(s *capnp.Segment) (IcebergScan_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return IcebergScan_done_Results(st), err
}

func NewRootIcebergScan_done_Results(s *capnp.Segment) (IcebergScan_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return IcebergScan_done_Results(st), err
}

func ReadRootIcebergScan_done_Results(msg *capnp.Message) (IcebergScan_done_Results, error) {
	root, err := msg.Root()
	return IcebergScan_done_Results(root.Struct()), err
}

func (s IcebergScan_done_Results) String() string {
	str, _ := text.Marshal(0x9974b38894482732, capnp.Struct(s))
	return str
}

func (s IcebergScan_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IcebergScan_done_Results) DecodeFromPtr(p capnp.Ptr) IcebergScan_done_Results {
	return IcebergScan_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IcebergScan_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IcebergScan_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IcebergScan_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IcebergScan_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IcebergScan_done_Results) Out() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s IcebergScan_done_Results) HasOut() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IcebergScan_done_Results) SetOut(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

// IcebergScan_done_Results_List is a list of IcebergScan_done_Results.
type IcebergScan_done_Results_List = capnp.StructList[IcebergScan_done_Results]

// NewIcebergScan_done_Results creates a new list of IcebergScan_done_Results.
func NewIcebergScan_done_Results_List(s *capnp.Segment, sz int32) (IcebergScan_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[IcebergScan_done_Results](l), err
}

// IcebergScan_done_Results_Future is a wrapper for a IcebergScan_done_Results promised by a client call.
type IcebergScan_done_Results_Future struct{ *capnp.Future }

func (f IcebergScan_done_Results_Future) Struct() (IcebergScan_done_Results, error) {
	p, err := f.Future.Ptr()
	return IcebergScan_done_Results(p.Struct()), err
}

const schema_c7e14a3b8d9a2c1f = "x\xda\x9c\x94_H\x14]\x18\xc6\xdf\xe7\x9c\x99\x1d\xf9" +
	"p\xf1\x1bvA\xba\xda(\xa5\x92\xd4\xd5\xed\xaf\x05\xbb" +
	"D\x82F\xc1\x1e\xf3\"B\xb0qwZ\x97vgu" +
	"f\x16\xd3\x9b\xa0.\x0c\"\x82\x0aJ\xbb(\"o\x82" +
	"\x08\x09\x0b\x02!\xba\xf1N\x90\xba)\x082\xb0\xa0\x02" +
	"\x092\xf2j\xe2\xec6\xabaQz50\xe7}\xcf" +
	"\xf9\xbd\xcf\xf3\x9c\x13\xfd\x8f%\x94\x96\xe0\xa2FL\xf4" +
	"\xa8\x01\xef\xca\xfbkwo4\xde\xbf@z3\x88\x14" +
	"\x8d(\xf6\x86\xbf\x06)\xde\xde\x99\xa7_c\xcb\xec\x12" +
	"\x89(8\x91\x0a\xb96\xc7?\x82\x10Z\xe0\x1f\x08^" +
	"\xeb\xb6\x8e\xeb\x17\x1f\xb9c\xe5\xder\xc1\xb4\xf2N\x16" +
	"\xcc)q\x82\xc7\xf1\x19'\xcf\xd8S\xa4G\xfd\xcd\xbf" +
	"\xc8u\xc5\xeb\x9f\xf8\xb6\x8fO5\xcc\x92\xbe\x95{\x91" +
	"\x9d\xe3\x97\x0f\x1c\x99\x9f!BlA9\x8f\xd0\xb2," +
	"\x0d-)\xa3\xa1v\xb5\x96\xc8\xdbs\xf0{\xee\xf6\xe6" +
	"\xe7\xb3\x12E\x9e\xc4\xe4N\xbb\xd5\x12J\xa7\xfa\x90\xe0" +
	"=~r\xeb\xa6\xfd\xea\xe5\xdb\x9f(\xa5\x82y\xb5\x84" +
	"\xb2\xa4\x0e\x11\xbc\xab\xf9\xfd#\xd3\x0f\xee,\xae9P" +
	"\x04F\x102\x03\xf2@#0\x1a\x9a\x0ch4\xe1Y" +
	"\x85\xbc\x91\xc9\x0e\x16\x03f\xb3\xe3\x16l\xb3\xd95\xfa" +
	"r\xa6S\xfe4\xa5\x8c\x01k\xa0\xad3e\xf6\x99v" +
	"\xe6x\xca\xb0\x9a\xd2\x05\xcb\xacK\x1a\xb6\xc1\xf3\xcez" +
	"\x9a\xbbK\xbfJ\xdd]\xa6SS\xcc\xb9\x8e\xf8\x9f+" +
	"D\x0a\x88tc\x0b\x91\xe8\xe1\x10\xfd\x0c@X\x8e\xae" +
	"\x9b\x87\x88\xc4)\x0e\x91c\xd0\x19\xc2`Dz\xb6\x8b" +
	"H\xf4s\x08\x97A\xe7,,\xfd\xd2\x07[\x89D\x8e" +
	"C\x9ce\xd0\x0aE\x17Ab\x08\x12\xce\x0d\x98V:" +
	"ke\xa0\x12\x83J\xf0R\x85|>\xeb\xba&!\xed" +
	"\xff\x8b\xf4\x0d\xbb\xa6S\xa9\xd8\x90\x1c]\xa6S\xd4\xe4" +
	"@Je\xa0\xa0\x1c\xa8\x8aC\x84\x7fE\xda\xa0dI" +
	"\xc3\xd6\x8cU\x82\xab\xff\xd8MI@TquU\xb2" +
	"`M>\x1b\x8a\x8d\xf7\x8e\xe9-\xad\xc4\xf4z\x0d+" +
	"\xe9\x85\x7f\x13\xf4M\x0d\xc4\xf4\xa0\x16\x19\xb2\xb3\xae\x99" +
	"@\x8d\xa4H@(\x80w\xa2\xfe^\xb4\xf7S\xed\x0b" +
	"\"Z\xff4\xa5\xfd\xea\x92F\x8dm\xe4\x1dQ]\xd1" +
	"\xab\xbd\x8dH$8\xc4Q\x06\xddO@\xa7L\xc0a" +
	"\x0e\x91d\x00+\x07\xe0\x98,\xec\xe0\x10\xdd\x0c\xf1T" +
	"\xc1:\x9d\xcd\xa0\x9a\x18\xaa\xa5\xdd\xc6p\xae`\xa4}" +
	"\xad\xe3e\xbb\x01b\xc0\x06\xbc\xf5YK\xd2\x8b\xaa\x0a" +
	"\xeb\x0e\x89P\xc7!\xa2\xabX\x1be\x06\xb7s\x88]" +
	"k\xb8\"\x83E\xd3\x1e^\x93\x00\xe5o\x18\xf12\xc7" +
	"\x8a\x85\xfe\xd5\xff\x9d\x85\xfe\xeb\x06\xff\xa9\xfa\x83\x85I" +
	"\xe0G\x00\x00\x00\xff\xff\x8a\x11m\xac"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c7e14a3b8d9a2c1f,
		Nodes: []uint64{
			0x83aa2d97a293e68f,
			0x8b02f933f4bac737,
			0x9974b38894482732,
			0xb5726b5a01ec0103,
			0xce2ab50338f6a568,
			0xcec2209f6cf83c36,
			0xe0d4d972989bb7b6,
			0xefa0adbd7a396d92,
		},
		Compressed: true,
	})
}
