// Code generated by capnpc-go. DO NOT EDIT.

package trend

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type MassIndex capnp.Client

// MassIndex_TypeID is the unique identifier for the type MassIndex.
const MassIndex_TypeID = 0x882fa78c39659835

func (c MassIndex) Write(ctx context.Context, params func(MassIndex_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x882fa78c39659835,
			MethodID:      0,
			InterfaceName: "nomagique/financial/trend/mass_index.capnp:MassIndex",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MassIndex_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c MassIndex) Done(ctx context.Context, params func(MassIndex_done_Params) error) (MassIndex_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x882fa78c39659835,
			MethodID:      1,
			InterfaceName: "nomagique/financial/trend/mass_index.capnp:MassIndex",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(MassIndex_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return MassIndex_done_Results_Future{Future: ans.Future()}, release

}

func (c MassIndex) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c MassIndex) String() string {
	return "MassIndex(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c MassIndex) AddRef() MassIndex {
	return MassIndex(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c MassIndex) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c MassIndex) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c MassIndex) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (MassIndex) DecodeFromPtr(p capnp.Ptr) MassIndex {
	return MassIndex(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c MassIndex) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c MassIndex) IsSame(other MassIndex) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c MassIndex) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c MassIndex) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A MassIndex_Server is a MassIndex with a local implementation.
type MassIndex_Server interface {
	Write(context.Context, MassIndex_write) error

	Done(context.Context, MassIndex_done) error
}

// MassIndex_NewServer creates a new Server from an implementation of MassIndex_Server.
func MassIndex_NewServer(s MassIndex_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(MassIndex_Methods(nil, s), s, c)
}

// MassIndex_ServerToClient creates a new Client from an implementation of MassIndex_Server.
// The caller is responsible for calling Release on the returned Client.
func MassIndex_ServerToClient(s MassIndex_Server) MassIndex {
	return MassIndex(capnp.NewClient(MassIndex_NewServer(s)))
}

// MassIndex_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func MassIndex_Methods(methods []server.Method, s MassIndex_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x882fa78c39659835,
			MethodID:      0,
			InterfaceName: "nomagique/financial/trend/mass_index.capnp:MassIndex",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, MassIndex_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x882fa78c39659835,
			MethodID:      1,
			InterfaceName: "nomagique/financial/trend/mass_index.capnp:MassIndex",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, MassIndex_done{call})
		},
	})

	return methods
}

// MassIndex_write holds the state for a server call to MassIndex.write.
// See server.Call for documentation.
type MassIndex_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MassIndex_write) Args() MassIndex_write_Params {
	return MassIndex_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MassIndex_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// MassIndex_done holds the state for a server call to MassIndex.done.
// See server.Call for documentation.
type MassIndex_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c MassIndex_done) Args() MassIndex_done_Params {
	return MassIndex_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c MassIndex_done) AllocResults() (MassIndex_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return MassIndex_done_Results(r), err
}

// MassIndex_List is a list of MassIndex.
type MassIndex_List = capnp.CapList[MassIndex]

// NewMassIndex_List creates a new list of MassIndex.
func NewMassIndex_List(s *capnp.Segment, sz int32) (MassIndex_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[MassIndex](l), err
}

type MassIndex_write_Params capnp.Struct

// MassIndex_write_Params_TypeID is the unique identifier for the type MassIndex_write_Params.
const MassIndex_write_Params_TypeID = 0x8ed3de5f5cd9912e

func NewMassIndex_write_Params(s *capnp.Segment) (MassIndex_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return MassIndex_write_Params(st), err
}

func NewRootMassIndex_write_Params(s *capnp.Segment) (MassIndex_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return MassIndex_write_Params(st), err
}

func ReadRootMassIndex_write_Params(msg *capnp.Message) (MassIndex_write_Params, error) {
	root, err := msg.Root()
	return MassIndex_write_Params(root.Struct()), err
}

func (s MassIndex_write_Params) String() string {
	str, _ := text.Marshal(0x8ed3de5f5cd9912e, capnp.Struct(s))
	return str
}

func (s MassIndex_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MassIndex_write_Params) DecodeFromPtr(p capnp.Ptr) MassIndex_write_Params {
	return MassIndex_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MassIndex_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MassIndex_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MassIndex_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MassIndex_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MassIndex_write_Params) High() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s MassIndex_write_Params) SetHigh(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s MassIndex_write_Params) Low() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s MassIndex_write_Params) SetLow(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// MassIndex_write_Params_List is a list of MassIndex_write_Params.
type MassIndex_write_Params_List = capnp.StructList[MassIndex_write_Params]

// NewMassIndex_write_Params creates a new list of MassIndex_write_Params.
func NewMassIndex_write_Params_List(s *capnp.Segment, sz int32) (MassIndex_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[MassIndex_write_Params](l), err
}

// MassIndex_write_Params_Future is a wrapper for a MassIndex_write_Params promised by a client call.
type MassIndex_write_Params_Future struct{ *capnp.Future }

func (f MassIndex_write_Params_Future) Struct() (MassIndex_write_Params, error) {
	p, err := f.Future.Ptr()
	return MassIndex_write_Params(p.Struct()), err
}

type MassIndex_done_Params capnp.Struct

// MassIndex_done_Params_TypeID is the unique identifier for the type MassIndex_done_Params.
const MassIndex_done_Params_TypeID = 0xa8cff97132866373

func NewMassIndex_done_Params(s *capnp.Segment) (MassIndex_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MassIndex_done_Params(st), err
}

func NewRootMassIndex_done_Params(s *capnp.Segment) (MassIndex_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return MassIndex_done_Params(st), err
}

func ReadRootMassIndex_done_Params(msg *capnp.Message) (MassIndex_done_Params, error) {
	root, err := msg.Root()
	return MassIndex_done_Params(root.Struct()), err
}

func (s MassIndex_done_Params) String() string {
	str, _ := text.Marshal(0xa8cff97132866373, capnp.Struct(s))
	return str
}

func (s MassIndex_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MassIndex_done_Params) DecodeFromPtr(p capnp.Ptr) MassIndex_done_Params {
	return MassIndex_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MassIndex_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MassIndex_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MassIndex_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MassIndex_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// MassIndex_done_Params_List is a list of MassIndex_done_Params.
type MassIndex_done_Params_List = capnp.StructList[MassIndex_done_Params]

// NewMassIndex_done_Params creates a new list of MassIndex_done_Params.
func NewMassIndex_done_Params_List(s *capnp.Segment, sz int32) (MassIndex_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[MassIndex_done_Params](l), err
}

// MassIndex_done_Params_Future is a wrapper for a MassIndex_done_Params promised by a client call.
type MassIndex_done_Params_Future struct{ *capnp.Future }

func (f MassIndex_done_Params_Future) Struct() (MassIndex_done_Params, error) {
	p, err := f.Future.Ptr()
	return MassIndex_done_Params(p.Struct()), err
}

type MassIndex_done_Results capnp.Struct

// MassIndex_done_Results_TypeID is the unique identifier for the type MassIndex_done_Results.
const MassIndex_done_Results_TypeID = 0xd626039a3cdac3d3

func NewMassIndex_done_Results(s *capnp.Segment) (MassIndex_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return MassIndex_done_Results(st), err
}

func NewRootMassIndex_done_Results(s *capnp.Segment) (MassIndex_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return MassIndex_done_Results(st), err
}

func ReadRootMassIndex_done_Results(msg *capnp.Message) (MassIndex_done_Results, error) {
	root, err := msg.Root()
	return MassIndex_done_Results(root.Struct()), err
}

func (s MassIndex_done_Results) String() string {
	str, _ := text.Marshal(0xd626039a3cdac3d3, capnp.Struct(s))
	return str
}

func (s MassIndex_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (MassIndex_done_Results) DecodeFromPtr(p capnp.Ptr) MassIndex_done_Results {
	return MassIndex_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s MassIndex_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s MassIndex_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s MassIndex_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s MassIndex_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s MassIndex_done_Results) Result() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s MassIndex_done_Results) SetResult(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// MassIndex_done_Results_List is a list of MassIndex_done_Results.
type MassIndex_done_Results_List = capnp.StructList[MassIndex_done_Results]

// NewMassIndex_done_Results creates a new list of MassIndex_done_Results.
func NewMassIndex_done_Results_List(s *capnp.Segment, sz int32) (MassIndex_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[MassIndex_done_Results](l), err
}

// MassIndex_done_Results_Future is a wrapper for a MassIndex_done_Results promised by a client call.
type MassIndex_done_Results_Future struct{ *capnp.Future }

func (f MassIndex_done_Results_Future) Struct() (MassIndex_done_Results, error) {
	p, err := f.Future.Ptr()
	return MassIndex_done_Results(p.Struct()), err
}
