version: 1
playbooks:
    - name: trend
      regime: bullish
      policy: standard
      deny:
        - category: coiled_compression
          condition: '>'
          value: 0.8
          action: deny
        - category: robust_liquidity
          condition: '>'
          value: 205.85000000000002
          action: deny
      entry:
        - metric: score_cost_ratio
          condition: <
          value: 2
          action: deny
        - branches:
            - branches:
                - branches:
                    - category: dense_neutrality
                      condition: '>'
                      value: 0.8
                      action: enter
                  category: vertical_ignition
                  condition: '>'
                  value: 5.7
                - category: dense_neutrality
                  condition: '>'
                  value: 35.9
                  action: enter
                - branches:
                    - category: dense_neutrality
                      condition: '>'
                      value: 0.9
                      action: enter
                  category: organic
                  condition: '>'
                  value: 1
              metric: in_play
              condition: '>='
              value: 1
          metric: score_cost_ratio
          condition: '>='
          value: 2
      exit:
        - category: dense_neutrality
          condition: '>'
          value: 0.8
          action: take_profit
        - category: coiled_compression
          condition: '>'
          value: 3.25
          action: take_profit
        - category: organic
          condition: '>'
          value: 1
          action: take_profit
        - category: robust_liquidity
          condition: '>'
          value: 60.95
          action: stop_loss
        - category: dense_neutrality
          condition: '>'
          value: 0.9
          action: take_profit
        - category: extreme_scarcity
          condition: '>'
          value: 257.3
          action: stop_loss
    - name: drive
      regime: trending
      policy: drive
      deny:
        - category: dense_neutrality
          condition: '>'
          value: 0.6000000000000001
          action: deny
        - category: dense_neutrality
          condition: '>'
          value: 0.8
          action: deny
        - category: risk_on_surge
          condition: '>'
          value: 1.1500000000000001
          action: deny
      entry:
        - metric: score_cost_ratio
          condition: <
          value: 1.4000000000000001
          action: deny
        - branches:
            - category: extreme_scarcity
              condition: '>'
              value: 691.6
              action: enter
          metric: score_cost_ratio
          condition: '>='
          value: 1.4000000000000001
      exit:
        - category: dense_neutrality
          condition: '>'
          value: 0.8
          action: take_profit
        - category: dense_neutrality
          condition: '>'
          value: 0.6000000000000001
          action: stop_loss
    - name: leadlag
      regime: trending
      policy: standard
      deny:
      entry:
        - metric: score_cost_ratio
          condition: <
          value: 2
          action: deny
        - branches:
            - category: robust_liquidity
              condition: '>'
              value: 126.15
              action: enter
            - branches:
                - branches:
                    - branches:
                        - category: coiled_compression
                          condition: '>'
                          value: 1.6500000000000001
                          action: enter
                      category: robust_liquidity
                      condition: '>'
                      value: 126.15
                  category: dense_neutrality
                  condition: '>'
                  value: 0.9
              category: extreme_scarcity
              condition: '>'
              value: 257.3
            - branches:
                - branches:
                    - branches:
                        - category: organic
                          condition: '>'
                          value: 199.60000000000002
                          action: enter
                      category: extreme_scarcity
                      condition: '>'
                      value: 691.6
                  category: robust_liquidity
                  condition: '>'
                  value: 205.85000000000002
              category: dense_neutrality
              condition: '>'
              value: 0.9
          metric: score_cost_ratio
          condition: '>='
          value: 2
      exit:
        - category: organic
          condition: '>'
          value: 1
          action: short
        - category: robust_liquidity
          condition: '>'
          value: 205.85000000000002
          action: take_profit
        - category: dense_neutrality
          condition: '>'
          value: 35.9
          action: take_profit
        - category: dense_neutrality
          condition: '>'
          value: 0.9
          action: take_profit
    - name: scarcity
      regime: choppy
      policy: standard
      deny:
        - category: mechanical_collapse
          condition: '>'
          value: 0.55
          action: deny
        - category: stochastic_balance
          condition: '>'
          value: 5.300000000000001
          action: deny
      entry:
        - metric: score_cost_ratio
          condition: <
          value: 1.5
          action: deny
        - branches:
            - branches:
                - branches:
                    - branches:
                        - category: coiled_compression
                          condition: '>'
                          value: 3.25
                          action: enter
                      category: robust_liquidity
                      condition: '>'
                      value: 205.85000000000002
                  category: organic
                  condition: '>'
                  value: 1
              category: dense_neutrality
              condition: '>'
              value: 0.8
            - branches:
                - category: active_reversal
                  condition: '>'
                  value: 0.55
                  action: enter
              category: dense_neutrality
              condition: '>'
              value: 35.9
          metric: score_cost_ratio
          condition: '>='
          value: 1.5
      exit:
        - category: dense_neutrality
          condition: '>'
          value: 0.9
          action: take_profit
        - category: dense_neutrality
          condition: '>'
          value: 0.9
          action: take_profit
    - name: pump
      regime: trending
      policy: pump
      deny:
        - category: stochastic_balance
          condition: '>'
          value: 4
          action: deny
      entry:
        - metric: score_cost_ratio
          condition: <
          value: 2.5
          action: deny
        - branches:
            - branches:
                - branches:
                    - branches:
                        - category: vertical_ignition
                          condition: '>'
                          value: 2.25
                          action: enter
                      category: thermal_exhaustion
                      condition: '>'
                      value: 0.65
                  category: robust_liquidity
                  condition: '>'
                  value: 126.15
              category: dense_neutrality
              condition: '>'
              value: 35.9
          metric: score_cost_ratio
          condition: '>='
          value: 2.5
      exit:
        - category: dense_neutrality
          condition: '>'
          value: 35.9
          action: take_profit
        - category: extreme_scarcity
          condition: '>'
          value: 257.3
          action: stop_loss
        - category: dense_neutrality
          condition: '>'
          value: 0.6000000000000001
          action: take_profit
        - category: dense_neutrality
          condition: '>'
          value: 0.9
          action: take_profit
