// Code generated by capnpc-go. DO NOT EDIT.

package strategy

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type SharpeRatio capnp.Client

// SharpeRatio_TypeID is the unique identifier for the type SharpeRatio.
const SharpeRatio_TypeID = 0x9816474b6d8e18cd

func (c SharpeRatio) Write(ctx context.Context, params func(SharpeRatio_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x9816474b6d8e18cd,
			MethodID:      0,
			InterfaceName: "nomagique/financial/strategy/sharpe_ratio.capnp:SharpeRatio",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SharpeRatio_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c SharpeRatio) Done(ctx context.Context, params func(SharpeRatio_done_Params) error) (SharpeRatio_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x9816474b6d8e18cd,
			MethodID:      1,
			InterfaceName: "nomagique/financial/strategy/sharpe_ratio.capnp:SharpeRatio",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(SharpeRatio_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return SharpeRatio_done_Results_Future{Future: ans.Future()}, release

}

func (c SharpeRatio) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c SharpeRatio) String() string {
	return "SharpeRatio(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c SharpeRatio) AddRef() SharpeRatio {
	return SharpeRatio(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c SharpeRatio) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c SharpeRatio) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c SharpeRatio) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (SharpeRatio) DecodeFromPtr(p capnp.Ptr) SharpeRatio {
	return SharpeRatio(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c SharpeRatio) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c SharpeRatio) IsSame(other SharpeRatio) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c SharpeRatio) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c SharpeRatio) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A SharpeRatio_Server is a SharpeRatio with a local implementation.
type SharpeRatio_Server interface {
	Write(context.Context, SharpeRatio_write) error

	Done(context.Context, SharpeRatio_done) error
}

// SharpeRatio_NewServer creates a new Server from an implementation of SharpeRatio_Server.
func SharpeRatio_NewServer(s SharpeRatio_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(SharpeRatio_Methods(nil, s), s, c)
}

// SharpeRatio_ServerToClient creates a new Client from an implementation of SharpeRatio_Server.
// The caller is responsible for calling Release on the returned Client.
func SharpeRatio_ServerToClient(s SharpeRatio_Server) SharpeRatio {
	return SharpeRatio(capnp.NewClient(SharpeRatio_NewServer(s)))
}

// SharpeRatio_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func SharpeRatio_Methods(methods []server.Method, s SharpeRatio_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x9816474b6d8e18cd,
			MethodID:      0,
			InterfaceName: "nomagique/financial/strategy/sharpe_ratio.capnp:SharpeRatio",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, SharpeRatio_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x9816474b6d8e18cd,
			MethodID:      1,
			InterfaceName: "nomagique/financial/strategy/sharpe_ratio.capnp:SharpeRatio",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, SharpeRatio_done{call})
		},
	})

	return methods
}

// SharpeRatio_write holds the state for a server call to SharpeRatio.write.
// See server.Call for documentation.
type SharpeRatio_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SharpeRatio_write) Args() SharpeRatio_write_Params {
	return SharpeRatio_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SharpeRatio_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// SharpeRatio_done holds the state for a server call to SharpeRatio.done.
// See server.Call for documentation.
type SharpeRatio_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c SharpeRatio_done) Args() SharpeRatio_done_Params {
	return SharpeRatio_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c SharpeRatio_done) AllocResults() (SharpeRatio_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return SharpeRatio_done_Results(r), err
}

// SharpeRatio_List is a list of SharpeRatio.
type SharpeRatio_List = capnp.CapList[SharpeRatio]

// NewSharpeRatio_List creates a new list of SharpeRatio.
func NewSharpeRatio_List(s *capnp.Segment, sz int32) (SharpeRatio_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[SharpeRatio](l), err
}

type SharpeRatio_write_Params capnp.Struct

// SharpeRatio_write_Params_TypeID is the unique identifier for the type SharpeRatio_write_Params.
const SharpeRatio_write_Params_TypeID = 0x880516fd0bf4fa39

func NewSharpeRatio_write_Params(s *capnp.Segment) (SharpeRatio_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return SharpeRatio_write_Params(st), err
}

func NewRootSharpeRatio_write_Params(s *capnp.Segment) (SharpeRatio_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return SharpeRatio_write_Params(st), err
}

func ReadRootSharpeRatio_write_Params(msg *capnp.Message) (SharpeRatio_write_Params, error) {
	root, err := msg.Root()
	return SharpeRatio_write_Params(root.Struct()), err
}

func (s SharpeRatio_write_Params) String() string {
	str, _ := text.Marshal(0x880516fd0bf4fa39, capnp.Struct(s))
	return str
}

func (s SharpeRatio_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SharpeRatio_write_Params) DecodeFromPtr(p capnp.Ptr) SharpeRatio_write_Params {
	return SharpeRatio_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SharpeRatio_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SharpeRatio_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SharpeRatio_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SharpeRatio_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SharpeRatio_write_Params) Outcome() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s SharpeRatio_write_Params) SetOutcome(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// SharpeRatio_write_Params_List is a list of SharpeRatio_write_Params.
type SharpeRatio_write_Params_List = capnp.StructList[SharpeRatio_write_Params]

// NewSharpeRatio_write_Params creates a new list of SharpeRatio_write_Params.
func NewSharpeRatio_write_Params_List(s *capnp.Segment, sz int32) (SharpeRatio_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[SharpeRatio_write_Params](l), err
}

// SharpeRatio_write_Params_Future is a wrapper for a SharpeRatio_write_Params promised by a client call.
type SharpeRatio_write_Params_Future struct{ *capnp.Future }

func (f SharpeRatio_write_Params_Future) Struct() (SharpeRatio_write_Params, error) {
	p, err := f.Future.Ptr()
	return SharpeRatio_write_Params(p.Struct()), err
}

type SharpeRatio_done_Params capnp.Struct

// SharpeRatio_done_Params_TypeID is the unique identifier for the type SharpeRatio_done_Params.
const SharpeRatio_done_Params_TypeID = 0x9b645c6f675e0485

func NewSharpeRatio_done_Params(s *capnp.Segment) (SharpeRatio_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SharpeRatio_done_Params(st), err
}

func NewRootSharpeRatio_done_Params(s *capnp.Segment) (SharpeRatio_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return SharpeRatio_done_Params(st), err
}

func ReadRootSharpeRatio_done_Params(msg *capnp.Message) (SharpeRatio_done_Params, error) {
	root, err := msg.Root()
	return SharpeRatio_done_Params(root.Struct()), err
}

func (s SharpeRatio_done_Params) String() string {
	str, _ := text.Marshal(0x9b645c6f675e0485, capnp.Struct(s))
	return str
}

func (s SharpeRatio_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SharpeRatio_done_Params) DecodeFromPtr(p capnp.Ptr) SharpeRatio_done_Params {
	return SharpeRatio_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SharpeRatio_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SharpeRatio_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SharpeRatio_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SharpeRatio_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// SharpeRatio_done_Params_List is a list of SharpeRatio_done_Params.
type SharpeRatio_done_Params_List = capnp.StructList[SharpeRatio_done_Params]

// NewSharpeRatio_done_Params creates a new list of SharpeRatio_done_Params.
func NewSharpeRatio_done_Params_List(s *capnp.Segment, sz int32) (SharpeRatio_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[SharpeRatio_done_Params](l), err
}

// SharpeRatio_done_Params_Future is a wrapper for a SharpeRatio_done_Params promised by a client call.
type SharpeRatio_done_Params_Future struct{ *capnp.Future }

func (f SharpeRatio_done_Params_Future) Struct() (SharpeRatio_done_Params, error) {
	p, err := f.Future.Ptr()
	return SharpeRatio_done_Params(p.Struct()), err
}

type SharpeRatio_done_Results capnp.Struct

// SharpeRatio_done_Results_TypeID is the unique identifier for the type SharpeRatio_done_Results.
const SharpeRatio_done_Results_TypeID = 0xf84dff653b2b6382

func NewSharpeRatio_done_Results(s *capnp.Segment) (SharpeRatio_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return SharpeRatio_done_Results(st), err
}

func NewRootSharpeRatio_done_Results(s *capnp.Segment) (SharpeRatio_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return SharpeRatio_done_Results(st), err
}

func ReadRootSharpeRatio_done_Results(msg *capnp.Message) (SharpeRatio_done_Results, error) {
	root, err := msg.Root()
	return SharpeRatio_done_Results(root.Struct()), err
}

func (s SharpeRatio_done_Results) String() string {
	str, _ := text.Marshal(0xf84dff653b2b6382, capnp.Struct(s))
	return str
}

func (s SharpeRatio_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SharpeRatio_done_Results) DecodeFromPtr(p capnp.Ptr) SharpeRatio_done_Results {
	return SharpeRatio_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SharpeRatio_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SharpeRatio_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SharpeRatio_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SharpeRatio_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SharpeRatio_done_Results) Ratio() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s SharpeRatio_done_Results) SetRatio(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// SharpeRatio_done_Results_List is a list of SharpeRatio_done_Results.
type SharpeRatio_done_Results_List = capnp.StructList[SharpeRatio_done_Results]

// NewSharpeRatio_done_Results creates a new list of SharpeRatio_done_Results.
func NewSharpeRatio_done_Results_List(s *capnp.Segment, sz int32) (SharpeRatio_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[SharpeRatio_done_Results](l), err
}

// SharpeRatio_done_Results_Future is a wrapper for a SharpeRatio_done_Results promised by a client call.
type SharpeRatio_done_Results_Future struct{ *capnp.Future }

func (f SharpeRatio_done_Results_Future) Struct() (SharpeRatio_done_Results, error) {
	p, err := f.Future.Ptr()
	return SharpeRatio_done_Results(p.Struct()), err
}
