// Code generated by tools/nomagiquecatalog. DO NOT EDIT.

package compiler

import (
	"github.com/theapemachine/symm/nomagique/types"
	algo "github.com/theapemachine/symm/nomagique/algo"
	arithmetic "github.com/theapemachine/symm/nomagique/arithmetic"
	associative "github.com/theapemachine/symm/nomagique/learning/associative"
	calculus "github.com/theapemachine/symm/nomagique/calculus"
	cognition "github.com/theapemachine/symm/nomagique/cognition"
	data "github.com/theapemachine/symm/nomagique/data"
	geometry "github.com/theapemachine/symm/nomagique/geometry"
	hawkes "github.com/theapemachine/symm/nomagique/statistic/hawkes"
	probability "github.com/theapemachine/symm/nomagique/probability"
	statistic "github.com/theapemachine/symm/nomagique/statistic"
	temporal "github.com/theapemachine/symm/nomagique/temporal"
)

/*
Registry maps the string types from the JSON graph to factory functions
that instantiate their `Value[any, any]` wrappers. 
*/
var Registry = map[string]func() types.Value[any, any]{
	"algo.HayashiYoshida": func() types.Value[any, any] {
		closure := algo.NewHayashiYoshida()
		return func(in any) any {
			return closure(in.([2][2]int64))
		}
	},
	"algo.RLSPrediction": func() types.Value[any, any] {
		closure := algo.NewRLSPrediction()
		return func(in any) any {
			return closure(in.(algo.RLSState))
		}
	},
	"algo.RLSUpdate": func() types.Value[any, any] {
		closure := algo.NewRLSUpdate()
		return func(in any) any {
			return closure(in.(algo.RLSObservation))
		}
	},
	"arithmetic.Add": func() types.Value[any, any] {
		closure := arithmetic.NewAdd()
		return func(in any) any {
			return closure(in.([2]float64))
		}
	},
	"arithmetic.AddScaledVec": func() types.Value[any, any] {
		closure := arithmetic.NewAddScaledVec()
		return func(in any) any {
			return closure(in.([3][]float64))
		}
	},
	"arithmetic.AddVec": func() types.Value[any, any] {
		closure := arithmetic.NewAddVec()
		return func(in any) any {
			return closure(in.([2][]float64))
		}
	},
	"arithmetic.Divide": func() types.Value[any, any] {
		closure := arithmetic.NewDivide()
		return func(in any) any {
			return closure(in.([2]float64))
		}
	},
	"arithmetic.DotProduct": func() types.Value[any, any] {
		closure := arithmetic.NewDotProduct()
		return func(in any) any {
			return closure(in.([2][]float64))
		}
	},
	"arithmetic.Exp": func() types.Value[any, any] {
		closure := arithmetic.NewExp()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"arithmetic.Identity": func() types.Value[any, any] {
		closure := arithmetic.NewIdentity()
		return func(in any) any {
			return closure(in.(int))
		}
	},
	"arithmetic.MatVecMul": func() types.Value[any, any] {
		closure := arithmetic.NewMatVecMul()
		return func(in any) any {
			return closure(in.([2]any))
		}
	},
	"arithmetic.MulVec": func() types.Value[any, any] {
		closure := arithmetic.NewMulVec()
		return func(in any) any {
			return closure(in.([2][]float64))
		}
	},
	"arithmetic.Multiply": func() types.Value[any, any] {
		closure := arithmetic.NewMultiply()
		return func(in any) any {
			return closure(in.([2]float64))
		}
	},
	"arithmetic.OuterProduct": func() types.Value[any, any] {
		closure := arithmetic.NewOuterProduct()
		return func(in any) any {
			return closure(in.([2][]float64))
		}
	},
	"arithmetic.ScaleVec": func() types.Value[any, any] {
		closure := arithmetic.NewScaleVec()
		return func(in any) any {
			return closure(in.([2][]float64))
		}
	},
	"arithmetic.SpectralRadius2": func() types.Value[any, any] {
		closure := arithmetic.NewSpectralRadius2()
		return func(in any) any {
			return closure(in.([2][2]float64))
		}
	},
	"arithmetic.SquareRoot": func() types.Value[any, any] {
		closure := arithmetic.NewSquareRoot()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"arithmetic.SubVec": func() types.Value[any, any] {
		closure := arithmetic.NewSubVec()
		return func(in any) any {
			return closure(in.([2][]float64))
		}
	},
	"arithmetic.Subtract": func() types.Value[any, any] {
		closure := arithmetic.NewSubtract()
		return func(in any) any {
			return closure(in.([2]float64))
		}
	},
	"arithmetic.Sum": func() types.Value[any, any] {
		closure := arithmetic.NewSum()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"arithmetic.Transpose": func() types.Value[any, any] {
		closure := arithmetic.NewTranspose()
		return func(in any) any {
			return closure(in.([][]float64))
		}
	},
	"arithmetic.VecPrecisionWeight": func() types.Value[any, any] {
		closure := arithmetic.NewVecPrecisionWeight()
		return func(in any) any {
			return closure(in.([2][]float64))
		}
	},
	"associative.Grid": func() types.Value[any, any] {
		closure := associative.NewGrid()
		return func(in any) any {
			return closure(in.([]float64))
		}
	},
	"calculus.Absolute": func() types.Value[any, any] {
		closure := calculus.NewAbsolute()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Atanh": func() types.Value[any, any] {
		closure := calculus.NewAtanh()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Erfc": func() types.Value[any, any] {
		closure := calculus.NewErfc()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Exp": func() types.Value[any, any] {
		closure := calculus.NewExp()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Floor": func() types.Value[any, any] {
		closure := calculus.NewFloor()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Log": func() types.Value[any, any] {
		closure := calculus.NewLog()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Maximum": func() types.Value[any, any] {
		closure := calculus.NewMaximum()
		return func(in any) any {
			return closure(in.([2]float64))
		}
	},
	"calculus.Minimum": func() types.Value[any, any] {
		closure := calculus.NewMinimum()
		return func(in any) any {
			return closure(in.([2]float64))
		}
	},
	"calculus.Negate": func() types.Value[any, any] {
		closure := calculus.NewNegate()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Polarize": func() types.Value[any, any] {
		closure := calculus.NewPolarize()
		return func(in any) any {
			return closure(in.([2]float64))
		}
	},
	"calculus.Reciprocal": func() types.Value[any, any] {
		closure := calculus.NewReciprocal()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.RelativeChange": func() types.Value[any, any] {
		closure := calculus.NewRelativeChange()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.SecondDifference": func() types.Value[any, any] {
		closure := calculus.NewSecondDifference()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Sign": func() types.Value[any, any] {
		closure := calculus.NewSign()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Sqrt": func() types.Value[any, any] {
		closure := calculus.NewSqrt()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Square": func() types.Value[any, any] {
		closure := calculus.NewSquare()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"calculus.Tanh": func() types.Value[any, any] {
		closure := calculus.NewTanh()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"cognition.Associate": func() types.Value[any, any] {
		closure := cognition.NewAssociate()
		return func(in any) any {
			return closure(in.([]byte))
		}
	},
	"cognition.Classification": func() types.Value[any, any] {
		closure := cognition.NewClassification()
		return func(in any) any {
			return closure(in.(func(func([]byte, float64, uint64) bool)))
		}
	},
	"cognition.Pack": func() types.Value[any, any] {
		closure := cognition.NewPack()
		return func(in any) any {
			return closure(in.([3]uint64))
		}
	},
	"cognition.Weight": func() types.Value[any, any] {
		closure := cognition.NewWeight()
		return func(in any) any {
			return closure(in.([]byte))
		}
	},
	"data.Extract": func() types.Value[any, any] {
		closure := data.NewExtract("value")
		return func(in any) any {
			return closure(in.(map[string]any))
		}
	},
	"data.Quality": func() types.Value[any, any] {
		closure := data.NewQuality()
		return func(in any) any {
			return closure(in.(data.QualityFacts))
		}
	},
	"geometry.Intersection": func() types.Value[any, any] {
		closure := geometry.NewIntersection()
		return func(in any) any {
			return closure(in.([2][2]int64))
		}
	},
	"geometry.Normalize": func() types.Value[any, any] {
		closure := geometry.NewNormalize()
		return func(in any) any {
			return closure(in.(geometry.PhaseDial))
		}
	},
	"geometry.Overlap": func() types.Value[any, any] {
		closure := geometry.NewOverlap()
		return func(in any) any {
			return closure(in.(geometry.OverlapPair))
		}
	},
	"geometry.PhasePath": func() types.Value[any, any] {
		closure := geometry.NewPhasePath()
		return func(in any) any {
			return closure(in.(int))
		}
	},
	"hawkes.ArrivalRate": func() types.Value[any, any] {
		closure := hawkes.NewArrivalRate()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.Assemble": func() types.Value[any, any] {
		closure := hawkes.NewAssemble()
		return func(in any) any {
			return closure(in.(map[string]any))
		}
	},
	"hawkes.BuyCount": func() types.Value[any, any] {
		closure := hawkes.NewBuyCount()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.BuyFraction": func() types.Value[any, any] {
		closure := hawkes.NewBuyFraction()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.BuyIntensity": func() types.Value[any, any] {
		closure := hawkes.NewBuyIntensity()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.BuyRate": func() types.Value[any, any] {
		closure := hawkes.NewBuyRate()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.ConditionalIntensity": func() types.Value[any, any] {
		closure := hawkes.NewConditionalIntensity()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.EventCount": func() types.Value[any, any] {
		closure := hawkes.NewEventCount()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.Process": func() types.Value[any, any] {
		closure := hawkes.NewProcess()
		return func(in any) any {
			return closure(in.(hawkes.Event))
		}
	},
	"hawkes.SellCount": func() types.Value[any, any] {
		closure := hawkes.NewSellCount()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.SellFraction": func() types.Value[any, any] {
		closure := hawkes.NewSellFraction()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.SellIntensity": func() types.Value[any, any] {
		closure := hawkes.NewSellIntensity()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.SellRate": func() types.Value[any, any] {
		closure := hawkes.NewSellRate()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"hawkes.SpectralRadius": func() types.Value[any, any] {
		closure := hawkes.NewSpectralRadius()
		return func(in any) any {
			return closure(in.(hawkes.Reading))
		}
	},
	"probability.Ambiguity": func() types.Value[any, any] {
		closure := probability.NewAmbiguity()
		return func(in any) any {
			return closure(in.([]float64))
		}
	},
	"probability.Argmax": func() types.Value[any, any] {
		closure := probability.NewArgmax()
		return func(in any) any {
			return closure(in.([]float64))
		}
	},
	"probability.Concentration": func() types.Value[any, any] {
		closure := probability.NewConcentration()
		return func(in any) any {
			return closure(in.(probability.ShapeInput))
		}
	},
	"probability.ConcentrationPoints": func() types.Value[any, any] {
		closure := probability.NewConcentrationPoints()
		return func(in any) any {
			return closure(in.(probability.PointsInput))
		}
	},
	"probability.Distribution": func() types.Value[any, any] {
		closure := probability.NewDistribution()
		return func(in any) any {
			return closure(in.([]float64))
		}
	},
	"probability.DistributionEntropy": func() types.Value[any, any] {
		closure := probability.NewDistributionEntropy()
		return func(in any) any {
			return closure(in.(probability.ShapeInput))
		}
	},
	"probability.DistributionNormalize": func() types.Value[any, any] {
		closure := probability.NewDistributionNormalize()
		return func(in any) any {
			return closure(in.(probability.WeightsInput))
		}
	},
	"probability.Entropy": func() types.Value[any, any] {
		closure := probability.NewEntropy()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"probability.EntropyPoints": func() types.Value[any, any] {
		closure := probability.NewEntropyPoints()
		return func(in any) any {
			return closure(in.(probability.PointsInput))
		}
	},
	"probability.Geomean": func() types.Value[any, any] {
		closure := probability.NewGeomean()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"probability.GeometricMean": func() types.Value[any, any] {
		closure := probability.NewGeometricMean()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"probability.KolmogorovSmirnov": func() types.Value[any, any] {
		closure := probability.NewKolmogorovSmirnov()
		return func(in any) any {
			return closure(in.(probability.DistanceInput))
		}
	},
	"probability.KolmogorovSmirnovPairs": func() types.Value[any, any] {
		closure := probability.NewKolmogorovSmirnovPairs()
		return func(in any) any {
			return closure(in.(probability.PairsInput))
		}
	},
	"probability.Normalize": func() types.Value[any, any] {
		closure := probability.NewNormalize()
		return func(in any) any {
			return closure(in.([]float64))
		}
	},
	"probability.ShannonAmbiguity": func() types.Value[any, any] {
		closure := probability.NewShannonAmbiguity()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"probability.Softmax": func() types.Value[any, any] {
		closure := probability.NewSoftmax()
		return func(in any) any {
			return closure(in.([]float64))
		}
	},
	"probability.SortedPositions": func() types.Value[any, any] {
		closure := probability.NewSortedPositions()
		return func(in any) any {
			return closure(in.(probability.SortedInput))
		}
	},
	"probability.Wasserstein1": func() types.Value[any, any] {
		closure := probability.NewWasserstein1()
		return func(in any) any {
			return closure(in.(probability.DistanceInput))
		}
	},
	"probability.Wasserstein1Pairs": func() types.Value[any, any] {
		closure := probability.NewWasserstein1Pairs()
		return func(in any) any {
			return closure(in.(probability.PairsInput))
		}
	},
	"statistic.CausalMean": func() types.Value[any, any] {
		closure := statistic.NewCausalMean()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"statistic.CausalVariance": func() types.Value[any, any] {
		closure := statistic.NewCausalVariance()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"statistic.Mean": func() types.Value[any, any] {
		closure := statistic.NewMean()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"statistic.ResidualBaseline": func() types.Value[any, any] {
		closure := statistic.NewResidualBaseline()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"statistic.ResidualDivergence": func() types.Value[any, any] {
		closure := statistic.NewResidualDivergence()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"statistic.Variance": func() types.Value[any, any] {
		closure := statistic.NewVariance()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"statistic.ZScore": func() types.Value[any, any] {
		closure := statistic.NewZScore()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"temporal.Elapsed": func() types.Value[any, any] {
		closure := temporal.NewElapsed()
		return func(in any) any {
			return closure(in.(int64))
		}
	},
	"temporal.LogReturns": func() types.Value[any, any] {
		closure := temporal.NewLogReturns()
		return func(in any) any {
			return closure(in.(float64))
		}
	},
	"temporal.Transition": func() types.Value[any, any] {
		closure := temporal.NewTransition()
		return func(in any) any {
			return closure(in.([]byte))
		}
	},
	"temporal.Velocity": func() types.Value[any, any] {
		closure := temporal.NewVelocity()
		return func(in any) any {
			return closure(in.([2]float64))
		}
	},
}

/*
Primitives returns a UI-compatible definition list of available primitive nodes.
*/
func Primitives() (any, error) {
	res := make(map[string]map[string]any)
	for k := range Registry {
		res[k] = map[string]any{
			"type":    k,
			"label":   k,
			"inputs":  []any{},
			"outputs": []any{},
		}
	}
	return res, nil
}
