// Code generated by capnpc-go. DO NOT EDIT.

package hawkes

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type Compensator capnp.Client

// Compensator_TypeID is the unique identifier for the type Compensator.
const Compensator_TypeID = 0xbe64b0a9d69d4d30

func (c Compensator) Write(ctx context.Context, params func(Compensator_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xbe64b0a9d69d4d30,
			MethodID:      0,
			InterfaceName: "nomagique/statistic/hawkes/compensator.capnp:Compensator",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 24, PointerCount: 3}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Compensator_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Compensator) Done(ctx context.Context, params func(Compensator_done_Params) error) (Compensator_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xbe64b0a9d69d4d30,
			MethodID:      1,
			InterfaceName: "nomagique/statistic/hawkes/compensator.capnp:Compensator",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Compensator_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Compensator_done_Results_Future{Future: ans.Future()}, release

}

func (c Compensator) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Compensator) String() string {
	return "Compensator(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Compensator) AddRef() Compensator {
	return Compensator(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Compensator) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Compensator) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Compensator) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Compensator) DecodeFromPtr(p capnp.Ptr) Compensator {
	return Compensator(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Compensator) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Compensator) IsSame(other Compensator) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Compensator) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Compensator) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Compensator_Server is a Compensator with a local implementation.
type Compensator_Server interface {
	Write(context.Context, Compensator_write) error

	Done(context.Context, Compensator_done) error
}

// Compensator_NewServer creates a new Server from an implementation of Compensator_Server.
func Compensator_NewServer(s Compensator_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Compensator_Methods(nil, s), s, c)
}

// Compensator_ServerToClient creates a new Client from an implementation of Compensator_Server.
// The caller is responsible for calling Release on the returned Client.
func Compensator_ServerToClient(s Compensator_Server) Compensator {
	return Compensator(capnp.NewClient(Compensator_NewServer(s)))
}

// Compensator_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Compensator_Methods(methods []server.Method, s Compensator_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xbe64b0a9d69d4d30,
			MethodID:      0,
			InterfaceName: "nomagique/statistic/hawkes/compensator.capnp:Compensator",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Compensator_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xbe64b0a9d69d4d30,
			MethodID:      1,
			InterfaceName: "nomagique/statistic/hawkes/compensator.capnp:Compensator",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Compensator_done{call})
		},
	})

	return methods
}

// Compensator_write holds the state for a server call to Compensator.write.
// See server.Call for documentation.
type Compensator_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Compensator_write) Args() Compensator_write_Params {
	return Compensator_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Compensator_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Compensator_done holds the state for a server call to Compensator.done.
// See server.Call for documentation.
type Compensator_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Compensator_done) Args() Compensator_done_Params {
	return Compensator_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Compensator_done) AllocResults() (Compensator_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Compensator_done_Results(r), err
}

// Compensator_List is a list of Compensator.
type Compensator_List = capnp.CapList[Compensator]

// NewCompensator_List creates a new list of Compensator.
func NewCompensator_List(s *capnp.Segment, sz int32) (Compensator_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Compensator](l), err
}

type Compensator_write_Params capnp.Struct

// Compensator_write_Params_TypeID is the unique identifier for the type Compensator_write_Params.
const Compensator_write_Params_TypeID = 0xa01ccf7f98c13a1f

func NewCompensator_write_Params(s *capnp.Segment) (Compensator_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return Compensator_write_Params(st), err
}

func NewRootCompensator_write_Params(s *capnp.Segment) (Compensator_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return Compensator_write_Params(st), err
}

func ReadRootCompensator_write_Params(msg *capnp.Message) (Compensator_write_Params, error) {
	root, err := msg.Root()
	return Compensator_write_Params(root.Struct()), err
}

func (s Compensator_write_Params) String() string {
	str, _ := text.Marshal(0xa01ccf7f98c13a1f, capnp.Struct(s))
	return str
}

func (s Compensator_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Compensator_write_Params) DecodeFromPtr(p capnp.Ptr) Compensator_write_Params {
	return Compensator_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Compensator_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Compensator_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Compensator_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Compensator_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Compensator_write_Params) Baseline() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.Float64List(p.List()), err
}

func (s Compensator_write_Params) HasBaseline() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Compensator_write_Params) SetBaseline(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewBaseline sets the baseline field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Compensator_write_Params) NewBaseline(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Compensator_write_Params) Excitation() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.Float64List(p.List()), err
}

func (s Compensator_write_Params) HasExcitation() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Compensator_write_Params) SetExcitation(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewExcitation sets the excitation field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Compensator_write_Params) NewExcitation(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Compensator_write_Params) Support() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.Float64List(p.List()), err
}

func (s Compensator_write_Params) HasSupport() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Compensator_write_Params) SetSupport(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewSupport sets the support field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Compensator_write_Params) NewSupport(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s Compensator_write_Params) Span() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Compensator_write_Params) SetSpan(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Compensator_write_Params) Decay() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Compensator_write_Params) SetDecay(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Compensator_write_Params) Dimension() int32 {
	return int32(capnp.Struct(s).Uint32(16))
}

func (s Compensator_write_Params) SetDimension(v int32) {
	capnp.Struct(s).SetUint32(16, uint32(v))
}

// Compensator_write_Params_List is a list of Compensator_write_Params.
type Compensator_write_Params_List = capnp.StructList[Compensator_write_Params]

// NewCompensator_write_Params creates a new list of Compensator_write_Params.
func NewCompensator_write_Params_List(s *capnp.Segment, sz int32) (Compensator_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3}, sz)
	return capnp.StructList[Compensator_write_Params](l), err
}

// Compensator_write_Params_Future is a wrapper for a Compensator_write_Params promised by a client call.
type Compensator_write_Params_Future struct{ *capnp.Future }

func (f Compensator_write_Params_Future) Struct() (Compensator_write_Params, error) {
	p, err := f.Future.Ptr()
	return Compensator_write_Params(p.Struct()), err
}

type Compensator_done_Params capnp.Struct

// Compensator_done_Params_TypeID is the unique identifier for the type Compensator_done_Params.
const Compensator_done_Params_TypeID = 0xfe8b52379f3d6466

func NewCompensator_done_Params(s *capnp.Segment) (Compensator_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Compensator_done_Params(st), err
}

func NewRootCompensator_done_Params(s *capnp.Segment) (Compensator_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Compensator_done_Params(st), err
}

func ReadRootCompensator_done_Params(msg *capnp.Message) (Compensator_done_Params, error) {
	root, err := msg.Root()
	return Compensator_done_Params(root.Struct()), err
}

func (s Compensator_done_Params) String() string {
	str, _ := text.Marshal(0xfe8b52379f3d6466, capnp.Struct(s))
	return str
}

func (s Compensator_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Compensator_done_Params) DecodeFromPtr(p capnp.Ptr) Compensator_done_Params {
	return Compensator_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Compensator_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Compensator_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Compensator_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Compensator_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Compensator_done_Params_List is a list of Compensator_done_Params.
type Compensator_done_Params_List = capnp.StructList[Compensator_done_Params]

// NewCompensator_done_Params creates a new list of Compensator_done_Params.
func NewCompensator_done_Params_List(s *capnp.Segment, sz int32) (Compensator_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Compensator_done_Params](l), err
}

// Compensator_done_Params_Future is a wrapper for a Compensator_done_Params promised by a client call.
type Compensator_done_Params_Future struct{ *capnp.Future }

func (f Compensator_done_Params_Future) Struct() (Compensator_done_Params, error) {
	p, err := f.Future.Ptr()
	return Compensator_done_Params(p.Struct()), err
}

type Compensator_done_Results capnp.Struct

// Compensator_done_Results_TypeID is the unique identifier for the type Compensator_done_Results.
const Compensator_done_Results_TypeID = 0xfb863e447caa9a35

func NewCompensator_done_Results(s *capnp.Segment) (Compensator_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Compensator_done_Results(st), err
}

func NewRootCompensator_done_Results(s *capnp.Segment) (Compensator_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Compensator_done_Results(st), err
}

func ReadRootCompensator_done_Results(msg *capnp.Message) (Compensator_done_Results, error) {
	root, err := msg.Root()
	return Compensator_done_Results(root.Struct()), err
}

func (s Compensator_done_Results) String() string {
	str, _ := text.Marshal(0xfb863e447caa9a35, capnp.Struct(s))
	return str
}

func (s Compensator_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Compensator_done_Results) DecodeFromPtr(p capnp.Ptr) Compensator_done_Results {
	return Compensator_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Compensator_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Compensator_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Compensator_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Compensator_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Compensator_done_Results) Compensator() (capnp.Float64List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.Float64List(p.List()), err
}

func (s Compensator_done_Results) HasCompensator() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Compensator_done_Results) SetCompensator(v capnp.Float64List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewCompensator sets the compensator field to a newly
// allocated capnp.Float64List, preferring placement in s's segment.
func (s Compensator_done_Results) NewCompensator(n int32) (capnp.Float64List, error) {
	l, err := capnp.NewFloat64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Float64List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// Compensator_done_Results_List is a list of Compensator_done_Results.
type Compensator_done_Results_List = capnp.StructList[Compensator_done_Results]

// NewCompensator_done_Results creates a new list of Compensator_done_Results.
func NewCompensator_done_Results_List(s *capnp.Segment, sz int32) (Compensator_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Compensator_done_Results](l), err
}

// Compensator_done_Results_Future is a wrapper for a Compensator_done_Results promised by a client call.
type Compensator_done_Results_Future struct{ *capnp.Future }

func (f Compensator_done_Results_Future) Struct() (Compensator_done_Results, error) {
	p, err := f.Future.Ptr()
	return Compensator_done_Results(p.Struct()), err
}
