// Code generated by capnpc-go. DO NOT EDIT.

package store

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	strconv "strconv"
)

type Sequence capnp.Client

// Sequence_TypeID is the unique identifier for the type Sequence.
const Sequence_TypeID = 0xe6115b6fdcda2cdd

func (c Sequence) Write(ctx context.Context, params func(Sequence_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe6115b6fdcda2cdd,
			MethodID:      0,
			InterfaceName: "nomagique/store/sequence.capnp:Sequence",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Sequence_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Sequence) Done(ctx context.Context, params func(Sequence_done_Params) error) (Item_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xe6115b6fdcda2cdd,
			MethodID:      1,
			InterfaceName: "nomagique/store/sequence.capnp:Sequence",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Sequence_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Item_Future{Future: ans.Future()}, release

}

func (c Sequence) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Sequence) String() string {
	return "Sequence(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Sequence) AddRef() Sequence {
	return Sequence(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Sequence) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Sequence) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Sequence) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Sequence) DecodeFromPtr(p capnp.Ptr) Sequence {
	return Sequence(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Sequence) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Sequence) IsSame(other Sequence) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Sequence) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Sequence) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Sequence_Server is a Sequence with a local implementation.
type Sequence_Server interface {
	Write(context.Context, Sequence_write) error

	Done(context.Context, Sequence_done) error
}

// Sequence_NewServer creates a new Server from an implementation of Sequence_Server.
func Sequence_NewServer(s Sequence_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Sequence_Methods(nil, s), s, c)
}

// Sequence_ServerToClient creates a new Client from an implementation of Sequence_Server.
// The caller is responsible for calling Release on the returned Client.
func Sequence_ServerToClient(s Sequence_Server) Sequence {
	return Sequence(capnp.NewClient(Sequence_NewServer(s)))
}

// Sequence_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Sequence_Methods(methods []server.Method, s Sequence_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe6115b6fdcda2cdd,
			MethodID:      0,
			InterfaceName: "nomagique/store/sequence.capnp:Sequence",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Sequence_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xe6115b6fdcda2cdd,
			MethodID:      1,
			InterfaceName: "nomagique/store/sequence.capnp:Sequence",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Sequence_done{call})
		},
	})

	return methods
}

// Sequence_write holds the state for a server call to Sequence.write.
// See server.Call for documentation.
type Sequence_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Sequence_write) Args() Sequence_write_Params {
	return Sequence_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Sequence_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Sequence_done holds the state for a server call to Sequence.done.
// See server.Call for documentation.
type Sequence_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Sequence_done) Args() Sequence_done_Params {
	return Sequence_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Sequence_done) AllocResults() (Item, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return Item(r), err
}

// Sequence_List is a list of Sequence.
type Sequence_List = capnp.CapList[Sequence]

// NewSequence_List creates a new list of Sequence.
func NewSequence_List(s *capnp.Segment, sz int32) (Sequence_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Sequence](l), err
}

type Sequence_write_Params capnp.Struct

// Sequence_write_Params_TypeID is the unique identifier for the type Sequence_write_Params.
const Sequence_write_Params_TypeID = 0xbee7a39db5cde247

func NewSequence_write_Params(s *capnp.Segment) (Sequence_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Sequence_write_Params(st), err
}

func NewRootSequence_write_Params(s *capnp.Segment) (Sequence_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Sequence_write_Params(st), err
}

func ReadRootSequence_write_Params(msg *capnp.Message) (Sequence_write_Params, error) {
	root, err := msg.Root()
	return Sequence_write_Params(root.Struct()), err
}

func (s Sequence_write_Params) String() string {
	str, _ := text.Marshal(0xbee7a39db5cde247, capnp.Struct(s))
	return str
}

func (s Sequence_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Sequence_write_Params) DecodeFromPtr(p capnp.Ptr) Sequence_write_Params {
	return Sequence_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Sequence_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Sequence_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Sequence_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Sequence_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Sequence_write_Params) Append() (capnp.DataList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.DataList(p.List()), err
}

func (s Sequence_write_Params) HasAppend() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Sequence_write_Params) SetAppend(v capnp.DataList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewAppend sets the append field to a newly
// allocated capnp.DataList, preferring placement in s's segment.
func (s Sequence_write_Params) NewAppend(n int32) (capnp.DataList, error) {
	l, err := capnp.NewDataList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.DataList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s Sequence_write_Params) Index() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Sequence_write_Params) SetIndex(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

// Sequence_write_Params_List is a list of Sequence_write_Params.
type Sequence_write_Params_List = capnp.StructList[Sequence_write_Params]

// NewSequence_write_Params creates a new list of Sequence_write_Params.
func NewSequence_write_Params_List(s *capnp.Segment, sz int32) (Sequence_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Sequence_write_Params](l), err
}

// Sequence_write_Params_Future is a wrapper for a Sequence_write_Params promised by a client call.
type Sequence_write_Params_Future struct{ *capnp.Future }

func (f Sequence_write_Params_Future) Struct() (Sequence_write_Params, error) {
	p, err := f.Future.Ptr()
	return Sequence_write_Params(p.Struct()), err
}

type Sequence_done_Params capnp.Struct

// Sequence_done_Params_TypeID is the unique identifier for the type Sequence_done_Params.
const Sequence_done_Params_TypeID = 0x962f9a101cfd1230

func NewSequence_done_Params(s *capnp.Segment) (Sequence_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Sequence_done_Params(st), err
}

func NewRootSequence_done_Params(s *capnp.Segment) (Sequence_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Sequence_done_Params(st), err
}

func ReadRootSequence_done_Params(msg *capnp.Message) (Sequence_done_Params, error) {
	root, err := msg.Root()
	return Sequence_done_Params(root.Struct()), err
}

func (s Sequence_done_Params) String() string {
	str, _ := text.Marshal(0x962f9a101cfd1230, capnp.Struct(s))
	return str
}

func (s Sequence_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Sequence_done_Params) DecodeFromPtr(p capnp.Ptr) Sequence_done_Params {
	return Sequence_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Sequence_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Sequence_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Sequence_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Sequence_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Sequence_done_Params_List is a list of Sequence_done_Params.
type Sequence_done_Params_List = capnp.StructList[Sequence_done_Params]

// NewSequence_done_Params creates a new list of Sequence_done_Params.
func NewSequence_done_Params_List(s *capnp.Segment, sz int32) (Sequence_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Sequence_done_Params](l), err
}

// Sequence_done_Params_Future is a wrapper for a Sequence_done_Params promised by a client call.
type Sequence_done_Params_Future struct{ *capnp.Future }

func (f Sequence_done_Params_Future) Struct() (Sequence_done_Params, error) {
	p, err := f.Future.Ptr()
	return Sequence_done_Params(p.Struct()), err
}

type Item capnp.Struct
type Item_item Item
type Item_Which uint16

const (
	Item_Which_missing Item_Which = 0
	Item_Which_item    Item_Which = 1
)

func (w Item_Which) String() string {
	const s = "missingitem"
	switch w {
	case Item_Which_missing:
		return s[0:7]
	case Item_Which_item:
		return s[7:11]

	}
	return "Item_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Item_TypeID is the unique identifier for the type Item.
const Item_TypeID = 0x99ac63f5dc2adacf

func NewItem(s *capnp.Segment) (Item, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return Item(st), err
}

func NewRootItem(s *capnp.Segment) (Item, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return Item(st), err
}

func ReadRootItem(msg *capnp.Message) (Item, error) {
	root, err := msg.Root()
	return Item(root.Struct()), err
}

func (s Item) String() string {
	str, _ := text.Marshal(0x99ac63f5dc2adacf, capnp.Struct(s))
	return str
}

func (s Item) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Item) DecodeFromPtr(p capnp.Ptr) Item {
	return Item(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Item) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Item) Which() Item_Which {
	return Item_Which(capnp.Struct(s).Uint16(10))
}
func (s Item) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Item) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Item) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Item) Count() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s Item) SetCount(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s Item) Found() bool {
	return capnp.Struct(s).Bit(64)
}

func (s Item) SetFound(v bool) {
	capnp.Struct(s).SetBit(64, v)
}

func (s Item) SetMissing() {
	capnp.Struct(s).SetUint16(10, 0)

}

func (s Item) Item() Item_item { return Item_item(s) }

func (s Item) SetItem() {
	capnp.Struct(s).SetUint16(10, 1)
}

func (s Item_item) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Item_item) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Item_item) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Item_item) Out() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Item_item) HasOut() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Item_item) SetOut(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Item_item) Next() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s Item_item) SetNext(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// Item_List is a list of Item.
type Item_List = capnp.StructList[Item]

// NewItem creates a new list of Item.
func NewItem_List(s *capnp.Segment, sz int32) (Item_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[Item](l), err
}

// Item_Future is a wrapper for a Item promised by a client call.
type Item_Future struct{ *capnp.Future }

func (f Item_Future) Struct() (Item, error) {
	p, err := f.Future.Ptr()
	return Item(p.Struct()), err
}
func (p Item_Future) Item() Item_item_Future { return Item_item_Future{p.Future} }

// Item_item_Future is a wrapper for a Item_item promised by a client call.
type Item_item_Future struct{ *capnp.Future }

func (f Item_item_Future) Struct() (Item_item, error) {
	p, err := f.Future.Ptr()
	return Item_item(p.Struct()), err
}
