// @ts-nocheck
// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from "flatbuffers";

import {
	EnvelopePerspective,
	type EnvelopePerspectiveT,
} from "../telemetry/envelope-perspective.js";

export class EnvelopeLiquiditySweepWithRecoveryUpdate
	implements
		flatbuffers.IUnpackableObject<EnvelopeLiquiditySweepWithRecoveryUpdateT>
{
	bb: flatbuffers.ByteBuffer | null = null;
	bb_pos = 0;
	__init(
		i: number,
		bb: flatbuffers.ByteBuffer,
	): EnvelopeLiquiditySweepWithRecoveryUpdate {
		this.bb_pos = i;
		this.bb = bb;
		return this;
	}

	static getRootAsEnvelopeLiquiditySweepWithRecoveryUpdate(
		bb: flatbuffers.ByteBuffer,
		obj?: EnvelopeLiquiditySweepWithRecoveryUpdate,
	): EnvelopeLiquiditySweepWithRecoveryUpdate {
		return (obj || new EnvelopeLiquiditySweepWithRecoveryUpdate()).__init(
			bb.readInt32(bb.position()) + bb.position(),
			bb,
		);
	}

	static getSizePrefixedRootAsEnvelopeLiquiditySweepWithRecoveryUpdate(
		bb: flatbuffers.ByteBuffer,
		obj?: EnvelopeLiquiditySweepWithRecoveryUpdate,
	): EnvelopeLiquiditySweepWithRecoveryUpdate {
		bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
		return (obj || new EnvelopeLiquiditySweepWithRecoveryUpdate()).__init(
			bb.readInt32(bb.position()) + bb.position(),
			bb,
		);
	}

	resolved(obj?: EnvelopePerspective): EnvelopePerspective | null {
		const offset = this.bb!.__offset(this.bb_pos, 4);
		return offset
			? (obj || new EnvelopePerspective()).__init(
					this.bb!.__indirect(this.bb_pos + offset),
					this.bb!,
				)
			: null;
	}

	issued(obj?: EnvelopePerspective): EnvelopePerspective | null {
		const offset = this.bb!.__offset(this.bb_pos, 6);
		return offset
			? (obj || new EnvelopePerspective()).__init(
					this.bb!.__indirect(this.bb_pos + offset),
					this.bb!,
				)
			: null;
	}

	static startEnvelopeLiquiditySweepWithRecoveryUpdate(
		builder: flatbuffers.Builder,
	) {
		builder.startObject(2);
	}

	static addResolved(
		builder: flatbuffers.Builder,
		resolvedOffset: flatbuffers.Offset,
	) {
		builder.addFieldOffset(0, resolvedOffset, 0);
	}

	static addIssued(
		builder: flatbuffers.Builder,
		issuedOffset: flatbuffers.Offset,
	) {
		builder.addFieldOffset(1, issuedOffset, 0);
	}

	static endEnvelopeLiquiditySweepWithRecoveryUpdate(
		builder: flatbuffers.Builder,
	): flatbuffers.Offset {
		const offset = builder.endObject();
		return offset;
	}

	unpack(): EnvelopeLiquiditySweepWithRecoveryUpdateT {
		return new EnvelopeLiquiditySweepWithRecoveryUpdateT(
			this.resolved() !== null ? this.resolved()!.unpack() : null,
			this.issued() !== null ? this.issued()!.unpack() : null,
		);
	}

	unpackTo(_o: EnvelopeLiquiditySweepWithRecoveryUpdateT): void {
		_o.resolved = this.resolved() !== null ? this.resolved()!.unpack() : null;
		_o.issued = this.issued() !== null ? this.issued()!.unpack() : null;
	}
}

export class EnvelopeLiquiditySweepWithRecoveryUpdateT
	implements flatbuffers.IGeneratedObject
{
	constructor(
		public resolved: EnvelopePerspectiveT | null = null,
		public issued: EnvelopePerspectiveT | null = null,
	) {}

	pack(builder: flatbuffers.Builder): flatbuffers.Offset {
		const resolved = this.resolved !== null ? this.resolved!.pack(builder) : 0;
		const issued = this.issued !== null ? this.issued!.pack(builder) : 0;

		EnvelopeLiquiditySweepWithRecoveryUpdate.startEnvelopeLiquiditySweepWithRecoveryUpdate(
			builder,
		);
		EnvelopeLiquiditySweepWithRecoveryUpdate.addResolved(builder, resolved);
		EnvelopeLiquiditySweepWithRecoveryUpdate.addIssued(builder, issued);

		return EnvelopeLiquiditySweepWithRecoveryUpdate.endEnvelopeLiquiditySweepWithRecoveryUpdate(
			builder,
		);
	}
}
