// Code generated by capnpc-go. DO NOT EDIT.

package volume

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type Mfv capnp.Client

// Mfv_TypeID is the unique identifier for the type Mfv.
const Mfv_TypeID = 0x918a481605a1ebee

func (c Mfv) Write(ctx context.Context, params func(Mfv_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x918a481605a1ebee,
			MethodID:      0,
			InterfaceName: "nomagique/financial/volume/mfv.capnp:Mfv",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 32, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Mfv_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Mfv) Done(ctx context.Context, params func(Mfv_done_Params) error) (Mfv_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x918a481605a1ebee,
			MethodID:      1,
			InterfaceName: "nomagique/financial/volume/mfv.capnp:Mfv",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Mfv_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Mfv_done_Results_Future{Future: ans.Future()}, release

}

func (c Mfv) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Mfv) String() string {
	return "Mfv(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Mfv) AddRef() Mfv {
	return Mfv(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Mfv) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Mfv) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Mfv) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Mfv) DecodeFromPtr(p capnp.Ptr) Mfv {
	return Mfv(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Mfv) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Mfv) IsSame(other Mfv) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Mfv) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Mfv) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Mfv_Server is a Mfv with a local implementation.
type Mfv_Server interface {
	Write(context.Context, Mfv_write) error

	Done(context.Context, Mfv_done) error
}

// Mfv_NewServer creates a new Server from an implementation of Mfv_Server.
func Mfv_NewServer(s Mfv_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Mfv_Methods(nil, s), s, c)
}

// Mfv_ServerToClient creates a new Client from an implementation of Mfv_Server.
// The caller is responsible for calling Release on the returned Client.
func Mfv_ServerToClient(s Mfv_Server) Mfv {
	return Mfv(capnp.NewClient(Mfv_NewServer(s)))
}

// Mfv_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Mfv_Methods(methods []server.Method, s Mfv_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x918a481605a1ebee,
			MethodID:      0,
			InterfaceName: "nomagique/financial/volume/mfv.capnp:Mfv",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Mfv_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x918a481605a1ebee,
			MethodID:      1,
			InterfaceName: "nomagique/financial/volume/mfv.capnp:Mfv",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Mfv_done{call})
		},
	})

	return methods
}

// Mfv_write holds the state for a server call to Mfv.write.
// See server.Call for documentation.
type Mfv_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Mfv_write) Args() Mfv_write_Params {
	return Mfv_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Mfv_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Mfv_done holds the state for a server call to Mfv.done.
// See server.Call for documentation.
type Mfv_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Mfv_done) Args() Mfv_done_Params {
	return Mfv_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Mfv_done) AllocResults() (Mfv_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Mfv_done_Results(r), err
}

// Mfv_List is a list of Mfv.
type Mfv_List = capnp.CapList[Mfv]

// NewMfv_List creates a new list of Mfv.
func NewMfv_List(s *capnp.Segment, sz int32) (Mfv_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Mfv](l), err
}

type Mfv_write_Params capnp.Struct

// Mfv_write_Params_TypeID is the unique identifier for the type Mfv_write_Params.
const Mfv_write_Params_TypeID = 0xf470b2c0bb2e26a7

func NewMfv_write_Params(s *capnp.Segment) (Mfv_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return Mfv_write_Params(st), err
}

func NewRootMfv_write_Params(s *capnp.Segment) (Mfv_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0})
	return Mfv_write_Params(st), err
}

func ReadRootMfv_write_Params(msg *capnp.Message) (Mfv_write_Params, error) {
	root, err := msg.Root()
	return Mfv_write_Params(root.Struct()), err
}

func (s Mfv_write_Params) String() string {
	str, _ := text.Marshal(0xf470b2c0bb2e26a7, capnp.Struct(s))
	return str
}

func (s Mfv_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Mfv_write_Params) DecodeFromPtr(p capnp.Ptr) Mfv_write_Params {
	return Mfv_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Mfv_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Mfv_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Mfv_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Mfv_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Mfv_write_Params) High() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Mfv_write_Params) SetHigh(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Mfv_write_Params) Low() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Mfv_write_Params) SetLow(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Mfv_write_Params) Close() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Mfv_write_Params) SetClose(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s Mfv_write_Params) Volume() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(24))
}

func (s Mfv_write_Params) SetVolume(v float64) {
	capnp.Struct(s).SetUint64(24, math.Float64bits(v))
}

// Mfv_write_Params_List is a list of Mfv_write_Params.
type Mfv_write_Params_List = capnp.StructList[Mfv_write_Params]

// NewMfv_write_Params creates a new list of Mfv_write_Params.
func NewMfv_write_Params_List(s *capnp.Segment, sz int32) (Mfv_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 32, PointerCount: 0}, sz)
	return capnp.StructList[Mfv_write_Params](l), err
}

// Mfv_write_Params_Future is a wrapper for a Mfv_write_Params promised by a client call.
type Mfv_write_Params_Future struct{ *capnp.Future }

func (f Mfv_write_Params_Future) Struct() (Mfv_write_Params, error) {
	p, err := f.Future.Ptr()
	return Mfv_write_Params(p.Struct()), err
}

type Mfv_done_Params capnp.Struct

// Mfv_done_Params_TypeID is the unique identifier for the type Mfv_done_Params.
const Mfv_done_Params_TypeID = 0xa681fb66bd655a6e

func NewMfv_done_Params(s *capnp.Segment) (Mfv_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Mfv_done_Params(st), err
}

func NewRootMfv_done_Params(s *capnp.Segment) (Mfv_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Mfv_done_Params(st), err
}

func ReadRootMfv_done_Params(msg *capnp.Message) (Mfv_done_Params, error) {
	root, err := msg.Root()
	return Mfv_done_Params(root.Struct()), err
}

func (s Mfv_done_Params) String() string {
	str, _ := text.Marshal(0xa681fb66bd655a6e, capnp.Struct(s))
	return str
}

func (s Mfv_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Mfv_done_Params) DecodeFromPtr(p capnp.Ptr) Mfv_done_Params {
	return Mfv_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Mfv_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Mfv_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Mfv_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Mfv_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Mfv_done_Params_List is a list of Mfv_done_Params.
type Mfv_done_Params_List = capnp.StructList[Mfv_done_Params]

// NewMfv_done_Params creates a new list of Mfv_done_Params.
func NewMfv_done_Params_List(s *capnp.Segment, sz int32) (Mfv_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Mfv_done_Params](l), err
}

// Mfv_done_Params_Future is a wrapper for a Mfv_done_Params promised by a client call.
type Mfv_done_Params_Future struct{ *capnp.Future }

func (f Mfv_done_Params_Future) Struct() (Mfv_done_Params, error) {
	p, err := f.Future.Ptr()
	return Mfv_done_Params(p.Struct()), err
}

type Mfv_done_Results capnp.Struct

// Mfv_done_Results_TypeID is the unique identifier for the type Mfv_done_Results.
const Mfv_done_Results_TypeID = 0x97c7696eae3e0f36

func NewMfv_done_Results(s *capnp.Segment) (Mfv_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Mfv_done_Results(st), err
}

func NewRootMfv_done_Results(s *capnp.Segment) (Mfv_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Mfv_done_Results(st), err
}

func ReadRootMfv_done_Results(msg *capnp.Message) (Mfv_done_Results, error) {
	root, err := msg.Root()
	return Mfv_done_Results(root.Struct()), err
}

func (s Mfv_done_Results) String() string {
	str, _ := text.Marshal(0x97c7696eae3e0f36, capnp.Struct(s))
	return str
}

func (s Mfv_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Mfv_done_Results) DecodeFromPtr(p capnp.Ptr) Mfv_done_Results {
	return Mfv_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Mfv_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Mfv_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Mfv_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Mfv_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Mfv_done_Results) Result() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Mfv_done_Results) SetResult(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Mfv_done_Results_List is a list of Mfv_done_Results.
type Mfv_done_Results_List = capnp.StructList[Mfv_done_Results]

// NewMfv_done_Results creates a new list of Mfv_done_Results.
func NewMfv_done_Results_List(s *capnp.Segment, sz int32) (Mfv_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Mfv_done_Results](l), err
}

// Mfv_done_Results_Future is a wrapper for a Mfv_done_Results promised by a client call.
type Mfv_done_Results_Future struct{ *capnp.Future }

func (f Mfv_done_Results_Future) Struct() (Mfv_done_Results, error) {
	p, err := f.Future.Ptr()
	return Mfv_done_Results(p.Struct()), err
}
