// Code generated by capnpc-go. DO NOT EDIT.

package data

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
)

type Chunk capnp.Client

// Chunk_TypeID is the unique identifier for the type Chunk.
const Chunk_TypeID = 0xc633cb7d53d128a6

func (c Chunk) Write(ctx context.Context, params func(Chunk_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc633cb7d53d128a6,
			MethodID:      0,
			InterfaceName: "nomagique/data/chunk.capnp:Chunk",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Chunk_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Chunk) Done(ctx context.Context, params func(Chunk_done_Params) error) (Chunk_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xc633cb7d53d128a6,
			MethodID:      1,
			InterfaceName: "nomagique/data/chunk.capnp:Chunk",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Chunk_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Chunk_done_Results_Future{Future: ans.Future()}, release

}

func (c Chunk) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Chunk) String() string {
	return "Chunk(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Chunk) AddRef() Chunk {
	return Chunk(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Chunk) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Chunk) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Chunk) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Chunk) DecodeFromPtr(p capnp.Ptr) Chunk {
	return Chunk(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Chunk) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Chunk) IsSame(other Chunk) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Chunk) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Chunk) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Chunk_Server is a Chunk with a local implementation.
type Chunk_Server interface {
	Write(context.Context, Chunk_write) error

	Done(context.Context, Chunk_done) error
}

// Chunk_NewServer creates a new Server from an implementation of Chunk_Server.
func Chunk_NewServer(s Chunk_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Chunk_Methods(nil, s), s, c)
}

// Chunk_ServerToClient creates a new Client from an implementation of Chunk_Server.
// The caller is responsible for calling Release on the returned Client.
func Chunk_ServerToClient(s Chunk_Server) Chunk {
	return Chunk(capnp.NewClient(Chunk_NewServer(s)))
}

// Chunk_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Chunk_Methods(methods []server.Method, s Chunk_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc633cb7d53d128a6,
			MethodID:      0,
			InterfaceName: "nomagique/data/chunk.capnp:Chunk",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Chunk_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xc633cb7d53d128a6,
			MethodID:      1,
			InterfaceName: "nomagique/data/chunk.capnp:Chunk",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Chunk_done{call})
		},
	})

	return methods
}

// Chunk_write holds the state for a server call to Chunk.write.
// See server.Call for documentation.
type Chunk_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Chunk_write) Args() Chunk_write_Params {
	return Chunk_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Chunk_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Chunk_done holds the state for a server call to Chunk.done.
// See server.Call for documentation.
type Chunk_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Chunk_done) Args() Chunk_done_Params {
	return Chunk_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Chunk_done) AllocResults() (Chunk_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 8})
	return Chunk_done_Results(r), err
}

// Chunk_List is a list of Chunk.
type Chunk_List = capnp.CapList[Chunk]

// NewChunk_List creates a new list of Chunk.
func NewChunk_List(s *capnp.Segment, sz int32) (Chunk_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Chunk](l), err
}

type Chunk_write_Params capnp.Struct

// Chunk_write_Params_TypeID is the unique identifier for the type Chunk_write_Params.
const Chunk_write_Params_TypeID = 0xebb2ae2cd4b95cd4

func NewChunk_write_Params(s *capnp.Segment) (Chunk_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return Chunk_write_Params(st), err
}

func NewRootChunk_write_Params(s *capnp.Segment) (Chunk_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return Chunk_write_Params(st), err
}

func ReadRootChunk_write_Params(msg *capnp.Message) (Chunk_write_Params, error) {
	root, err := msg.Root()
	return Chunk_write_Params(root.Struct()), err
}

func (s Chunk_write_Params) String() string {
	str, _ := text.Marshal(0xebb2ae2cd4b95cd4, capnp.Struct(s))
	return str
}

func (s Chunk_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Chunk_write_Params) DecodeFromPtr(p capnp.Ptr) Chunk_write_Params {
	return Chunk_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Chunk_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Chunk_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Chunk_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Chunk_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Chunk_write_Params) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Chunk_write_Params) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Chunk_write_Params) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Chunk_write_Params) Size() int64 {
	return int64(capnp.Struct(s).Uint64(0))
}

func (s Chunk_write_Params) SetSize(v int64) {
	capnp.Struct(s).SetUint64(0, uint64(v))
}

func (s Chunk_write_Params) Endpoint() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Chunk_write_Params) HasEndpoint() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Chunk_write_Params) EndpointBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Chunk_write_Params) SetEndpoint(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// Chunk_write_Params_List is a list of Chunk_write_Params.
type Chunk_write_Params_List = capnp.StructList[Chunk_write_Params]

// NewChunk_write_Params creates a new list of Chunk_write_Params.
func NewChunk_write_Params_List(s *capnp.Segment, sz int32) (Chunk_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[Chunk_write_Params](l), err
}

// Chunk_write_Params_Future is a wrapper for a Chunk_write_Params promised by a client call.
type Chunk_write_Params_Future struct{ *capnp.Future }

func (f Chunk_write_Params_Future) Struct() (Chunk_write_Params, error) {
	p, err := f.Future.Ptr()
	return Chunk_write_Params(p.Struct()), err
}

type Chunk_done_Params capnp.Struct

// Chunk_done_Params_TypeID is the unique identifier for the type Chunk_done_Params.
const Chunk_done_Params_TypeID = 0xa50a99c6913e124c

func NewChunk_done_Params(s *capnp.Segment) (Chunk_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Chunk_done_Params(st), err
}

func NewRootChunk_done_Params(s *capnp.Segment) (Chunk_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Chunk_done_Params(st), err
}

func ReadRootChunk_done_Params(msg *capnp.Message) (Chunk_done_Params, error) {
	root, err := msg.Root()
	return Chunk_done_Params(root.Struct()), err
}

func (s Chunk_done_Params) String() string {
	str, _ := text.Marshal(0xa50a99c6913e124c, capnp.Struct(s))
	return str
}

func (s Chunk_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Chunk_done_Params) DecodeFromPtr(p capnp.Ptr) Chunk_done_Params {
	return Chunk_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Chunk_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Chunk_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Chunk_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Chunk_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Chunk_done_Params_List is a list of Chunk_done_Params.
type Chunk_done_Params_List = capnp.StructList[Chunk_done_Params]

// NewChunk_done_Params creates a new list of Chunk_done_Params.
func NewChunk_done_Params_List(s *capnp.Segment, sz int32) (Chunk_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Chunk_done_Params](l), err
}

// Chunk_done_Params_Future is a wrapper for a Chunk_done_Params promised by a client call.
type Chunk_done_Params_Future struct{ *capnp.Future }

func (f Chunk_done_Params_Future) Struct() (Chunk_done_Params, error) {
	p, err := f.Future.Ptr()
	return Chunk_done_Params(p.Struct()), err
}

type Chunk_done_Results capnp.Struct

// Chunk_done_Results_TypeID is the unique identifier for the type Chunk_done_Results.
const Chunk_done_Results_TypeID = 0xf928bdfb1d26ac89

func NewChunk_done_Results(s *capnp.Segment) (Chunk_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 8})
	return Chunk_done_Results(st), err
}

func NewRootChunk_done_Results(s *capnp.Segment) (Chunk_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 8})
	return Chunk_done_Results(st), err
}

func ReadRootChunk_done_Results(msg *capnp.Message) (Chunk_done_Results, error) {
	root, err := msg.Root()
	return Chunk_done_Results(root.Struct()), err
}

func (s Chunk_done_Results) String() string {
	str, _ := text.Marshal(0xf928bdfb1d26ac89, capnp.Struct(s))
	return str
}

func (s Chunk_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Chunk_done_Results) DecodeFromPtr(p capnp.Ptr) Chunk_done_Results {
	return Chunk_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Chunk_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Chunk_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Chunk_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Chunk_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Chunk_done_Results) Out0() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Chunk_done_Results) HasOut0() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Chunk_done_Results) SetOut0(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Chunk_done_Results) Out1() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Chunk_done_Results) HasOut1() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Chunk_done_Results) SetOut1(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

func (s Chunk_done_Results) Out2() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Chunk_done_Results) HasOut2() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Chunk_done_Results) SetOut2(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s Chunk_done_Results) Out3() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s Chunk_done_Results) HasOut3() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Chunk_done_Results) SetOut3(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

func (s Chunk_done_Results) Endpoint0() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Chunk_done_Results) HasEndpoint0() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Chunk_done_Results) Endpoint0Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Chunk_done_Results) SetEndpoint0(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Chunk_done_Results) Endpoint1() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Chunk_done_Results) HasEndpoint1() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Chunk_done_Results) Endpoint1Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Chunk_done_Results) SetEndpoint1(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Chunk_done_Results) Endpoint2() (string, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.Text(), err
}

func (s Chunk_done_Results) HasEndpoint2() bool {
	return capnp.Struct(s).HasPtr(6)
}

func (s Chunk_done_Results) Endpoint2Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(6)
	return p.TextBytes(), err
}

func (s Chunk_done_Results) SetEndpoint2(v string) error {
	return capnp.Struct(s).SetText(6, v)
}

func (s Chunk_done_Results) Endpoint3() (string, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.Text(), err
}

func (s Chunk_done_Results) HasEndpoint3() bool {
	return capnp.Struct(s).HasPtr(7)
}

func (s Chunk_done_Results) Endpoint3Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(7)
	return p.TextBytes(), err
}

func (s Chunk_done_Results) SetEndpoint3(v string) error {
	return capnp.Struct(s).SetText(7, v)
}

// Chunk_done_Results_List is a list of Chunk_done_Results.
type Chunk_done_Results_List = capnp.StructList[Chunk_done_Results]

// NewChunk_done_Results creates a new list of Chunk_done_Results.
func NewChunk_done_Results_List(s *capnp.Segment, sz int32) (Chunk_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 8}, sz)
	return capnp.StructList[Chunk_done_Results](l), err
}

// Chunk_done_Results_Future is a wrapper for a Chunk_done_Results promised by a client call.
type Chunk_done_Results_Future struct{ *capnp.Future }

func (f Chunk_done_Results_Future) Struct() (Chunk_done_Results, error) {
	p, err := f.Future.Ptr()
	return Chunk_done_Results(p.Struct()), err
}
