// Code generated by capnpc-go. DO NOT EDIT.

package momentum

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type AwesomeOscillator capnp.Client

// AwesomeOscillator_TypeID is the unique identifier for the type AwesomeOscillator.
const AwesomeOscillator_TypeID = 0x8a3c91a40bb0e7b8

func (c AwesomeOscillator) Write(ctx context.Context, params func(AwesomeOscillator_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a3c91a40bb0e7b8,
			MethodID:      0,
			InterfaceName: "nomagique/financial/momentum/awesome_oscillator.capnp:AwesomeOscillator",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 16, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AwesomeOscillator_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c AwesomeOscillator) Done(ctx context.Context, params func(AwesomeOscillator_done_Params) error) (AwesomeOscillator_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x8a3c91a40bb0e7b8,
			MethodID:      1,
			InterfaceName: "nomagique/financial/momentum/awesome_oscillator.capnp:AwesomeOscillator",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(AwesomeOscillator_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return AwesomeOscillator_done_Results_Future{Future: ans.Future()}, release

}

func (c AwesomeOscillator) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c AwesomeOscillator) String() string {
	return "AwesomeOscillator(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c AwesomeOscillator) AddRef() AwesomeOscillator {
	return AwesomeOscillator(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c AwesomeOscillator) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c AwesomeOscillator) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c AwesomeOscillator) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (AwesomeOscillator) DecodeFromPtr(p capnp.Ptr) AwesomeOscillator {
	return AwesomeOscillator(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c AwesomeOscillator) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c AwesomeOscillator) IsSame(other AwesomeOscillator) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c AwesomeOscillator) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c AwesomeOscillator) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A AwesomeOscillator_Server is a AwesomeOscillator with a local implementation.
type AwesomeOscillator_Server interface {
	Write(context.Context, AwesomeOscillator_write) error

	Done(context.Context, AwesomeOscillator_done) error
}

// AwesomeOscillator_NewServer creates a new Server from an implementation of AwesomeOscillator_Server.
func AwesomeOscillator_NewServer(s AwesomeOscillator_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(AwesomeOscillator_Methods(nil, s), s, c)
}

// AwesomeOscillator_ServerToClient creates a new Client from an implementation of AwesomeOscillator_Server.
// The caller is responsible for calling Release on the returned Client.
func AwesomeOscillator_ServerToClient(s AwesomeOscillator_Server) AwesomeOscillator {
	return AwesomeOscillator(capnp.NewClient(AwesomeOscillator_NewServer(s)))
}

// AwesomeOscillator_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func AwesomeOscillator_Methods(methods []server.Method, s AwesomeOscillator_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a3c91a40bb0e7b8,
			MethodID:      0,
			InterfaceName: "nomagique/financial/momentum/awesome_oscillator.capnp:AwesomeOscillator",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, AwesomeOscillator_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x8a3c91a40bb0e7b8,
			MethodID:      1,
			InterfaceName: "nomagique/financial/momentum/awesome_oscillator.capnp:AwesomeOscillator",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, AwesomeOscillator_done{call})
		},
	})

	return methods
}

// AwesomeOscillator_write holds the state for a server call to AwesomeOscillator.write.
// See server.Call for documentation.
type AwesomeOscillator_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AwesomeOscillator_write) Args() AwesomeOscillator_write_Params {
	return AwesomeOscillator_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AwesomeOscillator_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// AwesomeOscillator_done holds the state for a server call to AwesomeOscillator.done.
// See server.Call for documentation.
type AwesomeOscillator_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c AwesomeOscillator_done) Args() AwesomeOscillator_done_Params {
	return AwesomeOscillator_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c AwesomeOscillator_done) AllocResults() (AwesomeOscillator_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AwesomeOscillator_done_Results(r), err
}

// AwesomeOscillator_List is a list of AwesomeOscillator.
type AwesomeOscillator_List = capnp.CapList[AwesomeOscillator]

// NewAwesomeOscillator_List creates a new list of AwesomeOscillator.
func NewAwesomeOscillator_List(s *capnp.Segment, sz int32) (AwesomeOscillator_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[AwesomeOscillator](l), err
}

type AwesomeOscillator_write_Params capnp.Struct

// AwesomeOscillator_write_Params_TypeID is the unique identifier for the type AwesomeOscillator_write_Params.
const AwesomeOscillator_write_Params_TypeID = 0xff366a9a3972908d

func NewAwesomeOscillator_write_Params(s *capnp.Segment) (AwesomeOscillator_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return AwesomeOscillator_write_Params(st), err
}

func NewRootAwesomeOscillator_write_Params(s *capnp.Segment) (AwesomeOscillator_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0})
	return AwesomeOscillator_write_Params(st), err
}

func ReadRootAwesomeOscillator_write_Params(msg *capnp.Message) (AwesomeOscillator_write_Params, error) {
	root, err := msg.Root()
	return AwesomeOscillator_write_Params(root.Struct()), err
}

func (s AwesomeOscillator_write_Params) String() string {
	str, _ := text.Marshal(0xff366a9a3972908d, capnp.Struct(s))
	return str
}

func (s AwesomeOscillator_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AwesomeOscillator_write_Params) DecodeFromPtr(p capnp.Ptr) AwesomeOscillator_write_Params {
	return AwesomeOscillator_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AwesomeOscillator_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AwesomeOscillator_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AwesomeOscillator_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AwesomeOscillator_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AwesomeOscillator_write_Params) High() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s AwesomeOscillator_write_Params) SetHigh(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s AwesomeOscillator_write_Params) Low() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s AwesomeOscillator_write_Params) SetLow(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// AwesomeOscillator_write_Params_List is a list of AwesomeOscillator_write_Params.
type AwesomeOscillator_write_Params_List = capnp.StructList[AwesomeOscillator_write_Params]

// NewAwesomeOscillator_write_Params creates a new list of AwesomeOscillator_write_Params.
func NewAwesomeOscillator_write_Params_List(s *capnp.Segment, sz int32) (AwesomeOscillator_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 0}, sz)
	return capnp.StructList[AwesomeOscillator_write_Params](l), err
}

// AwesomeOscillator_write_Params_Future is a wrapper for a AwesomeOscillator_write_Params promised by a client call.
type AwesomeOscillator_write_Params_Future struct{ *capnp.Future }

func (f AwesomeOscillator_write_Params_Future) Struct() (AwesomeOscillator_write_Params, error) {
	p, err := f.Future.Ptr()
	return AwesomeOscillator_write_Params(p.Struct()), err
}

type AwesomeOscillator_done_Params capnp.Struct

// AwesomeOscillator_done_Params_TypeID is the unique identifier for the type AwesomeOscillator_done_Params.
const AwesomeOscillator_done_Params_TypeID = 0xa6f0d410b76173fc

func NewAwesomeOscillator_done_Params(s *capnp.Segment) (AwesomeOscillator_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AwesomeOscillator_done_Params(st), err
}

func NewRootAwesomeOscillator_done_Params(s *capnp.Segment) (AwesomeOscillator_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return AwesomeOscillator_done_Params(st), err
}

func ReadRootAwesomeOscillator_done_Params(msg *capnp.Message) (AwesomeOscillator_done_Params, error) {
	root, err := msg.Root()
	return AwesomeOscillator_done_Params(root.Struct()), err
}

func (s AwesomeOscillator_done_Params) String() string {
	str, _ := text.Marshal(0xa6f0d410b76173fc, capnp.Struct(s))
	return str
}

func (s AwesomeOscillator_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AwesomeOscillator_done_Params) DecodeFromPtr(p capnp.Ptr) AwesomeOscillator_done_Params {
	return AwesomeOscillator_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AwesomeOscillator_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AwesomeOscillator_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AwesomeOscillator_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AwesomeOscillator_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// AwesomeOscillator_done_Params_List is a list of AwesomeOscillator_done_Params.
type AwesomeOscillator_done_Params_List = capnp.StructList[AwesomeOscillator_done_Params]

// NewAwesomeOscillator_done_Params creates a new list of AwesomeOscillator_done_Params.
func NewAwesomeOscillator_done_Params_List(s *capnp.Segment, sz int32) (AwesomeOscillator_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[AwesomeOscillator_done_Params](l), err
}

// AwesomeOscillator_done_Params_Future is a wrapper for a AwesomeOscillator_done_Params promised by a client call.
type AwesomeOscillator_done_Params_Future struct{ *capnp.Future }

func (f AwesomeOscillator_done_Params_Future) Struct() (AwesomeOscillator_done_Params, error) {
	p, err := f.Future.Ptr()
	return AwesomeOscillator_done_Params(p.Struct()), err
}

type AwesomeOscillator_done_Results capnp.Struct

// AwesomeOscillator_done_Results_TypeID is the unique identifier for the type AwesomeOscillator_done_Results.
const AwesomeOscillator_done_Results_TypeID = 0x8a76ce35697c4238

func NewAwesomeOscillator_done_Results(s *capnp.Segment) (AwesomeOscillator_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AwesomeOscillator_done_Results(st), err
}

func NewRootAwesomeOscillator_done_Results(s *capnp.Segment) (AwesomeOscillator_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return AwesomeOscillator_done_Results(st), err
}

func ReadRootAwesomeOscillator_done_Results(msg *capnp.Message) (AwesomeOscillator_done_Results, error) {
	root, err := msg.Root()
	return AwesomeOscillator_done_Results(root.Struct()), err
}

func (s AwesomeOscillator_done_Results) String() string {
	str, _ := text.Marshal(0x8a76ce35697c4238, capnp.Struct(s))
	return str
}

func (s AwesomeOscillator_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (AwesomeOscillator_done_Results) DecodeFromPtr(p capnp.Ptr) AwesomeOscillator_done_Results {
	return AwesomeOscillator_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s AwesomeOscillator_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s AwesomeOscillator_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s AwesomeOscillator_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s AwesomeOscillator_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s AwesomeOscillator_done_Results) Result() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s AwesomeOscillator_done_Results) SetResult(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// AwesomeOscillator_done_Results_List is a list of AwesomeOscillator_done_Results.
type AwesomeOscillator_done_Results_List = capnp.StructList[AwesomeOscillator_done_Results]

// NewAwesomeOscillator_done_Results creates a new list of AwesomeOscillator_done_Results.
func NewAwesomeOscillator_done_Results_List(s *capnp.Segment, sz int32) (AwesomeOscillator_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[AwesomeOscillator_done_Results](l), err
}

// AwesomeOscillator_done_Results_Future is a wrapper for a AwesomeOscillator_done_Results promised by a client call.
type AwesomeOscillator_done_Results_Future struct{ *capnp.Future }

func (f AwesomeOscillator_done_Results_Future) Struct() (AwesomeOscillator_done_Results, error) {
	p, err := f.Future.Ptr()
	return AwesomeOscillator_done_Results(p.Struct()), err
}

const schema_a625f78f3dbd3a99 = "x\xda\xccZ{xT\xd5\xb5\xdf\xfb\x9c\x84\x040\x86" +
	"\x93\x13^y2y'\x14C\x02\x01\x12y\x04r\xa1" +
	"\x84\x97\x9cD\x0a\xe2\xf5\x8e'\xc919\xc9\xbc\x983" +
	"\x934Bl\x83\xc0\x14\x10\x01\x11K\xa2 \x9f\x15y" +
	"X\xa8h\x0b\xf5\x01\x17\xa8\xb4\xa64H(\"\xb1\x17" +
	"\x05\xb4*\xf8\xa8\x04\xc5\x9b\xef\x8a\xe7~kO\xf6\x99" +
	"\x93p \x93I>\xed\x7f3{\xefY{\xcd\xfa\xad" +
	"\xf5[k\xed\xbdG;\xef\xcc\x0f\xca\x0a\xf3\xa4 \xa6" +
	"\xf8\x08\x0e\xee\xa76}\xb3|\xef\x98\x81\x19\xbfD\\" +
	".\xab\xfe\x82\x91>\xda\x97\xb4v\x17BxL:_" +
	"\xc9\xf0s\xf9\x10\x84\xf8B\xde\xc37\xc0'5\xb9\xb2" +
	"$\xb7`\xfa\xe4z\xc4e\xb1j\xc5\xe37\xcen\xbf" +
	"\xbc\xf8+X]\xcf\xb7a~+Y\xdd\xc0{\xf8\xcb" +
	"d\xf5\xc9$\xf9\x14\x1f\xf6|=\xe22X\xf5\xc0[" +
	"7\x9e\xfb\xfd\x86\x17Zau\x0b\xbf\x06{\xd7\xf0\xff" +
	"\xe4=|N$\xac\xfe}\xc4\x1b\x8b\xa6\xf4[\xb0\x9c" +
	"\xc8\xde\x99\xb8<\xb3\xa6\xa1\xfcSX\x1d\x1b\xd9\x86\xf9" +
	"\\X\xc3\xe7Dz\xf8\x95d\xf5\xd4{V\xf5\x7f\xab" +
	"\xb0y\x15\x12\x0a0F((\x04\xa11\xd6\xc8\xe5\x0c" +
	"\xc2\xfc\xea\xc8)\x08\xab/-:r\xea\xe0\xa5\xef~" +
	"\x85\xb8lV\xe5\xf6\xdf9`\xc6\xbf\xb2>\x06q\xbb" +
	"#\x19\x86?N\xc4\x1d\x8d\xf4\xf0\xdc`\x10w\xf5\xc4" +
	"\xd3iA;~\xbb\x1a\x09\xf98\xb8C\\{d%" +
	"\x83\xf0\x98\xc1\x83\xe31\xc2\xea\x1f?yi\xe0\xf3\x1b" +
	"'\xaeA\xdc8Vm\xc8;4i\xfd\xb7\xc9/\x80" +
	"\xbc\xdc!\xd3\x18\xfe\xbe! o\xc1\x10\x0f\xbf\x03>" +
	"\xa9\x13\xa6-\x93sNV\xafA\xc2LM\xbduC" +
	"\xf6\x80z{\x87\x80z\xfb\xfe\xb2wL\xd6l\xfbZ" +
	"\xc4\x8de\xd5\xb4I\x83\xeez\xc2\x1e\xb6\x15\xc45\x0f" +
	"\x89b\xf8/\x88\xb8\xcbC<|\xeeP\x10\xb7\xa5\xff" +
	"\xb6e\xf7\x86_Z\x8b\xb8LV\xcd:\x13\xde\xb8\xe4" +
	"\xbd\xcf\xf6\xc2j\xd3\xd0\xd3\x98\x9f\x04k\xf8\xdc\xa1\x1e" +
	"~5Y}\xf1\xfe\xd7W\xbbO:\x1fG\xc2\\\xcc" +
	"vl\xbed\xe8i\xd8|\xf3\xd0\xdf!\xac^\x8b\xfe" +
	"W\xd3\xce&\xc7zb\xeaY\x7f{\xb90ug;" +
	"\xd9|\xd4\xb06\xcc\x17\x0e\x03q\xd3\x87y\xf8\xcd\xf0" +
	"I\xbd\xf3\xa5\xa7k\x9e9{`#\x12Fj\xff\xa5" +
	"n\xd81\x8c0\xbfn\x18\xfc\x97\xbf\x1c^}\xaa\xe0" +
	"\xd9\xcf7\"a2\x0e\xeaX\xb0w\xd8b\xd8\xafi" +
	"\xd8'\x08\xabq\xe1\x9fm*\xbf4s\x13\xe2fR" +
	"\x01{\x87?\xc7\xa0 \xd5^\xbc\xc36p\xcd\xce'" +
	"\xf5\xb2\xf7\x0e'\xb2\x0f\x0d\x07\xd9[\xdb\x96\x04\x8d\xc9" +
	":\xd7i\xc1y\xef\x82/\xc8\x82\x83s'\xdd\xb7\xfd" +
	"\x91\x91\x9bas\xa6cAX\x14\xd9<=\xaa\x06a" +
	"\xf5'U\xef>k~\xe9\xc4Sz\x09+\xa3\x88\x84" +
	"\xcdQ \xe1\xfe\xb3W\x9e\xdf\xf4\xf5\x93[\x10\x97E" +
	"\xe7\xff\x10u\x05\xa3 u\xd3\x81\xd4\xe2X\xf3\x9e\x06" +
	"$\xe4i?\xdd\x1d\x95\x07\xb2\x8f\x92\x9f~\xdf\xbc*" +
	"\x7f\xdf\xa3\xaf4 n.\x9d\xbf\x18\xf5W\xf8c\xfb" +
	"\x1a-\xa1s\x92\xdb\x1aA-:\xf5O\xafZ8\x1a" +
	"~zf\xd0\x97\xa1\xeb\xe5\xa4g\x900A\x03\xc9\x14" +
	"\x9d\x01\x0br\xa3\x01\xa4\xd7J\xbe\xabU\xc5\xcc\xad\x88" +
	"\x1bI\x05\xb4D\xbf\x06j\xf5;|\xe1\xf3\xba\x87^" +
	"\xdf\x86\xb8TVMo\xbehK?9\xf9\x02\xc0w" +
	"4z1\xe6\xdf\x89\x06\xf8Z\xa2=\xbc)\x06\xe0\xcb" +
	"\xb4\xbeY\xf9b\xdd\x80\xdf a\x96\xa6I\xff\x98\xd7" +
	"\x88\x81b@\x93\xb7\x96\xdd3\xe10\xbe\xf8\x02\x12\xb2" +
	"\xb4\x05\x851m`\xa0\x07\xc8\x82\xef\x14\xf1\xe0\xa03" +
	"_\xbd\xa0\x83\xaf.\x86\xc0\xb7P\xa8\x9f{$:v" +
	"'\xe2\xf2}3%0\x93\xf4\xc6\xb2\x87\xc3\x17\x17\xec" +
	"\xd2\xcd\xd4zgJ\xa6\x97\\\xb8T\x99\xb8\x87\xb0B" +
	"\xe4\xb7\x8f\xae\xf8\xe9\xa7\xc1\x8f\x82\xf6\xee\x985\x98_" +
	"\x07:\xf3\xabc<|+\xd1~\xe9'\xe1\xd7\xb7\x9e" +
	"o\xdc\xa3\xb3\xc2\xd1\x18b\x05G[i\xaa\xfb\\\xea" +
	"\x8b\xc4\x0a\xa1\xed\xd9\x8d\xa32?8\x0fr\xf6\xc7," +
	"\xc6\xfcq\"\xe7h\x8c\x87\xe7bA\xce\xaf?\x8cx" +
	"\xcf\xfd\xec\xd2\x17\x11\x97G\xe5\xb4\xc7d3(\xe8F" +
	"N\xfe\xf7\x1fLhzE\x98\xa7\xb9\xcf\xd5\x98\xf7\xc0" +
	":\x83c\xc1}f\xec+8\xcc~p\xe0\x00\xb8\x8f" +
	"\x16L\xb1\xc4}\xeac\x01\xa7\xdd\xd5\xa3\x93\x0ag5" +
	"\xfc\x91\xe8\xd1>1\xf1\x08sa\xc5)\xc2[q\x8b" +
	"1\x9f\x15\x07z\x8c\x8a\xf3\xf0u\xf0I\x8d\xddsn" +
	"\xfb\xc0\xab\x1b\x0e\xe9\x8d-\xc5\x11c\xd7\xc6\x81\xb1\x7f" +
	".\x1d[\xb46\xeb\xe0a$\x8c\xd3\xf6k\x88\x8b\x02" +
	"\x85\xf6\xc7\xc1~\x9fo\x9b\xb3\xf0\xeb\x83_\x1f\xd3+" +
	"T\x18O\x14\xba/\x1e\x16\xa8\x95;\x13\xf7\xd5\x9e\xfe" +
	"\x13p\x19\xdd\xe2\x9bx\xe02\x9e\x1b\x01[\x8c:6" +
	"\xfe\x8eY\xf3\xdfyS\xef\xd6Y#\x88[\x17\x92\x05" +
	"\xc9\xfc\xcf>+\x8a\xc8;\x8e\xb8yt^\x1eq\x1a" +
	"\xc0+\xbe6\xf4\xe8\xc8U\xcaq\xd8\x9c\x86\xbau\x04" +
	"\xd9\xbcn\x04\x84\xfa\x82\x84\x01\x7fz\xa0\xe9\xb9?#" +
	"n\x02\xfd\xa9`J\x80\x9f\x0eZzn\x89\xeb\xebW" +
	"\xde\x02V\xd2\xdc\xccDX\xc9j\x82]\xcb\x7f\x11_" +
	"9wD\xd0\x09\xc4M\xd6(\xd3T\x04?\xfd\xeag" +
	"q\xa3[\xff7\xa9Y\x17\xa1\xabM$B\xc3\x16\x15" +
	">\xb8\xfb\xafk\x9a\x117\x8aU\xab\x87\xf5\xdb\xd1Z" +
	"r\xff~0~\x9d\xe9e\xcco6\x81\xf17\x9a<" +
	"\xfcE\xf8\xa4\xde\xed\xfc\xef\xb7\xdf.\x1cp\x12lK" +
	"\xc1n2\x11\xdb^4\x01\xd8\xe6\xc84fB\xb1\xf0" +
	"6\xf1\xcd\x88\xc2\x8f\x83\x0e^\x9fy\x0d\xc4MOX" +
	"\x83\xf9\x07\x12@\xdc}\x09\x1e~w\x02\xc12\x7f\xd0" +
	"/\xdd\xfc\x89\x16=\x96\x1b\x13\x08\x96;\x12\xe0\x1f1" +
	"\xa6g\x17JC\xcaN#\xee.V\x15r\x1f\x99\xb7" +
	"p\x92\xb9\x05\xc4\x1dO8\x86\xf9\xf3D\\k\x82\x87" +
	"OO\x04qO\x875n3\xa5(\x7fG\xdc,*" +
	"\x8dK|\x19\xfe\x7f\xc5\xddK\xd5\xa7v\x9d:\x03\x88" +
	"\xb2\xda\x14AtT\"@>\xfb\xe1K\x9e\xc1\x9b\xc3" +
	"\xce\xea\xd9\xe6x\"a\x9b\x8b\x89\xa0I\xd8\xe07\xe5" +
	"\xb0w\x87\x9eE\\\x01\x9d\xc7I\x0f\x83\xec\xeb#?" +
	"\xdc\xbe\xea\xc6\x07g\x910O\x93}#\x91\x04\x80)" +
	"\x09d\xc79\xc7.[\xfa\xf6\xc8s\x90\xca\xa8\xd1^" +
	"M\"\xa9\xac5\x09\x8c\xa6\x1c\x1a\x98\xb5\xfe\x8b\xccV" +
	"}*\xceI&\xa9XH\x86\xcd\xed\xffu\xc7\xc4\xc2" +
	"\xb59\xad\xc0@Z\x08%\x13\x06\xda\x98\x0c[d\x9c" +
	"|r\xeb\xc93\x83\xfe\x01\\H%\xa4\xa7\x10.\x9c" +
	"\x9a\x02\x12*\xdb\x95\xd8\xb6\xc1\x97\xfe\x07q\xe3Y5" +
	"ul\xfd\x99?7\x8c}\x0c\x0c)\xa6\x141\xfc\xca" +
	"\x140d}\x8a\x87o\x81Oj\xd58\xe6\xf5\xc7\xb7" +
	"\x98\xcf\x83\x93j\x1a\xa7\x10'mJ\x01\x8d\xaf<\xb6" +
	"\xe2\xa9~|\xcbE\x9d\xa7%\xa7\x12O\xbbr\xe2\xf8" +
	"#g\x9f\xb8~I\x0f\xa9)\x95@\x9a\x93\x0a\x9a\xbc" +
	"\xdf\xfc\xfd\xca\x19\x7f\xaf\xf8\x10\xacA\x03`A*\xb1" +
	"\x86;\x15\x02\xa0\xf5\xdc\xf2\xa3\x1f\xa5<\xf1\xa1\x1e\x8a" +
	"\xc24\x02\x85\x94\x06\x12n\x9c\x1ez\xca<\xde\xf2)" +
	"\xe2\xc6i\xe9(-\x026\xffm\xfd\xf8\xf6\xe0=3" +
	".\xeb\xd4\xaaK#j\xbd\xdf\xff\xdc\xbb\xdbs\xde\xbf" +
	"\xacc\xc1\xda4\xc2\x82_N\x1c_\xb0+\xf2\xa1\xcf" +
	"H\x99\xf3\x93\xc9[V\xd4\xc5\xd5\x1d\x07\xcb\xc8i\x0c" +
	"\xc3\xafL#\x96I\xf3\xf0-\xf0I\x9d\xf4\x8fki" +
	"o|\xf4\xe0\x97\x84\xab\xbe\x89N\x8fX_\x9c{\x0c" +
	"V\xbf\x9a\xb6\x18\xf3\xcdduS\x9a\x87\x1f\x9e\x0e\xab" +
	"\x9fi,~g\x9b8\xe0\x1a)y\xbe,;\x9f?" +
	"\xf3B\xc4JX\x8d\xd3\xa71\xbc\x09\xd6\xf0\xb1\xe9\x1e" +
	"\xdeJVoj\xcb;\xb8 \xea\xa7\xdf\xe8t\\\x90" +
	"Nt\x8c\xba\xda\x8eS\xaf\xad\xb9\xae7\xc9\xf4tb" +
	"\x121\x1dL\xf2\xf1\xe2\xd5\x95\xe6y\xb3\xbf\x05\xabS" +
	"\xc0\xea\xd3\x89\xd57\xa7\x03`\xcem\xe3[\xee.\xfd" +
	"M\xbb\x9e\xd2\xae\xa6\x93\x00\x08\xcb\x00\x09\xa7V1U" +
	"\xa3\x7f'\xfe\x9f\x1e\xb7Q\x19D\xc2T\xb2\xa0\xeco" +
	"\x7f\x98\xf9\xee\xd8\x11\xdf\x91:w\xc3\x95\x98\xf7\x06\x1d" +
	"\xa88D<(\xc3\xc9\xf0+3\x88\x9d2<|\x0b" +
	"|R\xd7.\xdb\xf7\xeb\x8f\xc4\x94\xefu\x84\xf3j\x06" +
	"!\x9cu\x1b\x9c\xb9\x8d\x95\xe3T}4\xec\xcd \xf8" +
	"7g\xd4 \x15\xe5\xa86\xbbU,\x97\x97\xb8C\xa5" +
	"\xcc\x87d\x9bh+\x95EK\xa6\xd5n\x95l.\xb7" +
	"5S\xb6\xb9$\xa7M\xb4\x98KD\xa7Yq9%" +
	"[\xb9\xab\xe2\xaeR\xd1as\xe4\x15v\xccM\x13\x9d" +
	"\xc5.\xa7\x14\x0eS\xf31\x16B\xd9`]Y\x87m" +
	"\xfb\x8f\xd4\x8ci47pY\xd9\x88\xe1\x92C\xb0\xaf" +
	"\x10\xc1\x94e\xb9\xe1\x19\x88\xe1\xc2B\xe2k\x9c\xb2K" +
	"\xca\xc7\xe1ev\x9b\x94\x8f\xe7c\xac\xe9\xd7\xcfP?" +
	"W\x99Y\x91\x96\xb8%\x9bK\x16-\x1dz\xdd[V" +
	"\x0cC\xf1d\xcc\xa7\x10\xc5\xd5H!\x1ab\x98\x16\x87" +
	"~(\x14l\xa8\xd0\x12\xc5%\x97Vuh\"\x90/" +
	"\x08\xf9\x94\xa0\xbec\xa4\x04\xad\xec0u\x8f\x80\xad\"" +
	"UX$\xa7b~HV*$g\x87.\xd3\xc9\xd8" +
	"\x8cx2\xe6S\x88\x16\xa4F\x0a\xd1\x08\xc7\x94%\xfc" +
	"P\xa8\xbf\xa1B\x0e\xa7l+W\xcc\x8aC\x82q3" +
	"\xb5\xcf|2\\\xec\x1d\x9d}\x17HK*\x92\x14\xb7" +
	"\xc5\xa5 !\x88\x05\xc6\xc2\x08qay\x08\x09\xa1," +
	"\x16\"\x19<\xc5I\xe6\xf1@\xc4\xe0\x81\xc8\xb7o\x88" +
	"\xe1\xbe\x8a\xcb^Z!\x02\x0af\xa7\"w\xecZ\xac" +
	"\x0d\x16)\xb2\x0e\x1bZ\x89\x18\x99\x82\x16\x88\x98\xc6\xb6" +
	"\x1f\xa6\xb8ED\x95V\xc8V{\x95\xdb\\j\xb1\xbb" +
	"\xcbh(u\x0c\x16\x901j\x87p0\x84\x10\xa9\xd9" +
	"\xa1\xeea\x84\x84e,\x16~\xc5`\x0e\xe3H\xe0\x0e" +
	"n\xe5,\x84\x84\x15,\x1660\x98c\x98H\x88s" +
	"n]%B\xc2c,\x16\xb60\x98c\xd9HHd" +
	"\xdcf\x18|\x92\xc5\xc2v\x06sAA\x91\x90\x11\xb8" +
	"\xad%\x08\x09\xcf\xb0X\xd8\xc5`\xb5\xd4n\xab\x96\x9c" +
	"\x8a\x8c\xa6\xd8msd\x9b\xa4Y\xb9DT$\x18@" +
	"\x08ic\x16I,\x93m\xe5\xc5(\xdc!\xda\xa6\x1a" +
	"\x0fO\xf3\x0d\x8b\xe5\xe5\xb2\xad|\x0e\x0a\xd1\xcb\xbd\xbd" +
	"\xa9\xc4\x1aI\xb1[%\xb3])\x95-\x16\xd1e\xa7" +
	"\xbe<\xd5;q\x8f6\xaeC\x91R\x9e\x11\x8a\xb45" +
	"\xc0\xb4\xe1\x0d\xd8\xa1\xfdW\xad\x0b\x9a}\xe1\xd5~D" +
	"\x13k\x99\xed3\x09-y\x8cLBK-L\x8f(" +
	"\x02&\x9dR\xbb\xcdfw*\xba@+\xf0\x8e\x14)" +
	"X\xf6)C\xbbT#eh\xdb\x83i\xcd\xef\x872" +
	"\x03z\x9b\xb7\xc8\x0c\x91\x9f4_t\x8aV\xac\x08w" +
	"h M\xcf@H\xc8g\xb10G\x17r\x85\x09\x08" +
	"\x09\xff\xc1ba\xbe.\xe4\xe6f#$\xccd\xb1p" +
	"/\x83\xc3+\xe4\xf2\x0a\x0af\x88\xc5^C?\xc7\x97" +
	"Z\xec\xca\xcd\xee\x7f+\x83:\x1c\xf6\xd2*s\xa9\xdb" +
	"Y-i&%c\xf1\x050\xe63*\xad\xa8\x8d\x8c" +
	"J\x1b\x15L\x9b\xfc\x80\x11vT\xdb\xa9\xabU\xdb\xf5" +
	"&\xbb5[W\xdb-n\xab\xbf\xf1~\x9bd\xee\x1d" +
	"\xf2%\x08\xd6\xa5\x08\x83\xb4-E\xe0\xc0\x07Y,X" +
	"t(\xc9E\x08\x09\x15,\x16\\:\x94\x96\x00\x07:" +
	"X,,\xd3\x11c\xad\x13!\xe1\xe7,\x16V0X" +
	"-q\xd7\x16K.\xb7COu\x8ad\xb1\xc0 \xc2" +
	"\x0e\x1f%\xbak\x0b\xecn\x9b\x0b\x85\x97\xd9kl\x9d" +
	"\x96\xc28\x8awu\x1a\xbf=\x9d\x94V\x88r\x95l" +
	"\xbb\x99N\x0a\xbc\x13]\xe9d\xbe\xe8\x0c\x11\xadJw" +
	"x94\xbc\x1c\xb7\xc1+\xdb\x87W\x8f\xfc\xd3\x17\xe8" +
	"E\x8a\xdc\x1b\xf1\xa1=-b\xbcC\xbe\x1dY\xab\"" +
	"\x84j;\xa6C\xcc&\xb1X\x18\xad\xf3\x86Q\x10\xb3" +
	"i,\x16\xc6\xde&<{\xf4\x87{S\xad\xf4\xf3\xb7" +
	"v\xa4p\x87;\xf5p\x87\xf4\x94\x80)<S\xbc\xf8" +
	"\xf4\x0c\x9e\xbeaX\xea\xb7\xe0\x1e\xa8\x1b\xe8o\xc3|" +
	"\x84\xf8\xba\x10A_\xe4\xd4\x1a\xd9b\x91E\xabb\xa6" +
	"\xae\xb6\xb0c\xa0H\xf33\x82\xc1\x0f\x9e\x1b\x82\xfdu" +
	"\xc5\x0el\xb5\x1f\x06u\xf7CV\xd1\xa5ezrm" +
	"\x94A\xe8\xd9.\xa6\x87\xd3\x01\x97Mn\x8bK\xb6\x8a" +
	".\x83\xbaiA\xc7\xccM\x85\xd3\x14o\x84\xf5I\x80" +
	"\x81\x9b\x8aUZ\x1b@\xbet\xb8R| \xbb\xf4M" +
	"m\xd8\x95\xcc{\xd77\xf8'\xad\xfb\xc6\xc8X\x9a\xb1" +
	"7v\xe2h/;\xeb\x9b^z\xf2h\xe4[\xf4\xec" +
	"\x02\xd3\xa3\xe6\x80;og\xb5\xe6\xd9\xd5=\x0a\x09]" +
	"Y\xc3V\xdb}j\xd3\x9b$#\xb5\xe9\x11\x17\xa6\x07" +
	"\xee~\xa8\x1d\x00k{1\x88\xef\xfc/\x06t\x87\xe8" +
	"M\x8e\xe7\x03\xd6\xa0/\xf1r\xa8.}F\x18\xa5\xcf" +
	"\x08_\xfa\xc4U4\x10p\x99\x9f\x81\xd7\xb9r\xec\x9c" +
	"9u\x84\x9a`D\xa8yF\x84\x0a\xb5\xdd\x1c\x16\x0b" +
	"\x8b\x18\x1c\xe2\xa8\xb6S5\xa6(r\xb9M\xb4hZ" +
	"U\xc8\x8a\xcb^\xee\x14\x11\xb6\xde\xa4iPw^\xc4" +
	"V\xeb\xf8\x91^%\x189\x03\xbd\xf5\xc1\xf4(7\xe0" +
	"\x0a\xdb \x90zEP\xc6.'Y\xca$\xa7\xd9)" +
	"\xd6\xd2\xaa\x0a\xbe\x17\x89\xb5]*\xaa\x7f\x8f.\xa8s" +
	"\x11\xdb\xd7\xae\xe3\x08\xc8u\x02\xe6\xd4\xce\xa5D\x8f\xaa" +
	"\xb0@\xd9#\xc0\x04\xda\x97$\xd3\xd1VwW]w" +
	"\xe2\xef\xce\xed\x84\xae\xd5\x03W\xfcO\x16\x0b\x15:\xa0" +
	"\xa5\x0c]\xffG\x81\x96\xc1%\xcaX,8t\xad\x9e" +
	"5\xdb\xd7\x14\x86\xdb\x1d\x92\xd6\xa0\xf5\xd4Y{\\E" +
	"\x1a\xa6\xd3>,\xad\xbdA\x81{\x8aso\x0ap\xff" +
	"p\xbde\xd1\xd5\xb5\xab\x09\xf6\x97\xac\xe2\x09[\xf9\xb8" +
	"\x99^B\x1bq3\xbd\xbf\xc2\xf465\xe0D}K" +
	"\xd6\xbce\"-\xf2\xe5L\xcdU\xb3`p4\x8b\x85" +
	"\x89\xe4\xac\xc1b\x99o\xaf\x91\x10v\xfa\xce\x15$\xd1" +
	"\xd9u\xec\xf6\x1620\xb0\xbe\xfa\xa2\x97\x84F\xd6\xa1" +
	"W\xd5\x98\xbe\xaa\xe8\xd3\xcc\xd5\x11\xc3\xf1\x01\xf4\x9c\xfd" +
	"z\x18^\xba\xffK\x9f\xaa\x18\xfd_z\xdf\x8f\xe9\x1d" +
	"\xee\x0f\xd8\xc9t-\xe3\x02.\xf3\x7f\xdc~4@\xc2" +
	"\xe8\\Z\xdc\xc2\x17\xaaE\x8b\xdb\xdf\x1d{p\xa5\xd4" +
	"\xb5\x0d\xe8\xa3\xdc\xf6\xe3VK}s\x90\xa8\xddK\xe8" +
	"h+\xca\xa8\xfe\x8f\xf2q\x19[\xaa\x15M\xacX\xe6" +
	"\xa7b\xfe\xc1\xd5\x8bC\xc4>\x08\xd3\xcegd?4" +
	"\xa0\x81U\x14\x01^,\x85\xf6\xd6ZXw\x87L_" +
	"\xcc\x181.}&\x84\xe9\xc3\xbe\x803\x8cA\x7f\xaf" +
	"5\x02:\xefM0\xf2\xde<\x9f\xf7\x868\xab\xe5[" +
	"\xd5\xfc}q=\x11xQ\xd4\x8bt\xd9k2\xe8\x9c" +
	"S\xba+\xb7\x13\x8c\xca\xedl\xa3r;OWn\xfb" +
	"\x17\x0f=\xbb2\xea\xf6\x92\xa0\xefO\x8ao_\x07v" +
	"\x85\xbf7jw\x95\x15\xec\xef\xd9J\xd7\x84\x17\x12`" +
	"\xa9\xa1\xab\xaa\xe8\xa3>\xa3\x18\xa7\xefj1}\x97\xee" +
	"G\x8c\x07u\xd7\xec\xb3\x0e\xddQ\x1c}xm\xb4;" +
	"}\xc9\x85\xe9S\xd3\x80\x9ff\xf8\x1f/:\xc3\xd0'" +
	"vF\xaa\xd1\x97\xe4\x98\xbeJ\x0c\xf8p\xd3\xe0\x14\xa4" +
	"+\xc8\x01\x92\x96_\x85YO\x8at\xa3[\xac\xce\xd4" +
	"\xd6\xddU]\xb6\xee\xaaN\xdf\xa3\xf7\xa8\"\xf5\xf7\x84" +
	";\xc0\x04\xda\xc3\x1b\xbc\x00\xcf\xefB{[\xa9\xc6\x93" +
	"9\x9f\xb7\xd2\xf7\xb3F\xdeJ\xdfQ\xe3\x1c\xe4}d" +
	"\xde\xf7\xc7\x98][\xfe^_\xa0t\xce[}q\x07" +
	"\xfc\xff\x01\x00\x00\xff\xff\x84~\xa8\x89"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a625f78f3dbd3a99,
		Nodes: []uint64{
			0x802a0b33ad82f5c9,
			0x813e454339626a25,
			0x81a40d13d06924ce,
			0x8255063f58bc12b4,
			0x86cd49c809864f41,
			0x88fce2b7d0c058b0,
			0x89aca504289bcbf1,
			0x8a3c91a40bb0e7b8,
			0x8a76ce35697c4238,
			0x8b6f4b3133adc7ae,
			0x8be20f547c9e0998,
			0x8e72ce7589bb5be1,
			0x8f70c9a7c9ef1bf3,
			0x91b6d69c779bb00e,
			0x91ec9f43d089bec7,
			0x9348e26793eb0f1e,
			0x94a78a0b6ea5536f,
			0x94d831330471f29d,
			0x952b7ea0593d4db7,
			0x96cbb05f9fd76b2c,
			0x9894f493a4ead65b,
			0x99aa5f1d5327b693,
			0x99b383ae4086cdfe,
			0x9af2254c086c9aae,
			0x9c24698f08ee10d4,
			0x9d2f61ff79fc62ba,
			0x9ebb667dece0be06,
			0xa30a7dab6ac46d2f,
			0xa6e101be384f7cc8,
			0xa6f0d410b76173fc,
			0xa71d1bc04d815157,
			0xa8435a0f7a7cbc24,
			0xaa236ae2e0624562,
			0xaa9add9df60fe77b,
			0xab27d8752763f270,
			0xab7b9f75da12e397,
			0xb3c938dffe400035,
			0xb6b6df03be43ae46,
			0xb8994a49243076a9,
			0xbd90f10ba0d8aa1d,
			0xbeb7318b58c26578,
			0xc2f4b7f4574c9eec,
			0xc3d279ae23a76aff,
			0xc4d5504a0c37c22d,
			0xc53a1252eb561325,
			0xc573862bc117f353,
			0xc6a2c95dc30a2255,
			0xc8b3f47471d87b10,
			0xcb04204d6a1f7f67,
			0xcd24f8d9301e56f0,
			0xcd8acaa96049580d,
			0xce0a49cfcfbf723b,
			0xcf5153380228145f,
			0xd1cb13758010401d,
			0xd2641665579f2102,
			0xd37326219e9a0d9b,
			0xd4d0a896ff7b3b68,
			0xd60d951587e27a4b,
			0xd617d70d69c4150d,
			0xd6dffd86a0e32bf6,
			0xd82bcf7b7c34721e,
			0xd92fed8f310bbd73,
			0xd9358b493c0c5e6f,
			0xdb10d4ce9d94ce2a,
			0xdce215f21d73f96a,
			0xdd5f988ebb02366b,
			0xe1d1130696848cea,
			0xe2f692d67ec5cbea,
			0xe368d34685fecdde,
			0xe39226e4c182d8d9,
			0xe86c375fd017d2fd,
			0xe946aa05f93781ac,
			0xe9de35a0d7d809de,
			0xeb6614a843373cee,
			0xee60e4bc28f3db3d,
			0xf30a619ed5539a9c,
			0xf5471a55b73af293,
			0xf68af32701f9f11a,
			0xf74b4e5f6a895ae6,
			0xf9a3633bd1379e72,
			0xfb61af306b0286d0,
			0xfc2034d748b5cc64,
			0xfe2661e497ae7c8b,
			0xff366a9a3972908d,
		},
		Compressed: true,
	})
}
