// Code generated by capnpc-go. DO NOT EDIT.

package momentum

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
	math "math"
)

type Ppo capnp.Client

// Ppo_TypeID is the unique identifier for the type Ppo.
const Ppo_TypeID = 0xee60e4bc28f3db3d

func (c Ppo) Write(ctx context.Context, params func(Ppo_write_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xee60e4bc28f3db3d,
			MethodID:      0,
			InterfaceName: "nomagique/financial/momentum/ppo.capnp:Ppo",
			MethodName:    "write",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 8, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Ppo_write_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c Ppo) Done(ctx context.Context, params func(Ppo_done_Params) error) (Ppo_done_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xee60e4bc28f3db3d,
			MethodID:      1,
			InterfaceName: "nomagique/financial/momentum/ppo.capnp:Ppo",
			MethodName:    "done",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Ppo_done_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Ppo_done_Results_Future{Future: ans.Future()}, release

}

func (c Ppo) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Ppo) String() string {
	return "Ppo(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Ppo) AddRef() Ppo {
	return Ppo(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Ppo) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Ppo) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Ppo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Ppo) DecodeFromPtr(p capnp.Ptr) Ppo {
	return Ppo(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Ppo) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Ppo) IsSame(other Ppo) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Ppo) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Ppo) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Ppo_Server is a Ppo with a local implementation.
type Ppo_Server interface {
	Write(context.Context, Ppo_write) error

	Done(context.Context, Ppo_done) error
}

// Ppo_NewServer creates a new Server from an implementation of Ppo_Server.
func Ppo_NewServer(s Ppo_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Ppo_Methods(nil, s), s, c)
}

// Ppo_ServerToClient creates a new Client from an implementation of Ppo_Server.
// The caller is responsible for calling Release on the returned Client.
func Ppo_ServerToClient(s Ppo_Server) Ppo {
	return Ppo(capnp.NewClient(Ppo_NewServer(s)))
}

// Ppo_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Ppo_Methods(methods []server.Method, s Ppo_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 2)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xee60e4bc28f3db3d,
			MethodID:      0,
			InterfaceName: "nomagique/financial/momentum/ppo.capnp:Ppo",
			MethodName:    "write",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Write(ctx, Ppo_write{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xee60e4bc28f3db3d,
			MethodID:      1,
			InterfaceName: "nomagique/financial/momentum/ppo.capnp:Ppo",
			MethodName:    "done",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Done(ctx, Ppo_done{call})
		},
	})

	return methods
}

// Ppo_write holds the state for a server call to Ppo.write.
// See server.Call for documentation.
type Ppo_write struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Ppo_write) Args() Ppo_write_Params {
	return Ppo_write_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Ppo_write) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// Ppo_done holds the state for a server call to Ppo.done.
// See server.Call for documentation.
type Ppo_done struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Ppo_done) Args() Ppo_done_Params {
	return Ppo_done_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Ppo_done) AllocResults() (Ppo_done_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return Ppo_done_Results(r), err
}

// Ppo_List is a list of Ppo.
type Ppo_List = capnp.CapList[Ppo]

// NewPpo_List creates a new list of Ppo.
func NewPpo_List(s *capnp.Segment, sz int32) (Ppo_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Ppo](l), err
}

type Ppo_write_Params capnp.Struct

// Ppo_write_Params_TypeID is the unique identifier for the type Ppo_write_Params.
const Ppo_write_Params_TypeID = 0x94a78a0b6ea5536f

func NewPpo_write_Params(s *capnp.Segment) (Ppo_write_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Ppo_write_Params(st), err
}

func NewRootPpo_write_Params(s *capnp.Segment) (Ppo_write_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return Ppo_write_Params(st), err
}

func ReadRootPpo_write_Params(msg *capnp.Message) (Ppo_write_Params, error) {
	root, err := msg.Root()
	return Ppo_write_Params(root.Struct()), err
}

func (s Ppo_write_Params) String() string {
	str, _ := text.Marshal(0x94a78a0b6ea5536f, capnp.Struct(s))
	return str
}

func (s Ppo_write_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Ppo_write_Params) DecodeFromPtr(p capnp.Ptr) Ppo_write_Params {
	return Ppo_write_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Ppo_write_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Ppo_write_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Ppo_write_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Ppo_write_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Ppo_write_Params) Close() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Ppo_write_Params) SetClose(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

// Ppo_write_Params_List is a list of Ppo_write_Params.
type Ppo_write_Params_List = capnp.StructList[Ppo_write_Params]

// NewPpo_write_Params creates a new list of Ppo_write_Params.
func NewPpo_write_Params_List(s *capnp.Segment, sz int32) (Ppo_write_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[Ppo_write_Params](l), err
}

// Ppo_write_Params_Future is a wrapper for a Ppo_write_Params promised by a client call.
type Ppo_write_Params_Future struct{ *capnp.Future }

func (f Ppo_write_Params_Future) Struct() (Ppo_write_Params, error) {
	p, err := f.Future.Ptr()
	return Ppo_write_Params(p.Struct()), err
}

type Ppo_done_Params capnp.Struct

// Ppo_done_Params_TypeID is the unique identifier for the type Ppo_done_Params.
const Ppo_done_Params_TypeID = 0xf5471a55b73af293

func NewPpo_done_Params(s *capnp.Segment) (Ppo_done_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Ppo_done_Params(st), err
}

func NewRootPpo_done_Params(s *capnp.Segment) (Ppo_done_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return Ppo_done_Params(st), err
}

func ReadRootPpo_done_Params(msg *capnp.Message) (Ppo_done_Params, error) {
	root, err := msg.Root()
	return Ppo_done_Params(root.Struct()), err
}

func (s Ppo_done_Params) String() string {
	str, _ := text.Marshal(0xf5471a55b73af293, capnp.Struct(s))
	return str
}

func (s Ppo_done_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Ppo_done_Params) DecodeFromPtr(p capnp.Ptr) Ppo_done_Params {
	return Ppo_done_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Ppo_done_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Ppo_done_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Ppo_done_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Ppo_done_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// Ppo_done_Params_List is a list of Ppo_done_Params.
type Ppo_done_Params_List = capnp.StructList[Ppo_done_Params]

// NewPpo_done_Params creates a new list of Ppo_done_Params.
func NewPpo_done_Params_List(s *capnp.Segment, sz int32) (Ppo_done_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[Ppo_done_Params](l), err
}

// Ppo_done_Params_Future is a wrapper for a Ppo_done_Params promised by a client call.
type Ppo_done_Params_Future struct{ *capnp.Future }

func (f Ppo_done_Params_Future) Struct() (Ppo_done_Params, error) {
	p, err := f.Future.Ptr()
	return Ppo_done_Params(p.Struct()), err
}

type Ppo_done_Results capnp.Struct

// Ppo_done_Results_TypeID is the unique identifier for the type Ppo_done_Results.
const Ppo_done_Results_TypeID = 0xc2f4b7f4574c9eec

func NewPpo_done_Results(s *capnp.Segment) (Ppo_done_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return Ppo_done_Results(st), err
}

func NewRootPpo_done_Results(s *capnp.Segment) (Ppo_done_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0})
	return Ppo_done_Results(st), err
}

func ReadRootPpo_done_Results(msg *capnp.Message) (Ppo_done_Results, error) {
	root, err := msg.Root()
	return Ppo_done_Results(root.Struct()), err
}

func (s Ppo_done_Results) String() string {
	str, _ := text.Marshal(0xc2f4b7f4574c9eec, capnp.Struct(s))
	return str
}

func (s Ppo_done_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Ppo_done_Results) DecodeFromPtr(p capnp.Ptr) Ppo_done_Results {
	return Ppo_done_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Ppo_done_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Ppo_done_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Ppo_done_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Ppo_done_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Ppo_done_Results) Ppo() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s Ppo_done_Results) SetPpo(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s Ppo_done_Results) Signal() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s Ppo_done_Results) SetSignal(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s Ppo_done_Results) Histogram() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s Ppo_done_Results) SetHistogram(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

// Ppo_done_Results_List is a list of Ppo_done_Results.
type Ppo_done_Results_List = capnp.StructList[Ppo_done_Results]

// NewPpo_done_Results creates a new list of Ppo_done_Results.
func NewPpo_done_Results_List(s *capnp.Segment, sz int32) (Ppo_done_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 0}, sz)
	return capnp.StructList[Ppo_done_Results](l), err
}

// Ppo_done_Results_Future is a wrapper for a Ppo_done_Results promised by a client call.
type Ppo_done_Results_Future struct{ *capnp.Future }

func (f Ppo_done_Results_Future) Struct() (Ppo_done_Results, error) {
	p, err := f.Future.Ptr()
	return Ppo_done_Results(p.Struct()), err
}
